"""
#autogenerated#header#do#not#modify############################################
#
# File:        test_fortran_builder_comm_1.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   14/08/2025
# Last Update: 25/08/2025, 14:57
# Version:     0.0.244
#
#################################################end#of#autoheader#do#not#modify


"""


# Load from the instruction library
from phoenix.fgen.instruction import (
    BiLinearOperationInstruction,
    CallInstruction,
    InstructionGroup,
    InstructionEnvironment,
    MapApplyInstruction,
)

# load instruction variables
from phoenix.fgen.instructionvar import InstructionVariable

# We will use the KeyMap class to express our operations in terms
# of readable keys rather than keeping track of the indices where those
# entries are stored.
from phoenix.keymap import KeyMap

# this part will later be automatized by the choice of backend, but it is
# probably useful to understand what is going on under the hood.
from phoenix.fgen.fortran_builder import (
    F90Builder,
    F90Library,
    F90InputVariable,
    F90OutputVariable,
    F90KernelContainer,
    F90RoutineContainer,
)


from phoenix.adaa_derived import FortranCA, FortranRA
from phoenix.fgen.libroutinevar import LibRoutineVariable


# USEFUL SETTINGS
# ===============

# Some parameters that define the subspace
MAX_SIZE = 4
NUM_SPINS = 15
NUM_SPINS_EXPLORE = MAX_SIZE + MAX_SIZE // 2
REAL_ONLY = True

my_builder = F90Builder("my_f90_builder")

pauli_table = {
    "0": {"0": ("0", 0), "x": ("x", 0), "y": ("y", 0), "z": ("z", 0)},
    "x": {"0": ("x", 0), "x": ("0", 0), "y": ("z", 1), "z": ("y", 3)},
    "y": {"0": ("y", 0), "x": ("z", 3), "y": ("0", 0), "z": ("x", 1)},
    "z": {"0": ("z", 0), "x": ("y", 1), "y": ("x", 3), "z": ("0", 0)},
}


def all_pauli_strings(string_size, prefix=""):
    """Recursively generate all pauli strings of given string_size"""
    if string_size <= 0:
        yield prefix
    else:
        yield from all_pauli_strings(string_size - 1, prefix=f"{prefix}x")
        yield from all_pauli_strings(string_size - 1, prefix=f"{prefix}y")
        yield from all_pauli_strings(string_size - 1, prefix=f"{prefix}z")


def pauli_comm(string_a, string_b, coeff_phase=0):
    """commutate two pauli strings of same length"""
    assert len(string_a) == len(string_b)
    result_ab = ""
    result_ba = ""
    coeff_phase_ab = 0
    coeff_phase_ba = 0
    for letter_a, letter_b in zip(string_a, string_b):
        letter_ab, letter_phase_ab = pauli_table[letter_a][letter_b]
        letter_ba, letter_phase_ba = pauli_table[letter_b][letter_a]
        result_ab += letter_ab
        result_ba += letter_ba
        coeff_phase_ab += letter_phase_ab
        coeff_phase_ba += letter_phase_ba

    if result_ab == result_ba:
        if (
            abs(factor := (1j ** (coeff_phase_ab) - 1j ** (coeff_phase_ba)))
            > 1e-12
        ):
            return result_ab, factor
        return None, None
    raise SystemError("That's weird!")


def pad_pauli_string(reduced, nums, size):
    """Create a padded string from a reduced string.
    E.g. having a string xyz at spins 2,4,6 in a subspace of length 8,
    we call pad_pauli_string('xyz', (2,4,6), 8) and receive '0x0y0z00'.
    """
    padded = ["0"] * size
    for letter, num in zip(reduced, nums):
        padded[num] = letter
    return "".join(padded)


def simplify_pauli_string(padded):
    """Reduce a string, i.e. invert the padding as opposed to pad_pauli_string.
    From '0x0y0z00' we get 'xyz', (2,4,6).
    """
    nums = []
    reduced = ""
    for num, letter in enumerate(padded):
        if letter == "0":
            continue
        nums.append(num)
        reduced += letter
    return reduced, tuple(nums)


def all_spin_groups(size, num_spins, collect=[]):
    """
    Recursively generate all spin groups made from <num_spins> spins that you
    can find in a subspace of size <size>.
    """
    if size == 0:
        yield tuple(collect)
    else:
        for num in range(max(collect + [-1]) + 1, num_spins):
            yield from all_spin_groups(size - 1, num_spins, collect + [num])


def triple_pattern(string_a, string_b, string_c):
    """
    As will be shown below, the operations group into basic patterns that can be
    identified from the location of the non-identity contributions in the pauli
    strings of inputs and output. This routine provides a pattern-tuple that
    directly associates the proper suboperation to it.
    """
    pat_a = ""
    pat_b = ""
    pat_c = ""
    assert len(string_a) == len(string_b) == len(string_c)
    for let_a, let_b, let_c in zip(string_a, string_b, string_c):
        if let_a != "0" or let_b != "0" or let_c != "0":
            pat_a += "X" if let_a in "xyz" else "_"
            pat_b += "X" if let_b in "xyz" else "_"
            pat_c += "X" if let_c in "xyz" else "_"
    return (pat_a, pat_b, pat_c)


def nice_phase(integer_phase):
    """aux routine to express the complex phase in a nice way"""
    integer_phase %= 4
    if integer_phase == 0:
        return ""
    if integer_phase == 2:
        return "- "
    if integer_phase == 1:
        return "i "
    if integer_phase == 3:
        return "-i "
    raise RuntimeError("you should never see this.")


#######################################################################

# in this dictionary we remember the the individual keymaps for later
inner_keymaps_system = {}

# a parent keymap for the state of the system
system_keymap = KeyMap(name="system")
system_explore_keymap = KeyMap(name="system explore")

# the scalar contribution...
scalar_keymap = KeyMap(name="pauli_0")
# ... has only a single entry that we identify by the empty string
scalar_keymap.entry("")

# we will link the individual component keymaps for size n to all the spin groups that
# have size n. For the scalar keymap (no spins included), this is the empty tuple
system_keymap.link(tuple(), scalar_keymap)
inner_keymaps_system[0] = scalar_keymap

# we use a set of fewer spins to explore the various auxiliary routines, but we will
# apply them in large scale to the full model
system_explore_keymap.link(tuple(), scalar_keymap)


# using the aux methods from before, we can now conveniently generate the spin index
# groups of size n and the components for size n
for size in range(1, MAX_SIZE + 1):
    # we create the component keymap of size <size>. For size 2, this is xx, xy, ... zz
    keymap = KeyMap(name=f"pauli_{size}")
    for substring in all_pauli_strings(size):
        keymap.entry(substring)
    inner_keymaps_system[size] = keymap
    # now, for every spin index tuple of size <size>, we associate that component keymap
    # to it
    for number_tuple in all_spin_groups(size, NUM_SPINS):
        system_keymap.link(number_tuple, keymap)
    for number_tuple in all_spin_groups(size, NUM_SPINS_EXPLORE):
        system_explore_keymap.link(number_tuple, keymap)


#######################################################################


inner_keymaps_hamilt = {}
hamilton_keymap = KeyMap(name="hamiltonian")
hamilton_explore_keymap = KeyMap(name="hamiltonian explore")

keymap_larmor = KeyMap(name=f"ham_single")
keymap_larmor.entry("x")
keymap_larmor.entry("y")
keymap_larmor.entry("z")

keymap_dipdip = KeyMap(name="dipdip")
keymap_dipdip.entry("xx")
keymap_dipdip.entry("yy")
keymap_dipdip.entry("zz")

inner_keymaps_hamilt[1] = keymap_larmor
inner_keymaps_hamilt[2] = keymap_dipdip

for number_tuple in all_spin_groups(1, NUM_SPINS):
    hamilton_keymap.link(number_tuple, keymap_larmor)

for number_tuple in all_spin_groups(2, NUM_SPINS):
    hamilton_keymap.link(number_tuple, keymap_dipdip)

for number_tuple in all_spin_groups(1, NUM_SPINS_EXPLORE):
    hamilton_explore_keymap.link(number_tuple, keymap_larmor)

for number_tuple in all_spin_groups(2, NUM_SPINS_EXPLORE):
    hamilton_explore_keymap.link(number_tuple, keymap_dipdip)


#######################################################################


VarRes = InstructionVariable.new(name="res", config=system_keymap)
VarRho = InstructionVariable.new(name="rho", config=system_keymap)
VarHam = InstructionVariable.new(name="ham", config=hamilton_keymap)


commutate_operations = {}
commutate_cases = {}


# we go through the system keymaps first hierarchy level
# the micro operation part, we do on the explore-level keymaps
for nums_a_key, nums_a_entry in system_explore_keymap.items():
    nums_a = nums_a_key.onlylabel()
    for nums_b_key, nums_b_entry in hamilton_explore_keymap.items():
        nums_b = nums_b_key.onlylabel()

        for keys_a_key in nums_a_entry.keys():
            keys_a = keys_a_key.onlylabel()
            ext_string_a = pad_pauli_string(keys_a, nums_a, NUM_SPINS_EXPLORE)
            for keys_b_key in nums_b_entry.keys():
                keys_b = keys_b_key.onlylabel()
                ext_string_b = pad_pauli_string(
                    keys_b, nums_b, NUM_SPINS_EXPLORE
                )

                ext_prod_c, factor = pauli_comm(ext_string_a, ext_string_b)

                if ext_prod_c is None:
                    continue

                # the t_pattern helps us to group operations
                t_pattern = triple_pattern(
                    ext_string_a, ext_string_b, ext_prod_c
                )

                # final validity check - still in truncated subspace?
                if t_pattern[-1].count("X") > MAX_SIZE:
                    continue

                # init?
                if t_pattern not in commutate_operations:
                    commutate_operations[t_pattern] = {}
                    commutate_cases[t_pattern] = set()

                # have we seen this component combination before in this pattern?
                if (keys_a, keys_b) not in commutate_operations[t_pattern]:
                    commutate_operations[t_pattern][(keys_a, keys_b)] = set()

                # we perform the multiplication
                keys_c, nums_c = simplify_pauli_string(ext_prod_c)

                # we remember the result. The set datattype avoids duplicates.
                commutate_operations[t_pattern][(keys_a, keys_b)].add(
                    (keys_c, factor)
                )


def get_target_variations(
    nums_a,
    nums_b,
    _combined=None,
    _nums_c=None,
    _t_a=None,
    _t_b=None,
    _t_c=None,
):
    """get all possible target variations from nums_a, nums_b and corresponding t_patterns"""
    if _combined is None:
        _combined = set.union(set(nums_a), set(nums_b))

    if _nums_c is None:
        _nums_c = []

    if _t_a is None:
        _t_a = ""

    if _t_b is None:
        _t_b = ""

    if _t_c is None:
        _t_c = ""

    if len(_combined) > 0:
        num = sorted(_combined)[0]
        if num in nums_a and num in nums_b:
            # cancellation case
            yield from get_target_variations(
                nums_a,
                nums_b,
                _combined=_combined - {num},
                _nums_c=_nums_c,
                _t_a=_t_a + "X",
                _t_b=_t_b + "X",
                _t_c=_t_c + "_",
            )
            # survive case
            yield from get_target_variations(
                nums_a,
                nums_b,
                _combined=_combined - {num},
                _nums_c=_nums_c + [num],
                _t_a=_t_a + "X",
                _t_b=_t_b + "X",
                _t_c=_t_c + "X",
            )
        elif num in nums_a:
            yield from get_target_variations(
                nums_a,
                nums_b,
                _combined=_combined - {num},
                _nums_c=_nums_c + [num],
                _t_a=_t_a + "X",
                _t_b=_t_b + "_",
                _t_c=_t_c + "X",
            )
        elif num in nums_b:
            yield from get_target_variations(
                nums_a,
                nums_b,
                _combined=_combined - {num},
                _nums_c=_nums_c + [num],
                _t_a=_t_a + "_",
                _t_b=_t_b + "X",
                _t_c=_t_c + "X",
            )
    else:
        yield tuple(_nums_c), (_t_a, _t_b, _t_c)


# This time, we identify the cases based on the larger set of spins
for nums_a_key, nums_a_entry in system_keymap.items():
    nums_a = nums_a_key.onlylabel()
    for nums_b_key, nums_b_entry in hamilton_keymap.items():
        nums_b = nums_b_key.onlylabel()

        # create the various t-patterns that this set of nums could contribute
        # to

        print(nums_a, nums_b)
        for nums_c, t_pattern in get_target_variations(nums_a, nums_b):
            if t_pattern in commutate_cases:
                print("->", t_pattern, nums_c)
                commutate_cases[t_pattern].add((nums_a, nums_b, nums_c))
                assert len(nums_c) <= MAX_SIZE


my_library = F90Library("pauli_library_comm")

if REAL_ONLY:
    System_ADAA = FortranRA.set_keymap(system_keymap)
    Hamilton_ADAA = FortranRA.set_keymap(hamilton_keymap)
else:
    System_ADAA = FortranCA.set_keymap(system_keymap)
    Hamilton_ADAA = FortranCA.set_keymap(hamilton_keymap)

daa_assignments = {
    VarRho: (System_ADAA, LibRoutineVariable.STATUS_INPUT),
    VarRes: (System_ADAA, LibRoutineVariable.STATUS_INOUT),
    VarHam: (Hamilton_ADAA, LibRoutineVariable.STATUS_INPUT),
}


# lrv_assignments = {
#     (VarRho, "real"): F90InputVariable(
#         assignment=(VarRho, "real"), name="rho_real", size=system_keymap.size
#     ),
#     (VarRho, "imag"): F90InputVariable(
#         assignment=(VarRho, "imag"), name="rho_imag", size=system_keymap.size
#     ),
#     (VarHam, "real"): F90InputVariable(
#         assignment=(VarHam, "real"), name="ham_real", size=hamilton_keymap.size
#     ),
#     (VarHam, "imag"): F90InputVariable(
#         assignment=(VarHam, "imag"), name="ham_imag", size=hamilton_keymap.size
#     ),
#     (VarRes, "real"): F90OutputVariable(
#         assignment=(VarRes, "real"), name="res_real", size=system_keymap.size
#     ),
#     (VarRes, "imag"): F90OutputVariable(
#         assignment=(VarRes, "imag"), name="res_imag", size=system_keymap.size
#     ),
# }


VarInpRInner = {}
VarInpHInner = {}
VarTargInner = {}

# Input rho goes up to max_size + 1.
# At the same time, the targets can also be restricted to these subspaces
for size in range(MAX_SIZE + 1):
    VarInpRInner[size] = InstructionVariable.new(
        name=f"rho_inner_{size}", config=inner_keymaps_system[size]
    )
    VarTargInner[size] = InstructionVariable.new(
        name=f"res_inner_{size}", config=inner_keymaps_system[size]
    )

# Input ham can contribute to single and pair terms
VarInpHInner[1] = InstructionVariable.new(
    name=f"ham_inner_{size}", config=inner_keymaps_hamilt[1]
)
VarInpHInner[2] = InstructionVariable.new(
    name=f"ham_inner_{size}", config=inner_keymaps_hamilt[2]
)


# As we will later call all auxiliary routines in a summarizing call, we can collect them here
libroutines = {}

instruction_groups = {}
for num, (t_pattern, operations) in enumerate(commutate_operations.items()):
    instructions = []

    # understand where we look for rho, ham and res by counting the X's in the t_pattern
    len_r, len_h, len_t = map(lambda x: x.count("X"), t_pattern)

    # we define the local variables
    target_variable = VarTargInner[len_t]
    rho_variable = VarInpRInner[len_r]
    ham_variable = VarInpHInner[len_h]

    # The convenience in the Instruction variables is, that they are callable
    # and will represent an access at an offset. These offsets can be stacked,
    # which will simplify the access patterns even further.

    # for all the operations we want to perform, we remember to do a
    # BiLinearOperationInstruction, which is basically z[l] = a * x[j] * y[k]
    for (src1_key, src2_key), operation in operations.items():
        for tgt_key, factor in operation:
            # Here, we create the actual instruction. The Builder will decide, how to turn that
            # into code, the instruction level is completely abstract
            instruction = BiLinearOperationInstruction(
                target_variable(tgt_key),
                rho_variable(src1_key),
                ham_variable(src2_key),
                factor * 1j,
            )
            # we remember the instructions though, because we will call them many times for
            # all the index combinations that match the t_pattern
            instructions.append(instruction)

    instruction_groups[t_pattern] = InstructionGroup(instructions)


for num, (t_pattern, cases) in enumerate(commutate_cases.items()):
    # we will use an Environment Instruction. This instruction will add offsets to  instruction
    # variables. You can read in InstructionEnvironment as 'everything in here will be interpreted
    # as seen from this offset'. Performing the component operations from different offsets means
    # creating an offset environment for all the matching index groups and mapping all these
    # environments on the component operations.

    environments = []
    for case in cases:
        rho_nums, ham_nums, res_nums = case

        # we will create an instruction environment and put it to the other environments
        # relevant for the t_pattern
        environments.append(
            InstructionEnvironment(
                {
                    VarInpRInner[len(rho_nums)]: VarRho(rho_nums),
                    VarInpHInner[len(ham_nums)]: VarHam(ham_nums),
                    VarTargInner[len(res_nums)]: VarRes(res_nums),
                }
            )
        )

    # we now want all the instruction environments being applied to the same instruction group (that
    # takes care of the component operations). And that's it! That's everything we need to do to
    # cover one of the t_patterns in our KeyMap configurations
    these_instructions = [
        MapApplyInstruction(
            content=instruction_groups[t_pattern],
            environments=environments,
        )
    ]

    # having collected all the environments, we can put it into a routine and give it a telling name
    lr_name = f"commutate_{num:03d}"

    # this is the crucial step: We create a libroutine (that is now in a specific target language)
    # from the instructions we have now created. We can reuse the same instructions in another
    # library and even in another language backend.
    libroutine = my_library.libroutine_from_instructions(
        lr_name,
        *these_instructions,
        builder=my_builder,
        daa_assignments=daa_assignments,
        # lrv_assignments=lrv_assignments,
        # container_class=F90KernelContainer,
        container_class=F90RoutineContainer,
    )
    # Note that the assignments tell the building process what variables to associate with the
    # abstract instruction variables

    # we will also add the libroutine to our dictionary, to conveniently call it later
    libroutines[lr_name] = libroutine


# first we group all the calls into one group
call_collection = [CallInstruction(lr) for lr in libroutines.values()]


libroutine_commutate = my_library.libroutine_from_instructions(
    "commutate",
    *call_collection,
    builder=my_builder,
    daa_assignments=daa_assignments,
    # lrv_assignments=lrv_assignments,
    container_class=F90RoutineContainer,
)


import subprocess
import sys


# my_library.build()

pauli_library_comm = None

RECOMPILE = True

try:
    if not RECOMPILE:
        print("attempt to import... ")
        from ecplib import pauli_library_comm

except ImportError as exc:
    print("import failed, probably not compiled yet.")

if not pauli_library_comm:
    try:
        print("attempt to compile...")

        ret = subprocess.run(
            "/home/matthias/VENV/DEFAULT/bin/f2py -m ecplib -c pauli_library_comm.f90 --f90flags='-ffree-line-length-none'",
            shell=True,
            # stderr=subprocess.DEVNULL,
            # stdout=subprocess.DEVNULL,
        )
        if ret.returncode != 0:
            raise RuntimeError(
                f"f2py failed compilation with exit code {ret.returncode}"
            )
        else:
            print("compilation finished")

    except RuntimeError as exc:
        print("something went wrong during the compilation:")
        print(exc)
        print("try to compile manually via")
        print(
            "  f2py -m ecplib -c pauli_library_comm.f90 --f90flags='-ffree-line-length-none'"
        )
        sys.exit(1)

    # let's try the import again.
    try:
        print("attempt to import (again)... ")
        from ecplib import pauli_library_comm

    except ImportError as exc:
        print("import failed again Try to compile manually via")
        print(
            "  f2py -m ecplib -c pauli_library_comm.f90 --f90flags='-ffree-line-length-none'"
        )
        print("and try running it again.")
        sys.exit(1)

assert pauli_library_comm is not None

import numpy as np
from matplotlib import pyplot as plt

size_ham = len(hamilton_keymap)
size_rho = len(system_keymap)

# rho_real = np.zeros(size_rho)
# rho_imag = np.zeros(size_rho)
# drh_real = np.zeros(size_rho)
# drh_imag = np.zeros(size_rho)
# res_real = np.zeros(size_rho)
# res_imag = np.zeros(size_rho)

# ham_real = np.zeros(size_ham)
# ham_imag = np.zeros(size_ham)


rho_adaa = System_ADAA()
drh_adaa = System_ADAA()
res_adaa = System_ADAA()
ham_adaa = Hamilton_ADAA()


def comm_wrapper(rho, ham, res=None):
    if res is None:
        res = System_ADAA()
    pauli_library_comm.commutate(
        rho.real,
        rho.imag,
        ham.real,
        ham.imag,
        res.real,
        res.imag,
    )
    return res


from phoenix.fgen.pywrapper_library import PyWrapperLibrary

foo = PyWrapperLibrary(my_library, wrapper_lib=pauli_library_comm)

wrapper = foo.create_wrapper("commutate", daa_assignments=daa_assignments)

print(wrapper(rho=rho_adaa, ham=ham_adaa))

print(help(wrapper))
print(wrapper.__doc__)


ids_z = []


coupl = 0.1
omega = 1.0
dtime = 0.00125

for num_spin_a in range(NUM_SPINS):
    for num_spin_b in range(num_spin_a, NUM_SPINS):
        if num_spin_a == num_spin_b:
            ham_adaa.real[hamilton_keymap.key2off((num_spin_a,), "z")] = (
                6.28 * omega
            )
            ids_z.append(system_keymap.key2off((num_spin_a,), "z"))
        else:
            ham_adaa.real[
                hamilton_keymap.key2off((num_spin_a, num_spin_b), "xx")
            ] = (6.28 * coupl) / (num_spin_a - num_spin_b) ** 3
            ham_adaa.real[
                hamilton_keymap.key2off((num_spin_a, num_spin_b), "yy")
            ] = (6.28 * coupl) / (num_spin_a - num_spin_b) ** 3
            ham_adaa.real[
                hamilton_keymap.key2off((num_spin_a, num_spin_b), "zz")
            ] = (-2 * 6.28 * coupl) / (num_spin_a - num_spin_b) ** 3

rho_adaa.real[ids_z[0]] = 1.0

NUM_STEPS_MAX = 2000
NUM_STEPS_AT_ONCE = 200
EVO_ORDER = 6

result_spin_z = [np.zeros(NUM_STEPS_AT_ONCE) for _ in range(NUM_SPINS)]
summed = np.zeros(NUM_STEPS_AT_ONCE)

plt.ion()

plt.ylim(-0.5, 1.1)
plt.xlim(0, NUM_STEPS_AT_ONCE + 10)

graph_sumd = plt.plot(summed)[0]
graph_data = [plt.plot(result_spin_z[k])[0] for k in range(NUM_SPINS)]

for num_step in range(NUM_STEPS_MAX):
    for num_substep in range(10):
        drh_adaa = rho_adaa.copy()

        for evo_order in range(1, EVO_ORDER + 1):
            res_adaa = wrapper(rho=rho_adaa, ham=ham_adaa)
            drh_adaa = (dtime / evo_order) * res_adaa
            rho_adaa += drh_adaa

    if num_step >= NUM_STEPS_AT_ONCE:
        summed[:-1] = summed[1:]
        summed[-1] = 0
        for spin_id in range(NUM_SPINS):
            result_spin_z[spin_id][:-1] = result_spin_z[spin_id][1:]
            value = rho_adaa.real[ids_z[spin_id]]
            # value = rho_real[ids_z[spin_id]]
            result_spin_z[spin_id][-1] = value
            summed[-1] += value
            graph_data[spin_id].set_ydata(result_spin_z[spin_id])
            graph_data[spin_id].set_xdata(
                range(num_step - NUM_STEPS_AT_ONCE, num_step)
            )
        graph_sumd.set_xdata(range(num_step - NUM_STEPS_AT_ONCE, num_step))
        graph_sumd.set_ydata(summed)
        plt.xlim(num_step - NUM_STEPS_AT_ONCE, num_step + 10)

    else:
        for spin_id in range(NUM_SPINS):
            value = rho_adaa.real[ids_z[spin_id]]
            # value = rho_real[ids_z[spin_id]]
            result_spin_z[spin_id][num_step] = value
            summed[num_step] += value
            graph_data[spin_id].set_ydata(result_spin_z[spin_id])
        graph_sumd.set_ydata(summed)

    plt.pause(0.0001)
plt.show()
