"""
#autogenerated#header#do#not#modify############################################
#
# File:        operator2.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   08/11/2024
# Last Update: 12/11/2024, 18:22
# Version:     0.0.739
#
#################################################end#of#autoheader#do#not#modify


Basis is a class to create actual Basis elements.
However, their instances could have a __call__ routine to create subops from
creation parameters
"""

from typing import Self, Any
import math
import cmath

PI = 3.141592653589793
TWOPI = 2 * PI
HALFPI = PI / 2


def _reduce_fraction(nom: int, den: int | None):
    if den is None:
        return (nom, None)
    if den < 0:
        den = -den
        nom = -nom
    gcd = math.gcd(nom, den)
    return nom // gcd, den // gcd


class Coeff:
    """The coefficient base class.

    This class is not supposed to be instantiated
    """

    _ZTOL = 1e-12

    def mul_queue(self, *vals, **_kwargs) -> Self:
        """append the value to the scalar queue to be multiplied"""
        raise NotImplementedError(
            "operation 'mul_queue' must be implemented by the subclass"
        )

    def div_queue(self, *vals, **_kwargs) -> Self:
        """append the value to the scalar queue to be divided"""
        raise NotImplementedError(
            "operation 'div_queue' must be implemented by the subclass"
        )

    def jshift(self, num: int, /) -> Self:
        """apply num multiplications with 1j"""
        raise NotImplementedError(
            "operation 'imshift' must be implemented by the subclass"
        )


def _dismantle_python_intrinsic(number):
    if isinstance(number, int):
        return {"rnom": number}
    elif isinstance(number, float):
        return {"real": number, "imag": None}
    elif isinstance(number, complex):
        return {"real": number.real, "imag": number.imag}


def autoconvert(func):
    def wrapper(self, first=None, /, **kwargs):
        if first is not None:
            if isinstance(first, Scalar):
                return func(self, **first.unpack())
            else:
                num = complex(first)
                return func(self, real=num.real, imag=num.imag, **kwargs)
        else:
            return func(self, **kwargs)

    return wrapper


class Scalar(Coeff):
    r"""
    A general scalar type as subtype of a coefficient.

    This class represents a universal scalar without any restrictions,
    including symbolic support.
    Internally it expresses any complex expression as

                                j phas  / rnom   inom   \     jpow
    z = (real + imag j) x magn e      x | ---- + ---- j | x  j
                                        \ rden   iden   /

    where ints are always strictly accumulated in fractions while
    real/imag or magn/phas can both accumulate irrational contributions.
    Ideally, global signs and multiples of pi/2 can be accumulated in jpow
    to speed up phase swaps of multiples of 90°.
    """

    @autoconvert
    def __init__(
        self,
        real: float = 0.0,
        imag: float = 0.0,
        rnom: int = 1,
        rden: int | None = None,
        inom: int = 0,
        iden: int | None = None,
        magn: float = 1.0,
        phas: float = 0.0,
        jpow: int = 0,
        nega: bool = False,
        symb: list[tuple[str, int | float]] | None = None,
        polar=True,
    ):
        self._nega = nega
        self._real = real
        self._imag = imag
        self._rnom = rnom
        self._rden = rden
        self._inom = inom
        self._iden = iden
        self._magn = magn
        self._phas = phas
        self._jpow = jpow
        self._ppol = polar  # polar priority

        # contract symbols
        symb_dict: dict[str, int | float] = {}
        if symb:
            for symbol, exponent in symb:
                if symbol not in symb_dict:
                    symb_dict[symbol] = 0
                symb_dict[symbol] += exponent
        self._symb = symb_dict
        self.simplify()

    def simplify(
        self, floats=True, polar=True, symbol=True, fracs=True
    ) -> Self:
        """reduces fractions and handles phase"""
        if floats:
            self._floats_simplify()
        if polar:
            self._polar_simplify()
        if fracs:
            self._fracs_simplify()
        if symbol:
            self._symbol_simplify()
        self._phase_collect()
        self._rearrange()
        return self

    def _floats_simplify(self) -> Self:
        """simplify the floats part"""
        if self._real < 0:
            self._real = -self._real
            self._imag = -self._imag
            self._nega = not self._nega
        return self

    def _polar_simplify(self) -> Self:
        """simplify the polar part"""
        if self._magn < 0:
            self._magn = -self._magn
            self._nega = not self._nega
        return self

    def _fracs_simplify(self) -> Self:
        """reduce fractions"""
        if self._rden is not None:
            self._rnom, self._rden = _reduce_fraction(self._rnom, self._rden)
        if self._iden is not None:
            self._inom, self._iden = _reduce_fraction(self._inom, self._iden)
        if self._rnom < 0:
            self._rnom = -self._rnom
            self._inom = -self._inom
            self._nega = not self._nega
        return self

    def _symbol_simplify(self) -> Self:
        """simplify the symbol part"""
        return self

    def _phase_collect(self) -> Self:
        """redistribute phase information"""
        # make leading real part positive
        if self._real < 0:
            self._real *= -1
            self._imag *= -1
            self._nega = not self._nega
        if self._nega:
            self._jpow += 2
            self._nega = False
        self._jpow %= 4
        if self.polar:
            self._phas += self._jpow * HALFPI
            self._jpow = 0
        else:
            self._phas

        # mod 2pi
        self._phas %= TWOPI
        # exclude extra minus signs
        return self

    def _rearrange(self) -> Self:
        """rearrange the decimal contributions between polar and non polar"""
        return self

    def conjugate(self):
        """return a new scalar object that is the conjugate"""
        raise NotImplementedError("operation not yet implemented")

    def mul_queue(self, *vals, simplify=True, **_kwargs) -> Self:
        """append the value to the scalar queue to be multiplied"""
        for val in vals:
            if isinstance(val, int):
                if self._rden is not None:
                    self._rnom *= val
                if self._iden is not None:
                    self._inom *= val
            elif isinstance(val, float):
                if self.polar:
                    self._magn *= val
                else:
                    self._real *= val
                    self._imag *= val
            elif isinstance(val, complex):
                if self.polar:
                    self._magn *= abs(val)
                    self._phas += cmath.phase(val)
                else:
                    new_real = val.real * self._real - val.imag * self._imag
                    new_imag = val.imag * self._real + val.real * self._imag
                    self._real = new_real
                    self._imag = new_imag
            else:
                raise ValueError(f"Unsupported type: {type(val)}")
        if simplify:
            self.simplify()
        return self

    def div_queue(self, *vals, simplify=True, **_kwargs) -> Self:
        """append the value to the scalar queue to be divided"""
        for val in vals:
            if isinstance(val, int):
                if self._rden is None:
                    self._rden = val
                else:
                    self._rden *= val
                if self._iden is None:
                    self._iden = val
                else:
                    self._iden *= val
            elif isinstance(val, float):
                if self.polar:
                    self._magn /= val
                else:
                    self._real /= val
                    self._imag /= val
            elif isinstance(val, complex):
                if self.polar:
                    self._magn /= abs(val)
                    self._phas -= cmath.phase(val)
                else:
                    new_complex = (self._real + 1j * self._imag) / val
                    self._real = new_complex.real
                    self._imag = new_complex.imag
            else:
                raise ValueError(f"Unsupported type: {type(val)}")
        if simplify:
            self.simplify()
        return self

    def jshift(self, num: int, /, *, simplify=True) -> Self:
        """apply num multiplications with 1j"""
        if not isinstance(num, int):
            raise ValueError("jshift requires an integer argument")
        self._jpow += num
        if simplify:
            self.simplify()
        return self

    def flip_sign(self, num: int = 1) -> Self:
        """applies the negation num times, num defaults to 1"""
        if num & 1:
            self._nega = not self._nega
        return self

    @classmethod
    def identity(cls):
        """create a perfect one or its equivalent"""
        return cls(1)

    @classmethod
    def zero(cls):
        """create a perfect zero or its equivalent"""
        return cls(0)

    @property
    def polar(self):
        """get the polar priority of the variable"""
        return self._ppol

    @polar.setter
    def polar(self, value):
        """set if priority is polar"""
        if not isinstance(value, bool):
            raise ValueError("polar priority must be a boolean")
        self._ppol = value
        self._rearrange()

    def to_polar(self):
        """check if the scalar is polar"""
        raise NotImplementedError("yet to be implemented")

    def to_components(self):
        """check if the scalar is composed from real and imag"""
        raise NotImplementedError("yet to be implemented")

    def unpack(self):
        """unpack the generating values for the scalar"""
        return {
            "nega": self._nega,
            "real": self._real,
            "imag": self._imag,
            "rnom": self._rnom,
            "rden": self._rden,
            "inom": self._inom,
            "iden": self._iden,
            "magn": self._magn,
            "phas": self._phas,
            "jpow": self._jpow,
            "symb": self._symb,
        }

    # binary special
    # --------------

    def __mul__(self, other):
        raise NotImplementedError("operation '__mul__' not implemented")

    def __div__(self, other):
        raise NotImplementedError("operation '__div__' not implemented")

    def __truediv__(self, other):
        raise NotImplementedError("operation '__truediv__' not implemented")

    def __add__(self, other):
        raise NotImplementedError("operation '__add__' not implemented")

    def __sub__(self, other):
        raise NotImplementedError("operation '__sub__' not implemented")

    def __pow__(self, exponent):
        raise NotImplementedError("operation '__pow__' not implemented")

    # right side binary special
    # -------------------------

    # the __rx__ routines are called if the left operator has not routine x
    def __rmul__(self, other):
        raise NotImplementedError("operation '__rmul__' not implemented")

    def __rdiv__(self, other):
        raise NotImplementedError("operation '__rdiv__' not implemented")

    def __rtruediv__(self, other):
        raise NotImplementedError("operation '__rtruediv__' not implemented")

    def __radd__(self, other):
        raise NotImplementedError("operation '__radd__' not implemented")

    def __rsub__(self, other):
        raise NotImplementedError("operation '__rsub__' not implemented")

    def __rpow__(self, exponent):
        raise NotImplementedError("operation '__rpow__' not implemented")

    # non-binary special routines
    # ---------------------------

    def __neg__(self):
        raise NotImplementedError("operation '__neg__' not implemented")

    def __abs__(self):
        raise NotImplementedError("operation '__abs__' not implemented")

    # type casts
    # ----------

    def __int__(self):
        if abs(self.imag) > Scalar._ZTOL:
            raise ValueError("Scalar is not a real number")
        return int(self.real)

    def __float__(self):
        if abs(self.imag) > Scalar._ZTOL:
            raise ValueError("Scalar is not a real number")
        return self.real

    def __complex__(self):
        return self.real + 1j * self.imag

    # component access
    # ----------------

    @property
    def real(self):
        """
        interpret as a complex number and return the real part of that number.
        """
        raise NotImplementedError("Cannot access 'real' property")

    @property
    def imag(self):
        """
        interpret as a complex number and return the imaginary part of that
        number.
        """
        raise NotImplementedError("Cannot access 'imag' property")

    @property
    def magn(self):
        """
        interpret as a complex number and return the magnitude of the polar
        representation of that number.
        """
        raise NotImplementedError("Cannot access 'magn' property")

    @property
    def phase(self):
        """
        interpret as a complex number and return the phase of the polar
        representation of that number.
        """
        raise NotImplementedError("Cannot access 'phas' property")


'''

    include this to consider subtypes
    =================================

    # scalar type casts
    # -----------------

    def to_python(self):
        """return as an unwrapped python scalar"""
        raise NotImplementedError("operation 'to_python' not implemented")

    def to_universal(self):
        """return as an unwrapped python scalar"""
        raise NotImplementedError("operation 'to_universal' not implemented")

    def to_pcomplex(self):
        """translate into a polar representation"""
        return ScalarPComplex().from_universal(self.to_universal())

    def to_ccomplex(self):
        """translate into a component complex representation"""
        return ScalarCComplex().from_universal(self.to_universal())

    def to_pyscalar(self):
        """translate into a python scalar"""
        return ScalarPython().from_universal(self.to_universal())

    def to_cfraction(self):
        """translate into a python fraction"""
        return ScalarCFraction().from_universal(self.to_universal())

    def to_rfraction(self):
        """translate into a python fraction"""
        return ScalarRFraction().from_universal(self.to_universal())

    def to_symbolic(self):
        """translate into a symbolic"""
        return ScalarSymbolic().from_universal(self.to_universal())

    def from_python(self, value):
        """return as an unwrapped python scalar"""
        raise NotImplementedError("operation 'from_python' not implemented")

    def from_universal(self, value):
        """return as an unwrapped python scalar"""
        raise NotImplementedError("operation 'from_python' not implemented")

    def from_pcomplex(self, pcomplex) -> Self:
        """overwrite (!) content from a polar representation"""
        return self.from_universal(pcomplex.to_universal())

    def from_ccomplex(self, ccomplex) -> Self:
        """overwrite (!) content from a component complex representation"""
        return self.from_universal(ccomplex.to_universal())

    def from_pyscalar(self, pyscalar) -> Self:
        """overwrite (!) content from a python scalar"""
        return self.from_universal(pyscalar.to_universal())

    def from_cfraction(self, cfraction) -> Self:
        """overwrite (!) content from a python fraction"""
        return self.from_universal(cfraction.to_universal())

    def from_rfraction(self, rfraction) -> Self:
        """overwrite (!) content from a python fraction"""
        return self.from_universal(rfraction.to_universal())

    def from_symbolic(self, symbolic, **substitutes):
        """apply substitutes and create from symbolic"""
        return self.from_universal(
            symbolic.substitute(
                **substitutes, check_numeric=True
            ).to_universal()
        )

    # auto cast
    # ---------

    def autoconvert(self, sometype) -> Self:
        """automatically convert from input. Also supports python intrinsics"""
        if isinstance(sometype, Scalar):
            return self.from_scalar(sometype)
        return self.from_python(sometype)

    def from_scalar(self, scalar) -> Self:
        match type(scalar):
            case scalar_namespace.PythonScalar:
                return self.from_pyscalar(scalar)
            case scalar_namespace.ScalarCComplex:
                return self.from_ccomplex(scalar)
            case scalar_namespace.ScalarPComplex:
                return self.from_pcomplex(scalar)
            case scalar_namespace.ScalarRFraction:
                return self.from_rfraction(scalar)
            case scalar_namespace.ScalarCFraction:
                return self.from_cfraction(scalar)
            case _:
                raise TypeError(f"Unsupported scalar type: {type(scalar)}")

    # SUBTYPES
    # ========



class ScalarPython(Scalar):
    """Default scalar, designed to wrap python scalars"""

    def __init__(self, value=0, **kwargs):
        """only take one value"""
        super().__init__(value, polar=False, **kwargs)


class ScalarCComplex(Scalar):
    """
    ScalarCComplex represents a complex value.

    In contrast to the python scalar wrapper, it distinguishes real and imag
    part explicitely as components.
    """

    def __init__(self, real=0.0, imag=0.0, **kwargs):
        super().__init__(real, imag, **kwargs)

    @property
    def real(self):
        """acccess the real part"""
        return self._vals[0]

    @real.setter
    def real(self, value):
        """set the value of alias 'real'"""
        self._vals = (value, self._vals[1])

    @property
    def imag(self):
        """acccess the real part"""
        return self._vals[1]

    @imag.setter
    def imag(self, value):
        """set the value of alias 'imag'"""
        self._vals = (self._vals[0], value)


class ScalarPComplex(Scalar):
    """
    ScalarPComplex represents a complex value in polar form via a magnitude
    and a phase.
    """

    def __init__(self, magn=0.0, phase=0.0, **kwargs):
        super().__init__(magn, phase, **kwargs)

    @property
    def magnitude(self):
        """acccess the magnitude part"""
        return self._vals[0]

    @magnitude.setter
    def magnitude(self, value):
        """set the value of alias 'magnitude'"""
        self._vals = (value, self._vals[1])

    @property
    def phase(self):
        """acccess the phase part"""
        return self._vals[1]

    @phase.setter
    def phase(self, value):
        """set the value of alias 'phase'"""
        self._vals = (self._vals[0], value)

    def __abs__(self):
        return self.magnitude


class ScalarRFraction(Scalar):
    """
    A fraction of real (!) ints.

    dnom is always >= 1.
    """

    def __init__(
        self,
        nom: int = 1,
        den: int = 1,
        **kwargs,
    ):
        super().__init__(nom, den, **kwargs)


class ScalarCFraction(Scalar):
    """
    A complex fraction of ints.

    Real and imag part can have their own denominator to have proper nominator
    values when real/imag >> 1 or imag/real >> 1.
    """

    def __init__(
        self,
        rnom: int = 1,
        rden: int = 1,
        inom: int = 0,
        iden: int = 1,
        **kwargs,
    ):
        super().__init__(rnom, rden, inom, iden, **kwargs)


class ScalarSymbolic(Scalar):
    """A symbolic variable, represented by a letter and its power"""

    def __init__(self, *scals, **powers):
        # assume the scals are of some compatible input type.
        super().__init__()
        self._powers = {}
        for varname, power in powers.items():
            self._powers[varname] = power


# the namespace makes classes available that are not yet defined
# scalar_namespace.ScalarCComplex = ScalarCComplex
# scalar_namespace.ScalarPComplex = ScalarPComplex
# scalar_namespace.ScalarRFraction = ScalarRFraction
# scalar_namespace.ScalarCFraction = ScalarCFraction
# scalar_namespace.PythonScalar = ScalarPython

'''


class Summand:
    """
    Summand class
    """

    _DEFAULT_COEFF = Scalar  # default class to create scalars from

    def __init__(self, bases, elems, scalar=None):
        self._elems = elems
        self._bases = bases
        if scalar is None:
            scalar = self._DEFAULT_COEFF.identity()
        elif not isinstance(scalar, Coeff):
            scalar = self._DEFAULT_COEFF(scalar)
        self.scalar = scalar


class Operator:
    """
    Operator class
    """

    _DEFAULT_SUMMAND = Summand  # default class to create summands from


class Basis:
    def __init__(self):
        pass

    def op(self, *vals):
        return Summand(
            (self,),
            (vals,),
        )


class SymbolBasis(Basis):
    """A counting basis counts e.g. the power of a symbol"""


class PauliBasis(Basis):
    """A basis for pauli strings"""


class PauliString(Basis):
    """A pauli string that always refers to a fixed length"""


class MatrixBasis(Basis):
    """
    A basis that generates matrices as operators. Note that
    matrices can be added and scale more directly with the scalars.
    """


if __name__ == "__main__":
    a = Scalar(1)
    print(a._real)
    print(a._imag)

    b = Scalar(a)
    print(b._real)
    print(b._imag)
