"""
#autogenerated#header#do#not#modify############################################
#
# File:        scalar.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   14/11/2024
# Last Update: 14/11/2024, 19:39
# Version:     0.0.463
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations
from typing import Self


ZEROTOL = 1e-13


def try_int(val, conv=True):
    """attempt to convert floats to ints that are very close to an int value"""
    if conv:
        if val > 0:
            if abs(val - (val_int := int(val + ZEROTOL))) < ZEROTOL:
                return int(val_int + ZEROTOL)
        else:
            if abs(val - (val_int := int(val - ZEROTOL))) < ZEROTOL:
                return int(val_int - ZEROTOL)
    return val


def autoconvert(func):
    """
    Convert the args of a two-input function into instances of cls
    """

    def wrapper(cls, first, second=None):
        if not isinstance(first, cls):
            first = cls(first)
        if second is not None:
            if not isinstance(second, cls):
                second = cls(second)
            return func(cls, first, second)
        return func(cls, first)

    return wrapper


class _Scalar:
    """Scalar parent class to make sure all that is needed is defined"""

    def __init__(self, *_args, **_kwargs):
        pass

    def copy(self) -> _Scalar:
        """return a copy of the current scalar"""
        raise NotImplementedError(
            "'to_python_scalar' must be defined by subclass."
        )

    def to_python_scalar(self) -> int | float | complex:
        """generate a python scalar from the object"""
        raise NotImplementedError(
            "'to_python_scalar' must be defined by subclass."
        )

    def to_complex_components(self) -> tuple[float, float]:
        """split into complex components"""
        c_rep = complex(self.to_python_scalar())
        return c_rep.real, c_rep.imag

    def to_str(self, conv_int=True):
        """
        Default string conversion.
        The conv_int flag decides whether floats that are closer to int values
        than ZEROTOL should be converted into actual integer.
        """
        val = self.value
        if isinstance(val, complex):
            real = try_int(val.real, conv=conv_int)
            imag = try_int(val.imag, conv=conv_int)
            if abs(val.real) < ZEROTOL:
                if abs(imag) < ZEROTOL:
                    return "0"
                return f"{imag}j"
            # |real| > 0:
            if abs(val.imag) < ZEROTOL:
                return f"{real}"
            return f"({real} + {imag}j)"
        return str(try_int(val, conv=conv_int))

    # class handler for arithmetics
    # -----------------------------

    @classmethod
    @autoconvert
    def _add(cls, first, second) -> _Scalar:
        return cls(first.to_python_scalar() + second.to_python_scalar())

    @classmethod
    @autoconvert
    def _sub(cls, first, second) -> _Scalar:
        return cls(first.to_python_scalar() - second.to_python_scalar())

    @classmethod
    @autoconvert
    def _mul(cls, first, second) -> _Scalar:
        return cls(first.to_python_scalar() * second.to_python_scalar())

    @classmethod
    @autoconvert
    def _div(cls, first, second) -> _Scalar:
        return cls(first.to_python_scalar() / second.to_python_scalar())

    @classmethod
    @autoconvert
    def _pow(cls, first, second) -> _Scalar:
        return cls(first.to_python_scalar() ** second.to_python_scalar())

    @classmethod
    @autoconvert
    def _abs(cls, scal) -> float:
        return abs(scal.to_python_scalar())

    # forward dunder methods into class handlers
    # ------------------------------------------

    def __add__(self, other):
        return self.__class__._add(self, other)

    def __radd__(self, other):
        return self.__class__._add(other, self)

    def __sub__(self, other):
        return self.__class__._sub(self, other)

    def __rsub__(self, other):
        return self.__class__._sub(other, self)

    def __mul__(self, other):
        return self.__class__._mul(self, other)

    def __rmul__(self, other):
        return self.__class__._mul(other, self)

    def __truediv__(self, other):
        return self.__class__._div(self, other)

    def __rtruediv__(self, other):
        return self.__class__._div(other, self)

    def __pow__(self, other):
        return self.__class__._pow(self, other)

    def __rpow__(self, other):
        return self.__class__._pow(other, self)

    def __abs__(self):
        return self.__class__._abs(self)

    def __str__(self):
        return f"S[{self.to_str()}]"

    def __repr__(self):
        return self.to_str()

    @classmethod
    def one(cls):
        """a scalar one"""
        return cls(1)

    @classmethod
    def zero(cls):
        """a scalar zero"""
        return cls(0)

    @classmethod
    def from_product(cls, *values):
        """generate from a product"""
        ret = cls.one()
        for val in values:
            if isinstance(val, _Scalar):
                ret *= val
            else:
                ret *= cls(val)
        return ret

    @property
    def value(self):
        """value property"""
        return self.to_python_scalar()

    @property
    def real(self):
        """value property"""
        real, _ = self.to_complex_components()
        return real

    @property
    def imag(self):
        """value property"""
        _, imag = self.to_complex_components()
        return imag


class ScalarWrapper(_Scalar):
    """Simple wrapper around the python scalar types"""

    _IDENTIFIER = "PYWRAPPER"

    def __init__(self, value, /):
        super().__init__()
        if isinstance(value, _Scalar):
            value = value.to_python_scalar()
        self._val = value

    def to_python_scalar(self):
        """generate a python scalar from the value"""
        assert not isinstance(self._val, _Scalar)
        return self._val

    def copy(self) -> _Scalar:
        return self.__class__(self.value)


class Scalar(ScalarWrapper):
    """redefines the scalar default class. This just inherits from anything that
    is currently the scalar of choice, but will expand later to multi scalar
    implementation to cover symbolics, fractions and more."""


if __name__ == "__main__":
    a = Scalar(2)
    b = Scalar(4)
    print((a * b + 2).real)
    print(3 + Scalar(a * b + 2).value)
    print((Scalar.from_product(1, 2, 3, a, (a + b))))
    print(type(Scalar(Scalar(Scalar(2))).value))
    #

    a *= 2.1257981
    print(a)


'''
    DUMP SCALAR WRAPPER

        # def _apply_mul_queue(self) -> Self:
        #     if self._mul_queue:
        #         nom = 1
        #         for val in self._mul_queue:
        #             if isinstance(val, _Scalar):
        #                 nom *= val.value
        #             else:
        #                 nom *= val
        #         self._val *= nom
        #     return self

        # def _apply_div_queue(self) -> Self:
        #     if self._div_queue:
        #         den = 1
        #         for val in self._div_queue:
        #             if isinstance(val, _Scalar):
        #                 den *= val.value
        #             else:
        #                 den *= val
        #         self._val /= den
        #     return self

        # def _apply_cmplx_rot(self) -> Self:
        #     # apply rotation with j
        #     self._cmplx_rot &= 3
        #     if self._cmplx_rot:
        #         self._val *= (1j) ** self._cmplx_rot
        #         self._cmplx_rot = 0
        #         if isinstance(self._val, complex):
        #             if abs(self._val.imag) < ZEROTOL:
        #                 self._val = self._val.real
        #     return self


    DUMP SCALAR

        # def __init__(self, *_args, **_kwargs):
        #     self._flag_eval = False

        # def flag_eval(self):
        #     """flag for reevaluation"""
        #     self._flag_eval = True

        # def enqueue_jpow(self, num=1, /) -> Self:
        #     """apply a multiplication with j or a power of it"""
        #     self._cmplx_rot += num
        #     self.flag_eval()
        #     return self

        # def enqueue_mul(self, value, /) -> Self:
        #     """enqueue a value for multiplication"""
        #     self._mul_queue.append(value)
        #     self.flag_eval()
        #     return self

        # def enqueue_div(self, value, /) -> Self:
        #     """enqueue a value for division"""
        #     self._div_queue.append(value)
        #     self.flag_eval()
        #     return self

        # def eval(self) -> Self:
        #     """apply eval if necessary"""
        #     if self._flag_eval:
        #         try:
        #             self._eval()
        #             self._flag_eval = False
        #         except Exception as e:
        #             self._flag_eval = True
        #             raise e
        #     assert not self._flag_eval
        #     return self

        # def _eval(self) -> Self:
        #     self._apply_mul_queue()
        #     self._apply_div_queue()
        #     self._apply_cmplx_rot()
        #     return self

        # def _apply_mul_queue(self) -> Self:
        #     val = self
        #     for mul in self._mul_queue:
        #         val *= mul
        #     self.copy_from(val)
        #     self._mul_queue = []
        #     return self

        # def _apply_div_queue(self) -> Self:
        #     val = self
        #     for div in self._div_queue:
        #         val /= div
        #     self.copy_from(val)
        #     self._div_queue = []
        #     return self

        # def _apply_cmplx_rot(self) -> Self:
        #     # apply rotation with j
        #     val = self * (1j) ** (self._cmplx_rot & 3)
        #     self.copy_from(val)
        #     self._cmplx_rot = 0
        #     return self
    '''
