"""
#autogenerated#header#do#not#modify############################################
#
# File:        summand.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   14/11/2024
# Last Update: 21/11/2024, 13:56
# Version:     0.0.44
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from phoenix.toolbox.qop.scalar import Scalar


class Summand:
    """
    Summand class
    """

    def __init__(self, bases: tuple, comps: tuple, modif=None):
        self._comps = comps
        self._bases = bases
        if modif is None:
            modif = Scalar.identity()
        elif not isinstance(modif, Scalar):
            modif = Scalar(modif)
        self._modif = modif

    @property
    def comps(self):
        """access read-only attribute components"""
        return self._comps

    @property
    def bases(self):
        """access read-only attribute bases"""
        return self._bases

    @property
    def coeff(self):
        """access read-only attribute coefficient/modifier"""
        return self._modif

    @property
    def modifier(self):
        """access read-only attribute modifier"""
        return self._modif

    def copy(self):
        """copy a summand"""
        return Summand(self._bases, self._comps, self._modif)
