"""
#autogenerated#header#do#not#modify############################################
#
# File:        _aux.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   09/10/2024
# Last Update: 04/02/2025, 18:17
# Version:     0.0.7
#
#################################################end#of#autoheader#do#not#modify


"""


def all_same(somelist):
    """checks if all elements in a list are the same, returns that element if
    true and raises exception when not.
    """
    if not somelist:
        raise ValueError("List is empty")
    first = somelist[0]
    assert first
    for other in somelist[1:]:
        if not first == other:
            raise ValueError("Not all elements are the same")
    return first


def segment_overlap(*segments_list):
    """get the list of overlapping entries in all lists.
    Used in instruction.py to identify the common instruction type when
    merging many of them
    """
    common_segments = []
    for segments in zip(*segments_list):
        try:
            common = all_same(segments)
        except ValueError:
            break
        common_segments.append(common)
    return common_segments


# def mro_latest_common_parent(*class_list):
#     """class based approach to find the common class in a list.
#     Used as alternative to find a common parent in a set of instructions that
#     are to be merged into a list"""
#     latest = None
#     for this_classes in zip(*class_list):
#         try:
#             latest = all_same(this_classes)
#         except ValueError:
#             break
#     return latest
