"""
#autogenerated#header#do#not#modify############################################
#
# File:        adaa_derived.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   24/10/2024
# Last Update: 24/10/2024, 15:35
# Version:     0.0.20
#
#################################################end#of#autoheader#do#not#modify


"""

from phoenix.adaa import ADAA
from phoenix.coeffbackend_derived import RawPyCoeffBackend
from phoenix.coeffbackend_derived import NumPyCoeffBackend
from phoenix.coeffbackend_derived import FortranCoeffBackend
from phoenix.coeffbackend_derived import CuPyCoeffBackend
from phoenix.coeffbackend_derived import OpenClCoeffBackend


class RawPyADAA(ADAA, backend=RawPyCoeffBackend(), identifier="RAWPYTHON"):
    """Raw Python data layer"""


class NumPyADAA(ADAA, backend=NumPyCoeffBackend(), identifier="NUMPY"):
    """NumPy based data layer"""


class FortranADAA(ADAA, backend=FortranCoeffBackend(), identifier="FORTRAN"):
    """FORTRAN based data layer (implemented via NumPy)"""


class CupyADAA(ADAA, backend=CuPyCoeffBackend(), identifier="CUPY"):
    """CuPy based data layer"""


class OpenClADAA(ADAA, backend=OpenClCoeffBackend(), identifier="OPENCL"):
    """OpenCL based data layer"""
