"""
#autogenerated#header#do#not#modify############################################
#
# File:        adaa_derived.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   24/10/2024
# Last Update: 13/08/2025, 13:03
# Version:     0.0.77
#
#################################################end#of#autoheader#do#not#modify


"""

from phoenix.adaa import ComplexArrayADAA
from phoenix.coeffbackend_derived import RawPyCoeffBackend
from phoenix.coeffbackend_derived import NumPyCoeffBackend
from phoenix.coeffbackend_derived import FortranCoeffBackend
from phoenix.coeffbackend_derived import CuPyCoeffBackend
from phoenix.coeffbackend_derived import OpenClCoeffBackend
from phoenix.coeffbackend_derived import PyCudaCoeffBackend


# CA for complex array


class RawPyCA(
    ComplexArrayADAA, backend=RawPyCoeffBackend(), identifier="RAWPYTHON"
):
    """Raw Python data layer"""


class NumPyCA(
    ComplexArrayADAA, backend=NumPyCoeffBackend(), identifier="NUMPY"
):
    """NumPy based data layer"""


class FortranCA(
    ComplexArrayADAA, backend=FortranCoeffBackend(), identifier="FORTRAN"
):
    """FORTRAN based data layer (implemented via NumPy)"""


class CupyCA(ComplexArrayADAA, backend=CuPyCoeffBackend(), identifier="CUPY"):
    """CuPy based data layer"""


class OpenClCA(
    ComplexArrayADAA, backend=OpenClCoeffBackend(), identifier="OPENCL"
):
    """OpenCL based data layer"""


class PyCudaCA(
    ComplexArrayADAA, backend=PyCudaCoeffBackend(), identifier="PYCUDA"
):
    """OpenCL based data layer"""


if __name__ == "__main__":
    for Array in [
        RawPyCA,
        NumPyCA,
        FortranCA,
        CupyCA,
        # OpenClCA,
        # PyCudaCA,
    ]:
        print("----------------------------------------------------")
        print(Array._IDENTIFIER)

        print("before fix_size")

        print("Array", Array)
        print("Array(12).real", Array(12, init_zeros=False).real)

        MyType = Array.fix_size(2)
        print("after fix_size")
        a = MyType(init_zeros=False)
        print(a.data)
        print(a.real, type)
        print(a.identifier)
        print(list(a.unpack()))
