"""
#autogenerated#header#do#not#modify############################################
#
# File:        dcontainer.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   24/10/2024
# Last Update: 24/10/2024, 15:28
# Version:     0.0.6
#
#################################################end#of#autoheader#do#not#modify


"""

from phoenix.adaa import ADAA


class DContainer:
    """DContainer class description"""

    _LAYERS: dict[str, ADAA] = {}

    def __init__(self, *sizes):
        if len(sizes) != len(self._LAYERS):
            raise ValueError("Sizes must match the number of layers")
        self._layers = {
            key: layer(size)
            for (key, layer), size in zip(self._LAYERS.items(), sizes)
        }

    def __init_subclass__(cls, **layers):
        cls._LAYERS = layers
        return cls

    def __getitem__(self, key: int | str):
        if isinstance(key, str):
            if key not in self._layers:
                raise KeyError(f"Layer '{key}' not found")
            return self._layers[key]
        elif isinstance(key, int):
            return self._layers[list(self._LAYERS.keys())[key]]
        else:
            raise TypeError("Key must be an integer or a string")

    def unpack(self, key, **kwargs):
        """unpack the requested layer"""
        assert key in self._layers
        return self._layers[key].unpack(**kwargs)

    def unpack_multi(self, keys, **kwargs):
        """unpack the requested layer"""
        for key in keys:
            assert key in self._layers
        return [self._layers[key].unpack(**kwargs) for key in keys]


class DLC(DContainer):
    """Dual Layer Container class. Implements host-device interaction"""


class SDLC(DLC):
    """Synced Dual Layer Container class"""


# class Foo(
#     DContainer,
#     layer1=PurePyADAA,
#     layer2=NumpyADAA,
#     layer3=OpenClADAA,
#     layer4=CupyADAA,
#     layer5=FortranADAA,
# ):
#     pass
