"""
#autogenerated#header#do#not#modify############################################
#
# File:        dtype.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 21/08/2024, 17:28
# Version:     0.0.1
#
#################################################end#of#autoheader#do#not#modify


"""


class DLayer:
    """DLayer class description"""


class DContainer:
    """DContainer class description"""


class DLC(DContainer):
    """Dual Layer Container class description"""


class SDLC(DLC):
    """Synced Dual Layer Container class description"""
