"""
#autogenerated#header#do#not#modify############################################
#
# File:        dtype.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 14/10/2024, 13:47
# Version:     0.0.1558
#
#################################################end#of#autoheader#do#not#modify



TODO:
=====

[X]:  from_numpy, to_numpy/as_numpy: these methods shortcut the data transfer
        between host and potential device without using a container object.
        This strategy does not require any host/local data representation in the
        datatype, does not require syncing and is cheap to implement.
[ ]:  auto-implement pure, gpu and cpu data type. Have a lib variable set upon
        initialisation to read the availability of cupy, pycuda, opencl, ...
        and have an automated choice for the data type if "GPU", "CPU" or
        "PURE" is  passed as an initializer. Check how ADAA is best implemented
        to have a choice of hardware
"""

from __future__ import annotations

__doc__ = """

The ADAA class holds data references to HPC backends and unpacks accordingly
for function calls.

Basic arithemtic operations are implemented via a mapping into a basic
linop(A, b, C) -> A + b * C operation

DContainer combines multiple Layers to a combined datatype and can be extended
to manage inter-layer data conversion, host-device sync and consistency checks.

So far, no arithmetic operation is implemented on this level, intentionally,
as, depending on the interpretation of levels, such an implementation might be
factually wrong.

"""

# pylint: disable=too-many-arguments

from typing import Any
from abc import ABCMeta, abstractmethod

import warnings
import numpy as np


ZERO_TOL = 1e-14


class CoeffBackend(metaclass=ABCMeta):
    """
    The coefficient based backend.

    This routine collection is implemented as a class, because for specific
    backend implementations, auxilliary variables, special libraries or
    initialization might be required.
    """

    def __init__(self, *args, **kwargs):
        pass

    def coeff_add(self, op_r, op_a, op_b, size: int, dtype: str = "f64"):
        """Adds operands op_a and op_b, write result to op_r."""
        return self.coeff_linop(
            op_r, 1.0, op_a, 1.0, op_b, size=size, dtype=dtype
        )

    def coeff_smul(self, op_r, op_a, scal, size: int, dtype: str = "f64"):
        """Scalar-multiply op_a with scal, write result to op_r."""
        return self.coeff_linop(
            op_r, scal, op_a, None, None, size=size, dtype=dtype
        )

    def coeff_safe_access(self, reference, size: int, dtype: str = "f64"):
        """
        Provide safe access to coeff array by generating a copy or guarantee
        read-only access privileges.
        """
        targ = self.coeff_new_array(size=size, dtype=dtype)
        return self.coeff_copy(targ, reference, size=size, dtype=dtype)

    def coeff_to_zero(self, reference, size: int, dtype: str = "f64"):
        """Set the passed coefficient vector to zero."""
        if size is None:
            size = len(reference)
        self.coeff_smul(reference, reference, 0.0, size=size, dtype=dtype)

    def coeff_copy(self, targ, source, size: int, dtype: str = "f64"):
        """Copy the data from source to targ."""
        self.coeff_smul(targ, source, 1.0, size=size, dtype=dtype)

    def coeff_free(self, reference, size: int, dtype: str = "f64"):
        """free the memory at ref."""
        return None

    def coeff_allclose(
        self, coeff_a, coeff_b, atol, rtol, size, dtype="f64"
    ) -> bool:
        """
        Perform the all-close-check:
        Check if the values are all sufficiently close by checking, if
        |a - b|² <= atol² + rtol² (|a|² + |b|²) / 4
        is fulfilled for all coefficients."""
        return np.allclose(
            self.coeff_to_numpy(coeff_a, size=size, dtype="f64"),
            self.coeff_to_numpy(coeff_b, size=size, dtype="f64"),
            atol=atol,
            rtol=rtol,
        )

    @abstractmethod
    def coeff_new_array(self, size: int, dtype: str = "f64") -> Any:
        """Create an empty coeff array."""

    @abstractmethod
    def coeff_from_numpy(
        self, targ: Any, array: np.ndarray, size, dtype="f64"
    ) -> None:
        """Fill the coeffs from a numpy array."""

    @abstractmethod
    def coeff_to_numpy(
        self, coeff_array: Any, size, dtype="f64"
    ) -> np.ndarray:
        """Export the coeffs as a numpy array."""

    @abstractmethod
    def coeff_linop(
        self,
        arr_r: Any,
        /,
        scal_a: float,
        arr_x: Any,
        scal_b: float | None = 1,
        arr_y: Any = None,
        *,
        size: int,
        dtype: str = "f64",
    ):
        """
        Performs the basic linear operation
            a * x (+ b * y)
        where and a and b are scalar and x and y are a coeff array.
        """
        # writes the result of scal_a * arr_x (+ scal_b * arr_y if arr_e) into arr_r


class ADAA:
    """
    ADAA is an acronym for Aligned Data Access Array.
    This data type is intended for the systematic distribution of data into
    multiple aligned arrays. An example for this distribution are arrays
    holding the real and imaginary parts of numbers that were originally
    stored in a complex array. The distribution does not require more memory
    but might allow optimizations based on the active distinction between
    e.g. real and imaginary parts.

    The base class implements just this case and comes along with basic
    arithmetic operations.
    """

    _IDENTIFIER = "COMPLEX_ARRAY"
    BACKEND: CoeffBackend

    def __init__(self, size: int):
        self._size = size
        self._data_r = None
        self._data_i = None
        self._reinit(size)

    @property
    def real(self):
        """Access protected attribute real."""
        return self.BACKEND.coeff_safe_access(
            reference=self._data_r, dtype="f64", size=self.size
        )

    @real.setter
    def real(self, arr):
        """Set the data for real part."""
        # self._set_data(real=arr)
        raise ValueError("Real part of the data cannot be set directly.")

    @property
    def imag(self):
        """Access protected attribute imag."""
        return self.BACKEND.coeff_safe_access(
            reference=self._data_i, dtype="f64", size=self.size
        )

    @imag.setter
    def imag(self, arr):
        """Set the data for imag part."""
        # self._set_data(imag=arr)
        raise ValueError("Imag part of the data cannot be set directly.")

    @property
    def ident(self) -> str:
        """access write-protected property 'identifier'"""
        return self._IDENTIFIER

    @property
    def size(self) -> int:
        """Access write-protected property 'size'"""
        return self._size

    def to_zero(self):
        """Set the coefficient data to zero."""
        self.BACKEND.coeff_to_zero(self._data_r, size=self.size, dtype="f64")
        self.BACKEND.coeff_to_zero(self._data_i, size=self.size, dtype="f64")
        return self

    @classmethod
    def from_numpy(cls, arr: np.ndarray) -> ADAA:
        """Import data from numpy array."""
        size = len(arr)
        obj = cls(size)
        cls.BACKEND.coeff_from_numpy(
            obj.real, arr.real, size=size, dtype="f64"
        )
        cls.BACKEND.coeff_from_numpy(
            obj.imag, arr.imag, size=size, dtype="f64"
        )
        return obj

    def to_numpy(self) -> np.ndarray:
        """Export data as numpy array."""
        real_part = self.__class__.BACKEND.coeff_to_numpy(
            self.real, size=self.size, dtype="f64"
        )
        imag_part = self.__class__.BACKEND.coeff_to_numpy(
            self.imag, size=self.size, dtype="f64"
        )
        return real_part + 1j * imag_part

    def unpack(self) -> tuple:
        """Unpack the layer into a tuple to apply it to functions."""
        return (self._data_r, self._data_i, self.size)

    def copy(self) -> ADAA:
        """Creates a real copy of self."""
        copy = self.__class__(self.size)
        self.__class__.BACKEND.coeff_linop(
            copy.real, 1.0, self.real, size=self.size, dtype="f64"
        )
        self.__class__.BACKEND.coeff_linop(
            copy.imag, 1.0, self.imag, size=self.size, dtype="f64"
        )
        return copy

    @classmethod
    def allclose(cls, op_a, op_b, rtol=1e-05, atol=1e-8):
        """
        Check if the values are all sufficiently close by checking, if
        |a - b|² <= atol² + rtol² (|a|² + |b|²) / 4
        is fulfilled for all coefficients.
        """
        if op_a.size != op_b.size:
            raise ValueError("Compared operators must have the same size.")
        real_all_close = cls.BACKEND.coeff_allclose(
            op_a.real, op_b.real, rtol, atol, size=op_a.size, dtype="f64"
        )
        imag_all_close = cls.BACKEND.coeff_allclose(
            op_a.imag, op_b.imag, rtol, atol, size=op_a.size, dtype="f64"
        )
        return real_all_close and imag_all_close

    @classmethod
    def basic_linop(cls, op_r, /, op_a=None, sc_b=None, op_c=None, size=None):
        """returns operator_a + scalar_b * operator_c"""

        assert op_c is not None
        assert op_r is not None

        if size is None:
            size = op_r.size

        if op_a is None:
            zero = cls(size).to_zero()
            oar, oai = zero.real, zero.imag
        else:
            oar = op_a.real
            oai = op_a.imag

        ocr = op_c.real
        oci = op_c.imag

        if sc_b is None:
            sbr, sbi = (1.0, 0.0)
        else:
            sbr, sbi = (complex(sc_b).real, complex(sc_b).real)

        aux_r = cls.BACKEND.coeff_new_array(size, dtype="f64")
        aux_i = cls.BACKEND.coeff_new_array(size, dtype="f64")

        # sbr * ocr - sbi * oci -> aux_r
        cls.BACKEND.coeff_linop(
            aux_r, sbr, ocr, -1 * sbi, oci, size=size, dtype="f64"
        )
        # sbi * ocr + sbr * oci -> aux_i
        cls.BACKEND.coeff_linop(
            aux_i, sbi, ocr, sbr, oci, size=size, dtype="f64"
        )

        # bracket + oar -> op_r.real
        cls.BACKEND.coeff_add(op_r.real, aux_r, oar, size=size, dtype="f64")
        # bracket + oai -> op_r.imag
        cls.BACKEND.coeff_add(op_r.imag, aux_i, oai, size=size, dtype="f64")

    def free_memory(self):
        """free the occupied memory"""
        self._data_r = self.__class__.BACKEND.coeff_free(self._data_r)
        self._data_i = self.__class__.BACKEND.coeff_free(self._data_i)

    def _reinit(self, size=None):
        """Reinitialize the data for a certain size"""
        if size is None:
            size = self.size
        else:
            if size == self.size:
                return
        self.reinit(size)

    def reinit(self, size):
        """Actual reinitialization. Forced."""
        self.free_memory()
        self._size = size
        self._data_r = self.BACKEND.coeff_new_array(size, dtype="f64")
        self._data_i = self.BACKEND.coeff_new_array(size, dtype="f64")

    def __init_subclass__(cls, backend, identifier=None):
        """
        When a new subclass is derived, introduce the class
        variable _IDENTIFIER.
        """
        cls.BACKEND = backend
        if identifier is None:
            ident = cls.__name__
        cls._IDENTIFIER = ident

    def _set_data(self, real=None, imag=None):
        """Set the data."""
        if real is not None:
            self._data_r = real
        if imag is not None:
            self._data_i = imag
        return self

    ###########################################################################
    #
    # MAGIC
    # =====

    def __add__(self, other):
        if isinstance(other, self.__class__):
            assert self.size == other.size
            assert self.ident == other.ident
            result = self.__class__(size=self.size)
            self.basic_linop(result, op_a=self, sc_b=1, op_c=other)
            return result
        raise ValueError(
            "Subtraction between operator and non-operator is not supported"
        )

    def __sub__(self, other):
        if isinstance(other, self.__class__):
            assert self.size == other.size
            assert self.ident == other.ident
            result = self.__class__(size=self.size)
            self.basic_linop(result, op_a=self, sc_b=-1, op_c=other)
            return result
        raise ValueError(
            "Subtraction between operator and non-operator is not supported"
        )

    def __mul__(self, other):
        if isinstance(other, ADAA):
            raise ValueError(
                "Multiplication with other operator is not supported"
            )
        result = self.__class__(size=self.size)
        self.basic_linop(result, op_a=None, sc_b=other, op_c=self)
        return result

    def __truediv__(self, other):
        if isinstance(other, ADAA):
            raise ValueError("Dividing through operator is not supported")
        result = self.__class__(size=self.size)
        inv_other = 1.0 / other
        self.basic_linop(result, op_a=None, sc_b=inv_other, op_c=self)
        return result

    def __rmul__(self, other):
        # assume commutative, because if the other operator is an ADAA as well,
        # why else should rmul be called?
        return self.__mul__(other)

    def __neg__(self):
        result = self.__class__(size=self.size)
        self.basic_linop(result, op_a=None, sc_b=-1, op_c=self)
        return result

    def __len__(self):
        return self.size

    def __bool__(self):
        return self.size > 0

    def __eq__(self, other):
        return self.__class__.allclose(
            self, other
        )  # , rtol=1e-08, atol=1e-12)

    def __del__(self):
        self.free_memory()


class DContainer:
    """DContainer class description"""

    _LAYERS: dict[str, ADAA] = {}

    def __init__(self, *sizes):
        if len(sizes) != len(self._LAYERS):
            raise ValueError("Sizes must match the number of layers")
        self._layers = {
            key: layer(size)
            for (key, layer), size in zip(self._LAYERS.items(), sizes)
        }

    def __init_subclass__(cls, **layers):
        cls._LAYERS = layers
        return cls

    def __getitem__(self, key):
        assert key in self._layers
        return self._layers[key]

    def unpack(self, key, **kwargs):
        """unpack the requested layer"""
        assert key in self._layers
        return self._layers[key].unpack(**kwargs)

    def unpack_multi(self, keys, **kwargs):
        """unpack the requested layer"""
        for key in keys:
            assert key in self._layers
        return [self._layers[key].unpack(**kwargs) for key in keys]


class DLC(DContainer):
    """Dual Layer Container class. Implements host-device interaction"""


class SDLC(DLC):
    """Synced Dual Layer Container class"""


###############################################################################


class PurePyCoeffBackend(CoeffBackend):
    """implement the backend for 'PurePy'"""


class NumpyCoeffBackend(CoeffBackend):
    """implement the backend for 'Numpy'"""


class FortranCoeffBackend(CoeffBackend):
    """implement the backend for 'Fortran'"""


class CupyCoeffBackend(CoeffBackend):
    """implement the backend for 'Cupy'"""


class OpenClCoeffBackend(CoeffBackend):
    """implement the backend for 'OpenCl'"""


###############################################################################


class PurePyADAA(ADAA, backend=PurePyCoeffBackend, identifier="PUREPYTHON"):
    """Pure Python data layer"""

    @classmethod
    def _new_data(cls, size):
        return [0.0 for _ in range(size)], [0.0 for _ in range(size)]


class NumpyADAA(ADAA, backend=NumpyCoeffBackend, identifier="NUMPY"):
    """Numpy based data layer"""

    @classmethod
    def _new_data(cls, size):
        return np.zeros(size), np.zeros(size)


class FortranADAA(ADAA, backend=FortranCoeffBackend, identifier="FORTRAN"):
    """FORTRAN based data layer (implemented via NumPy)"""

    @classmethod
    def _new_data(cls, size):
        return np.zeros(size), np.zeros(size)


class CupyADAA(ADAA, backend=CupyCoeffBackend, identifier="CUPY"):
    """Cupy based data layer"""

    @classmethod
    def _new_data(cls, size):
        return cp.zeros(size), cp.zeros(size)


class OpenClADAA(ADAA, backend=OpenClCoeffBackend, identifier="OPENCL"):
    """Cupy based data layer"""

    _CL_CNTXT = cl.create_some_context()
    _CL_QUEUE = cl.CommandQueue(_CL_CNTXT)

    _CL_MFLAG = cl.mem_flags

    @classmethod
    def _new_data(cls, size, init_zeros=True):
        try:
            read_write = cls._CL_MFLAG.READ_WRITE
            if init_zeros:
                copy_from_host = cls._CL_MFLAG.COPY_HOST_PTR
                zeros = np.zeros(size)
                real = cl.Buffer(
                    cls._CL_CNTXT,
                    read_write | copy_from_host,
                    hostbuf=zeros,
                )
                imag = cl.Buffer(
                    cls._CL_CNTXT,
                    read_write | copy_from_host,
                    hostbuf=np.zeros(size),
                )
            else:
                real = cl.Buffer(
                    cls._CL_CNTXT,
                    read_write,
                    size=8 * size,  # size in bytes
                )
                imag = cl.Buffer(
                    cls._CL_CNTXT,
                    read_write,
                    size=8 * size,  # size in bytes
                )
        except cl.Error as e:
            warnings.warn("Failed to create OpenCL buffer: {}".format(str(e)))
            return (None, None)
        return real, imag


class Foo(
    DContainer,
    layer1=PurePyADAA,
    layer2=NumpyADAA,
    layer3=OpenClADAA,
    layer4=CupyADAA,
    layer5=FortranADAA,
):
    pass


# print(Foo._LAYERS)

# test = Foo(10, 12, 14, 16, 9)

# print(
#     test["layer1"].unpack(),
#     "\n",
#     type(test["layer1"].unpack()[0]),
#     type(test["layer1"].unpack()[0][0]),
#     "\n",
# )

# print(
#     test["layer2"].unpack(),
#     "\n",
#     type(test["layer2"].unpack()[0]),
#     type(test["layer2"].unpack()[0][0]),
#     "\n",
# )

# print(
#     test["layer3"].unpack(),
#     "\n",
#     type(test["layer3"].unpack()[0]),
#     "<skip unpacking the cl buffer>",
#     "\n",
# )

# print(
#     test["layer4"].unpack(),
#     "\n",
#     type(test["layer4"].unpack()[0]),
#     type(test["layer4"].unpack()[0][0]),
#     "\n",
# )

# print(
#     test["layer5"].unpack(),
#     "\n",
#     type(test["layer5"].unpack()[0]),
#     type(test["layer5"].unpack()[0][0]),
#     "\n",
# )


# class MyLayerPurePy(PurePyADAA, ident="PurePy2"):
#     pass


# print(MyLayerPurePy._IDENTIFIER)

# import gc


# def free_mem(a):
#     del a
#     gc.collect()


# import numpy as np


# a = np.zeros(10)
# print(a)

# free_mem(a)

# print(a)
