"""
#autogenerated#header#do#not#modify############################################
#
# File:        test_keymap.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   10/10/2024
# Last Update: 11/10/2024, 11:51
# Version:     0.0.33
#
#################################################end#of#autoheader#do#not#modify


"""

###############################################################################
#
#  .oPYo.  8                                                             8
#  8    8  8                                                             8
# o8YooP'  8  .oPYo.  o    o  .oPYo.  oPYo.  .oPYo.  o    o  odYo.  .oPYo8
#  8       8  .oooo8  8    8  8    8  8  `'  8    8  8    8  8' `8  8    8
#  8       8  8    8  8    8  8    8  8      8    8  8    8  8   8  8    8
#  8       8  `YooP8  `YooP8  `YooP8  8      `YooP'  `YooP'  8   8  `YooP'
# :..::::: .. :.....: :....8  :....8  ..:::: :.....: :.....: ..::.. :.....:
# :::::::: :: ::::::: ::ooP'. ::ooP'. :::::: ::::::: ::::::: :::::: :::::::
# :::::::: :: ::::::: ::...:: ::...:: :::::: ::::::: ::::::: :::::: :::::::
###############################################################################

from phoenix.keymap import KeyMap, Region, Key, Entry


# this is for messing around a little, proper tests must be done though!

kma = KeyMap()
kmb = KeyMap()
print(kma)
print(kmb)

print(KeyMap._enum)

rgc = Region(4)
print()
rgc.extend(Entry(name="something"))
rgc.extend(Entry(name="something"))
rgc.extend(Entry(name="something"))
rgc.extend(Entry(name="something"))
rgc.extend(Entry(name="something"))

print(rgc)
for key, entry in rgc.items():
    print(key, entry)

print("a", kma)

kma.put("No 1", rgc)
kma.put("No 2", rgc)
kma.update()
print(Region._enum)

# a.update()
# b.update()
# c.update()

print(rgc)

print(len(rgc._content))

for reg in kma.items():
    print(reg)

for idn, item in kma._key2pos.items():
    print(idn, item)

print(len(kma))

a = Key((("A",), "B"))
b = Key("B")
c = Key("C")

d = Key(a, b, "C")
print(d._as_list())
e = Key(a, Key(a, b, b), "F")
print(e._as_list())

print(e)

f = e | e

for _, key in e._unchain():
    print(key)

print("f", f.parents)

kma = KeyMap(name="foobar")
print(kma._kseg_factory.__doc__)
kma.put("foo", Region(3, name="reg@foo"))
kma.put("bar", Region(3, name="reg@bar"))
kma.put("baz", Region(3, name="reg@baz"))

kmb = KeyMap(name="foobaz")
kmb.entry("x")
kmb.entry(Key("y"))
kmb.entry("z")
kma.put("test", kmb)
kma.extend(kmb)
kma.extend(kmb)
kma.extend(kmb)
kma.extend(kmb)
try:
    kma.extend(kmb, autorename=False)
except KeyError:
    pass

print("parents:", kmb._parents)
# a.update()
print(a)

print(kma["foo"])
print(len(kma))
print(len(kma["foo"]))
print()
print(list(kma.keys(recursive=False)))
print(list(kma.keys(recursive=True)))

print()
print(list(kma.items(recursive=False)))
print(list(kma.items(recursive=True)))

print()
print(list(kma.values(recursive=False)))
print(list(kma.values(recursive=True)))

testkey = next(kma.keys(recursive=True))
print(testkey)
print(testkey._as_list())
print(testkey._as_list(tagged=True))

print(Key("a", Key(Key("a") | Key("b") | Key("c"))))

print()
print("how to find keys")
print("A", kma.find(kma.key("test"), kmb.key("x")))
print("B", kma.find(Key(kma.key("test"), kmb.key("x"))))
print("C", kma.find(Key("test", "x")))
print("D", kma.find("test", "x"))

print("\nwhats at...:")
for num in range(len(kma)):
    print(num, kma.whats_at(num))

print("\nkeys, recursive=True:")
for num, key in enumerate(kma.keys(recursive=True)):
    print(num, key)

print("\nkeys, recursive=False:")
for num, key in enumerate(kma.keys(recursive=False)):
    print(num, key)

print("\nitems:")
print(list(kma.items(recursive=True)))
print("lengh", len(kma))
