"""
#autogenerated#header#do#not#modify############################################
#
# File:        builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   03/03/2025
# Last Update: 25/03/2025, 16:28
# Version:     0.0.851
#
#################################################end#of#autoheader#do#not#modify


"""

from typing import Dict, Set, List, Any, Generator
from phoenix.fgen.instructionvar import InstructionEnvironment

from phoenix.fgen.instruction import Instruction
from phoenix.fgen.libroutinevar import LibRoutineVariable, Namespace
from phoenix.toolbox.logger import GLOBAL_LOGGER as log

from phoenix.fgen.instruction import (
    GenericInstruction,
    EnvironmentInstruction,
    MapApplyInstruction,
    InstructionGroup,
    RoutineInstruction,
    ContentInstruction,
    VariationInstruction,
    KeyMapInstruction,
    LinkVariableEnvironmentInstruction,
    OffsetEnvironmentInstruction,
)

from weakref import ref
from phoenix.fgen.codecontainer import CommentLine, DefinitionContainer

# MODULE_LOGGER = Logger(None, loglevel=2, stdout=True)

info = log.info
success = log.success
debug = log.debug
warn = log.warn
error = log.error


class Context:
    """
    A context indicating the intermediate state of a builder when going down
    the instruction tree. Keep track of indentation level, local variables,
    and variable environments. And maybe more (hence the class)
    """

    def __init__(
        self,
        /,
        *,
        parent: Instruction | None = None,
        level=0,
        environment: InstructionEnvironment | None = None,
        namespace: Namespace | None = None,
    ):
        if environment is None:
            environment = InstructionEnvironment()

        if parent is None:
            self._parent = None
        else:
            self._parent = ref(parent)
        self._level = level
        self._namespace = namespace
        self._environment = environment

    @property
    def parent(self):
        """access read-only attribute parent"""
        if self._parent is None:
            return None
        # weakref
        return self._parent()

    @property
    def level(self):
        """access read-only attribute level"""
        return self._level

    @property
    def environment(self):
        """access read-only attribute environment"""
        return self._environment

    @property
    def namespace(self):
        """access read-only attribute namespace"""
        return self._namespace

    def new_namespace_node(self):
        """provide a new namespace node"""
        if self._namespace is None:
            self._namespace = Namespace()
        else:
            self._namespace = self._namespace.inherit()

    def inherit(
        self,
        parent=None,
        environment=None,
        namespace=None,
    ):
        """
        Inherit to a new context object.
        Increment the level, optionally extend the namespace.
        Default behaviour for previous namespace and environment
        """

        if parent is None:
            parent = self.parent

        if environment is None:
            environment = self.environment

        if namespace is None:
            if self.namespace is None:
                namespace = Namespace()
            else:
                namespace = self.namespace  # .inherit()

        return Context(
            parent=parent,
            level=self.level + 1,
            namespace=namespace,
            environment=environment,
        )


class Optimizer:
    """Optimize the instruction tree w.r.t. certain aspects"""

    _CLSNAME_PREFIX = "Optimizer"
    _IDENTIFIER = "GENERIC"
    _VERSN = 0
    _BUILD = 0
    _BCKND = "GENERIC"

    def __init__(self, _internal=None, **params):
        self._params: Dict[str, Any] = params
        if _internal is None:
            _internal = {}
        _log_welcome = _internal.get("_log_welcome", True)
        if _log_welcome:
            self._welcome_log()

    def _welcome_log(self):
        info(*self._welcome_log_lines())

    def _welcome_log_lines(self):
        version, build = type(self)._VERSN, type(self)._BUILD
        yield (
            f"Hello from {type(self)._CLSNAME_PREFIX} "
            + f"'{type(self)._IDENTIFIER}'"
            + f" (v{version}.{build})"
        )
        yield from self._detail_log_lines()

    def _detail_log_lines(self):
        yield f"parameters ({len(self._params)}):"
        for param, value in self._params.items():
            yield f"  - {param}={value}"

    @property
    def identifier(self):
        """access the identifier"""
        return type(self)._IDENTIFIER

    @classmethod
    def __init_subclass__(
        cls,
        identifier=None,
        # _major=False,
    ):
        if identifier is None:
            identifier = cls.__name__.upper()
        cls._IDENTIFIER = identifier
        # handle versioning when a new builder is implemented.
        # if _major:
        #     cls._VERSN += 1
        #     cls._BUILD = 0
        # else:
        #     cls._BUILD += 1

    def __str__(self):
        param_string = "|".join(
            [f"{key}={val}" for key, val in self._params.items()]
        )
        return f"<{self._CLSNAME_PREFIX}.{self.identifier}: {param_string}>"

    def __repr__(self):
        # param_string = "|".join(
        #     [f"{key}={val}" for key, val in self._params.items()]
        # )
        return f"<{self._CLSNAME_PREFIX}.{self.identifier}>"

    @log.wrap_call
    def apply(self, instruction_tree):
        """apply the optimizer"""
        return instruction_tree.deepcopy()


class ValidationError(Exception):
    """An Error exception class thrown from validator"""


class Validator:
    """Validators check whether an instruction tree matches all requirements"""

    def __init__(self, **parameters):
        self._params = parameters

    def apply(self, instruction_tree):
        """apply the validator to an instruction tree"""
        # check if all requirements are fulfilled
        return True

    def raise_exception(self, message):
        """raise an exception from the tree"""
        return ValidationError(message)


class Builder(Optimizer, identifier="GENERIC"):
    """
    Make codecontainer from instruction tree
    """

    _CLSNAME_PREFIX = "Builder"

    _supp_instr_handler: Dict[type, Generator] = {}
    _excl_instr_classes: Set[type] = set()

    _comment_class = None
    _defcon_class = DefinitionContainer

    _class_optimizers: List[Optimizer] = []
    _class_validators: List[Validator] = []

    _VERSN = 0
    _BUILD = 0

    def __init_subclass__(cls, identifier=None):
        super().__init_subclass__(identifier=identifier)
        cls.set_default_handlers()

    def __init__(self, _internal=None, **params):
        super().__init__(**params, _internal={"_log_welcome": False})
        if _internal is None:
            _internal = {}
        _log_welcome = _internal.get("_log_welcome", True)
        if _log_welcome:
            self._welcome_log()
        self._optimizers = []
        self._validators = []

        self._extra_instr_handler: Dict[type, Generator] = {}
        self._avoid_instr_classes: Set[type] = set()

    def _detail_log_lines(self):
        yield from Optimizer._detail_log_lines(self)
        supported = list(type(self)._supp_instr_handler.keys())
        yield f"supported ({len(supported)}):"
        for instruction_type in supported:
            yield f"  + {instruction_type.class_identifier()}"
        excluded = list(type(self)._excl_instr_classes)
        yield f"excluded ({len(excluded)}):"
        for instruction_type in excluded:
            yield f"  - {instruction_type}"

    def add_supported_instruction_class(self, instruction_class, handler):
        """add a supported instruction class and its handler"""
        # force cast a generator
        self._extra_instr_handler[instruction_class] = handler

    def add_forbidden_instruction_class(self, instruction_class):
        """add a forbidden instruction class and its handler"""
        self._avoid_instr_classes.add(instruction_class)

    @classmethod
    @log.wrap_call
    def set_default_handler(cls, instruction_class: type, handler: Generator):
        """add a new instruction class to recognize and assign a proper handler"""
        cls._supp_instr_handler[instruction_class] = handler
        if instruction_class in cls._excl_instr_classes:
            cls._excl_instr_classes.remove(instruction_class)

    @classmethod
    @log.wrap_call
    def set_default_forbidden(cls, instruction_class):
        """remember that this kind of instruction is not supported"""
        cls._excl_instr_classes.add(instruction_class)
        if instruction_class in cls._supp_instr_handler:
            del cls._supp_instr_handler[instruction_class]

    @log.wrap_call
    def include_optimizer(self, optimizer):
        """append an optimizer to the list"""
        if not isinstance(optimizer, Optimizer):
            raise TypeError("Optimizer must be an instance of Optimizer")
        self._optimizers.append(optimizer)

    @log.wrap_call
    def include_validator(self, validator):
        """append an validator to the list"""
        if not isinstance(validator, Validator):
            raise TypeError("validator must be an instance of Validator")
        self._validators.append(validator)

    @log.wrap_call
    def match_instruction(self, instruction):
        """find a matching container for instruction"""
        for elder in instruction.__class__.__mro__:
            # note: mro contains type(self) and then all parents

            # check local classes
            if elder in self._avoid_instr_classes:
                return None
            if elder in self._extra_instr_handler:
                return self._extra_instr_handler[elder]

            # check defaults
            if elder in type(self)._excl_instr_classes:
                return None
            if elder in type(self)._supp_instr_handler:
                return type(self)._supp_instr_handler[elder]
        return None

    @log.wrap_call_gen
    def containers_from_instruction(
        self,
        instruction,
        context,
        **buildargs,
    ):
        """takes an instruction and generate code containers from it"""

        handler = None

        handler = self.match_instruction(instruction)
        # match instruction returns a callable referred to as generating.
        # generating takes the instruction, the builder, a context object and
        # buildargs as arguments and yields all code containers that are built
        # from there. The code containers are filled already, so calling that
        # routine on the tree root will recursively trigger all children to be
        # built recursively.
        # As builder is passed as an argument and the context is updated upon
        # traversing the branches, the generating callables can call
        # containers_from_instruction on the children.

        # there has to be a match, otherwise the builder cannot build this.
        if handler is None:
            raise TypeError("Instruction class not supported")

        debug(f"\tTarget     : {instruction}")
        debug(f"\tBuilder    : {self}")
        debug(f"\tEnvironment: {context.environment}")
        debug(f"\tLevel      : {context.level}")
        debug(f"\tParent     : {context.parent}")
        debug(f"\tNamespace  : {context.namespace}")
        debug(f"\tbuild args : {buildargs}")

        yield from handler(
            self,
            instruction=instruction,
            context=context,
            buildargs=buildargs,
        )
        # fill with content. This is not done on init automatically to be able
        # to implement that lazy as well.

    @log.wrap_call
    def generate_container_tree(self, instruction, **buildargs):
        """
        Build the code from the instruction tree. This is meant to be called
        from the trees root.
        This is a generator!
        """
        info("build code from instruction tree")
        optimized_tree = self.apply(instruction)  # this is a deepcopy call

        for num, optimizer in enumerate(self._optimizers):
            info(f"apply optimizer #{num + 1}")
            optimized_tree = optimizer.apply(optimized_tree)

        for num, optimizer in enumerate(type(self)._class_optimizers):
            info(f"apply class optimizer #{num + 1}")
            optimized_tree = optimizer.apply(optimized_tree)

        for num, validator in enumerate(self._validators):
            info(f"apply validator #{num + 1}")
            if not validator.apply(optimized_tree):
                raise validator.raise_exception(optimized_tree)

        for num, validator in enumerate(type(self)._class_validators):
            info(f"apply class validator #{num + 1}")
            if not validator.apply(optimized_tree):
                raise validator.raise_exception(optimized_tree)

        info("start with root instruction node")

        # context = (level, environment, parent, namespace)

        context = Context(
            level=0,
            environment=InstructionEnvironment(),
            parent=None,
            namespace=Namespace(),
        )

        definition_section = type(self)._defcon_class(context=context)
        definition_section.add_capture(lambda x: True)
        for container in self.containers_from_instruction(
            optimized_tree,
            context=definition_section.inherit_context(),
            **{**self._params, **buildargs},
        ):
            definition_section.append(container)

        info("reached end of instruction build")
        return definition_section.build()

    @classmethod
    @log.wrap_call
    def set_comment_class(cls, comment_class):
        """set the comment class for the builder"""
        cls._comment_class = comment_class

    @classmethod
    @log.wrap_call
    def set_defcon_class(cls, defcon_class):
        """set the comment class for the builder"""
        cls._defcon_class = defcon_class

    @log.wrap_call
    def comment(self, *lines, context: Context, buildargs):
        """generate one or multiple comment lines"""
        comment_class: type(CommentLine) | None = type(self)._comment_class
        if comment_class is not None:
            assert issubclass(comment_class, CommentLine)
            for line in lines:
                yield comment_class(
                    context=context,
                    **buildargs,
                ).set_comment(line)

    @log.wrap_call_gen
    def handle_basic_instruction(self, instruction, context, buildargs):
        """default handler for basic instruction"""
        raise NotImplementedError(
            f"No handler for instruction {instruction}. "
            "This base class should have never been invoked. "
            f"Original instruction type: {instruction.class_identifier()}"
        )
        yield

    @log.wrap_call_gen
    def handle_group_instruction(self, instruction, context, buildargs):
        """default handler for group instruction"""
        for child in instruction.instructions:
            yield from self.containers_from_instruction(
                child,
                context=context.inherit(),
                **buildargs,
            )

    @log.wrap_call_gen
    def handle_content_instruction(self, instruction, context, buildargs):
        """default handler for content instruction"""
        yield from self.containers_from_instruction(
            instruction.content,
            context=context.inherit(),
            **buildargs,
        )

    @log.wrap_call_gen
    def handle_generic_instruction(self, instruction, context, buildargs):
        """default handler for generic instruction"""
        yield from self.comment(
            str(instruction.to_dict()), context=context, buildargs=buildargs
        )

    @log.wrap_call_gen
    def handle_routine_instruction(self, instruction, context, buildargs):
        """default handler for routine instruction"""
        return
        yield

    @log.wrap_call_gen
    def handle_mapapply_instruction(self, instruction, context, buildargs):
        """default handler for mapapply instruction"""
        for environment in instruction.environments:
            yield from self.containers_from_instruction(
                instruction.content,
                context=context.inherit(extra_environment=environment),
                **buildargs,
            )

    @log.wrap_call_gen
    def handle_variation_instruction(self, instruction, context, buildargs):
        """default handler for variation instruction"""
        yield from self.containers_from_instruction(
            instruction.content,
            context=context.inherit(),
            **buildargs,
        )

    @log.wrap_call_gen
    def handle_environment_instruction(self, instruction, context, buildargs):
        """default handler for environment instruction"""
        yield from self.containers_from_instruction(
            instruction.content,
            context=context.inherit(extra_environment=instruction.environment),
            **buildargs,
        )

    @classmethod
    @log.wrap_call
    def remove_handler(cls, instruction_class):
        """remove a handler"""
        if instruction_class in cls._supp_instr_handler:
            del cls._supp_instr_handler[instruction_class]

    @log.wrap_call
    @classmethod
    def include_instruction_class(cls, instruction_class):
        """remove a handler"""
        if instruction_class in cls._excl_instr_classes:
            cls._excl_instr_classes.remove(instruction_class)

    @classmethod
    @log.wrap_call
    def set_default_handlers(cls):
        """set the instruction handlers to a default"""
        handler_mappings = [
            # base instruction
            (Instruction, cls.handle_basic_instruction),
            #
            # first order subclasses
            (InstructionGroup, cls.handle_group_instruction),
            (ContentInstruction, cls.handle_content_instruction),
            #
            # leaf instruction
            (GenericInstruction, cls.handle_generic_instruction),
            #
            # content based
            (RoutineInstruction, cls.handle_routine_instruction),
            (MapApplyInstruction, cls.handle_mapapply_instruction),
            (VariationInstruction, cls.handle_variation_instruction),
            #
            # environments
            (EnvironmentInstruction, cls.handle_environment_instruction),
        ]
        cls.set_handlers(handler_mappings)

    @classmethod
    @log.wrap_call
    def set_handlers(cls, handler_mappings):
        """set the mappings of instruction classes to handlers"""
        for instruction_class, class_handler in handler_mappings:
            cls.set_default_handler(instruction_class, class_handler)


Builder.set_default_handlers()

if __name__ == "__main__":

    class TestBuilder(Builder, identifier="TEST"):
        """A builder for pure testing purposes"""

        @log.wrap_call
        def test_the_log(self, arg, **kwargs):
            """a good testing routine for the builder's log module"""
            info("foobar was here")
            debug(f"my argument is {arg}")
            debug(f"my kwarguments are {kwargs}")
            return "fooo"

        # exceptions trigger a warning because they are treated outside of the call
        @log.controlled
        @log.wrap_call
        def test_the_log2(self, arg, **kwargs):
            """a bad testing routine for the builder's log module"""
            info("foobar was here, too")
            debug(f"my argument is {arg}")
            debug(f"my kwarguments are {kwargs}")
            debug("I will raise an exception now.")
            raise ValueError("argument should be an integer")
            return "fooo"

    class TestOptimizer(Optimizer, identifier="TESTAGAIN"):
        pass

    log.set_loglevel(2)
    log.set_logfile("testlog.txt")

    info("run some tests")
    mybuilder = TestBuilder(foo="bar")
    mybuilder.test_the_log(1)
    mybuilder.test_the_log(2)
    mybuilder.test_the_log(3)
    info("now let's do a critical one")
    try:
        mybuilder.test_the_log2("test")
    except ValueError:
        pass
    success("This line should be visible")
    warn("now it's getting serious...")
    debug()
    # mybuilder.test_the_log2("testtest")
    # error("This should not be printed")
    mybuilder.test_the_log(15, x="y")

    myoptimizer = TestOptimizer(foo="bazzz")

    success()
    info()

    # build:
    # - look for a proper codecontainer by looking up the instructions
    #   MRO.
    # - input and output args are assigned to ADAAs at the highest
    #   level. This assignment is carried along in the known_variables
    #   dictionary. Any instruction variable known to an instruction
    #   can be mapped to the proper set of routine variables. The
    #   mapping goes through all environments.
    # - check if the signature is supported. If not, try to find the
    #   next match in MRO
    #   alternatively, the lookup can directly include the MRO and the
    #   structure, depending on the complexity. Control structures most
    #   likely don't care for any signature, so I thought two individual
    #   checks can safe us some effort.
    # - generate the code container with the current information known,
    #   implementing the proper libroutine variables and handle all
    #   dependencies, calls, ...


# required optimizers
# - GPU: resolve parallel environments that contain multiple other parallel environments
# - translate the most inner group into a parallel group
#   -> group.unpack() to MapOffset
