"""
#autogenerated#header#do#not#modify############################################
#
# File:        codecontainers.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   11/02/2025
# Last Update: 11/02/2025, 20:07
# Version:     0.0.29
#
#################################################end#of#autoheader#do#not#modify


"""
