"""
#autogenerated#header#do#not#modify############################################
#
# File:        context.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   07/04/2025
# Last Update: 29/04/2025, 19:29
# Version:     0.0.47
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations


from hashlib import sha256

from typing import Dict, Set, List, Any, Generator

from phoenix.fgen.instructionvar import InstructionEnvironment
from phoenix.fgen.instruction import Instruction
from phoenix.fgen.libroutinevar import LibRoutineVariable, Namespace
from phoenix.fgen.codecontainer import CodeContainer

from weakref import ref


class Context:
    """
    A context indicating the intermediate state of a builder when going down
    the instruction tree. Keep track of indentation level, local variables,
    and variable environments. And maybe more (hence the class)
    """

    def __init__(
        self,
        /,
        *,
        parent: CodeContainer | None = None,
        level: int = 0,
        environment: InstructionEnvironment | None = None,
        namespace: Namespace | None = None,
        # assignments: dict | None = None,
        name: str | None = None,
        # frame_selectors: Set[LibRoutineFrameSelectVariable] | None = None,
        _names: List[str] | None = None,
    ):
        if environment is None:
            environment = InstructionEnvironment()

        if namespace is None:
            namespace = Namespace()

        if parent is None:
            self._parent = None
        else:
            self._parent = ref(parent)

        # if frame_selectors is None:
        #     frame_selectors = set()

        self._container = None
        self._level = level
        self._namespace = namespace
        self._environment = environment
        # self._assignments = assignments
        self._names = []
        # self._frame_selectors = frame_selectors

        if name is not None:
            self._names.append(name)

    # there is only one assignments instance being passed down a routine.

    @property
    def name(self):
        """return a readable name from name combinations"""
        if self._names:
            return "_".join(self._names)
        else:
            return "_"

    def hashed_name(self, num_symbols=8):
        """return a shortened hashed name"""
        return sha256(self.name).hexdigest()[:num_symbols]

    @property
    def parent(self):
        """access read-only attribute parent"""
        if self._parent is None:
            return None
        # weakref
        return self._parent()

    @property
    def level(self):
        """access read-only attribute level"""
        return self._level

    @property
    def environment(self):
        """access read-only attribute environment"""
        return self._environment

    @property
    def namespace(self):
        """access read-only attribute namespace"""
        return self._namespace

    @property
    def container(self):
        """access container"""
        return self._container

    # @property
    # def frame_selectors(self):
    #     """access frame selectors"""
    #     return self._frame_selectors

    def set_container(self, container):
        """set container"""
        if self._container is not None:
            raise ValueError("Cannot change container once set")
        self._container = container
        return self

    def new_namespace_node(self):
        """provide a new namespace node"""
        if self._namespace is None:
            self._namespace = Namespace()
        else:
            self._namespace = self._namespace.inherit()

    # def new_assignment_node(self):
    #     """provide a new namespace node"""
    #     self._assignments = {}

    # def set_assignment(self, instr_var_class, assignment):
    #     """set the assignment for an instruction variable class"""
    #     if self._assignments is None:
    #         if parent is None:
    #             raise ValueError("Cannot assign to parent, no parent found!")
    #         return parent.set_assignment(instr_var_class, assignment)
    #     self._assignments[instr_var_class] = assignment

    # def get_assignment(self, instr_var_class):
    #     """get the assignment for an instruction variable class"""
    #     if self._assignments is None:
    #         if parent is None:
    #             raise ValueError("Cannot find assignment, no parent found!")
    #     else:
    #         if instr_var_class in self._assignments:
    #             return self._assignments[instr_var_class]
    #     return parent.get_assignment(instr_var_class)

    def inherit(
        self,
        name=None,
        parent=None,
        environment=None,
        namespace=None,
        # select_frame=None,
    ):
        """
        Inherit to a new context object.
        Increment the level, optionally extend the namespace.
        Default behaviour for previous namespace and environment
        """

        if name is not None:
            self._names.append(name)

        if parent is None:
            if self.container is None:
                parent = self.parent
            else:
                parent = self.container

        if environment is None:
            environment = self.environment
        else:
            environment = self.environment.merge(environment)

        if namespace is None:
            if self.namespace is None:
                namespace = Namespace()
            else:
                namespace = (
                    self.namespace
                )  # .inherit()  use new_namespace_node

        # frame_selectors = set(self.frame_selectors)
        # if select_frame is not None:
        #     frame_selectors.add(select_frame)

        return Context(
            parent=parent,
            level=self.level + 1,
            namespace=namespace,
            environment=environment,
            # assignments=None,
            # frame_selectors=frame_selectors,
            _names=self._names,
        )
