"""
#autogenerated#header#do#not#modify############################################
#
# File:        fortran_builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/04/2025
# Last Update: 01/04/2025, 20:40
# Version:     0.0.6
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from typing import Any, Dict

from phoenix.fgen.builder import Builder
from phoenix.fgen.codecontainer import (
    CodeLine,
    CommentLine,
    EnclosingContainer,
    DefinitionContainer,
    LoopContainer,
    RoutineContainer,
    ConditionalContainer,
)
from phoenix.fgen.libroutinevar import LibRoutineLocalVariable

from phoenix.toolbox.logger import GLOBAL_LOGGER

GLOBAL_LOGGER.set_logfile("fortranbuilder")
GLOBAL_LOGGER.set_loglevel("INFO")
GLOBAL_LOGGER.add_note(
    """
    This is the first version of the FORTRAN builder.
    The supported data is compatible to numpy. At this point I can
    start to design how call patterns are implemented and how they
    come from the signature of the ADAAs.
    Also a basic compilation call is required, let's see how that's
    gonna play out.
    """
)

GLOBAL_LOGGER.log_to_stdout(False)


###############################################################################
#
# .oPYo.                   o            o
# 8    8                   8
# 8       .oPYo.  odYo.   o8P  .oPYo.  o8  odYo.  .oPYo.  oPYo.  .oPYo.
# 8       8    8  8' `8    8   .oooo8   8  8' `8  8oooo8  8  `'  Yb..
# 8    8  8    8  8   8    8   8    8   8  8   8  8.      8        'Yb.
# `YooP'  `YooP'  8   8    8   `YooP8   8  8   8  `Yooo'  8      `YooP'
# :.....: :.....: ..::.. ::..: :.....: :.. ..::.. :.....: ..:::: :.....:
# ::::::: ::::::: :::::: ::::: ::::::: ::: :::::: ::::::: :::::: :::::::
# ::::::: ::::::: :::::: ::::: ::::::: ::: :::::: ::::::: :::::: :::::::
###############################################################################


class F90CodeLine(CodeLine):
    """Plain Text version of a StatementLine"""


class F90CommentLine(CommentLine):
    """Plain Text version of a CommentLine"""

    COMMENT_PREFIX = "! "

    # some_aux_variable = LibRoutineLocalVariable("testvar")


class F90BracketContainer(EnclosingContainer):
    """Plain Text version of a EnvironmentContainer"""

    INDENT_BODY = True

    def fill_enclosings(self, open_string, close_string, **buildargs):
        """this method defines the enclosing characters."""
        return super().fill_enclosings(open_string, close_string, **buildargs)


class F90LoopContainer(LoopContainer):
    """Plain Text version of a DefinitionContainer"""

    INDENT_BODY = True


class F90DefinitionContainer(DefinitionContainer):
    """Plain Text version of a DefinitionContainer"""

    INDENT_BODY = True

    def build(self):
        self.append_head(
            F90CodeLine(context=self.context).set_line(
                "BEGIN DEFINITION CONTAINER"
            )
        )
        if list(self.captured):
            self.append_head(
                F90CodeLine(context=self.context).set_line("defines:")
            )
        self.append_foot(
            F90CodeLine(context=self.context).set_line(
                "END OF DEFINITION CONTAINER"
            )
        )
        return super().build()


class F90RoutineDefinition(RoutineContainer):
    """Plain Text version of a RoutineDefinition"""

    # routine definition
    # variable initialization
    # body


class F90LibraryDefinition(RoutineContainer):
    """Plain Text version of a RoutineDefinition"""

    # collect all library routines


###############################################################################
#
#  .oPYo.           o  8       8
#  8   `8              8       8
# o8YooP'  o    o  o8  8  .oPYo8  .oPYo.  oPYo.
#  8   `b  8    8   8  8  8    8  8oooo8  8  `'
#  8    8  8    8   8  8  8    8  8.      8
#  8oooP'  `YooP'   8  8  `YooP'  `Yooo'  8
# :......: :.....: :.. .. :.....: :.....: ..::::
# :::::::: ::::::: ::: :: ::::::: ::::::: ::::::
# :::::::: ::::::: ::: :: ::::::: ::::::: ::::::
###############################################################################


class Fortran90Builder(Builder, identifier="PLAINTEXT"):
    """PlainTextBuilder"""

    def handle_basic_instruction(self, instruction, context, buildargs):
        yield F90CodeLine(context, **buildargs).set_line(
            f"Unknown instruction {instruction}",
        )

    def handle_group_instruction(self, instruction, context, buildargs):
        outer = F90BracketContainer(
            context=context, **buildargs
        ).fill_enclosings(
            open_string=f"BEGIN Group {instruction.identifier} {{ ",
            close_string=f"END Group {instruction.identifier} }} ",
        )
        inside_context = context.inherit(parent=outer)
        for inner_instruction in instruction.instructions:
            for inner_container in self.containers_from_instruction(
                inner_instruction,
                inside_context,
                **buildargs,
            ):
                outer.append(inner_container)
        yield outer

    def handle_content_instruction(self, instruction, context, buildargs):
        outer = F90BracketContainer(
            context=context, **buildargs
        ).fill_enclosings(
            open_string=f"BEGIN Content Group {instruction.identifier} {{ ",
            close_string=f"END Content Group {instruction.identifier} }} ",
        )
        for key, value in instruction.items():
            if key in ["identifier", "content"]:
                continue
            outer.append(
                F90CodeLine(context=context, **buildargs).set_line(
                    line=f":{key}={value}"
                )
            )
        inside_context = context.inherit(parent=outer)
        for inner_instruction in instruction.content:
            for inner_container in self.containers_from_instruction(
                inner_instruction,
                inside_context,
                **buildargs,
            ):
                outer.append(inner_container)
        yield outer

    def handle_generic_instruction(self, instruction, context, buildargs):
        yield F90CodeLine(context=context, **buildargs).set_line(
            line=f"generic instruction: {instruction.identifier}"
        )
        for key, value in instruction.items():
            if key in ["identifier"]:
                continue
            yield F90CodeLine(context=context, **buildargs).set_line(
                line=f":{key}={value}"
            )

    def handle_routine_instruction(self, instruction, context, buildargs):
        yield from super().handle_routine_instruction(
            instruction, context, buildargs
        )

    def handle_mapapply_instruction(self, instruction, context, buildargs):
        yield from super().handle_mapapply_instruction(
            instruction, context, buildargs
        )

    def handle_variation_instruction(self, instruction, context, buildargs):
        yield from super().handle_variation_instruction(
            instruction, context, buildargs
        )

    def handle_environment_instruction(self, instruction, context, buildargs):
        yield from super().handle_environment_instruction(
            instruction, context, buildargs
        )


Fortran90Builder.set_default_container("COMMENT", F90CommentLine)
Fortran90Builder.set_default_container("DEFCONT", F90DefinitionContainer)
Fortran90Builder.set_default_container("ROUTINE", F90RoutineDefinition)
Fortran90Builder.set_default_container("LIBRARY", F90LibraryDefinition)


from phoenix.fgen.builder import Context
import sys
from phoenix.fgen.instruction import GenericInstruction, InstructionGroup


a = Fortran90Builder()

test = InstructionGroup(
    [
        GenericInstruction(foo="bar1", answer=42.1),
        GenericInstruction(foo="bar2", answer=42.2),
        GenericInstruction(foo="bar3", answer=42.3),
        GenericInstruction(foo="bar4", answer=42.4),
        GenericInstruction(foo="bar5", answer=42.5),
    ]
)
ctxt = Context()

largegroup = InstructionGroup([test, test, test])

container_tree = a.generate_container_tree(largegroup)

for indent, line in container_tree.get_codelines():
    print(indent * "  " + line)

sys.exit()
