"""
#autogenerated#header#do#not#modify############################################
#
# File:        fortran_builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/04/2025
# Last Update: 26/05/2025, 16:11
# Version:     0.0.418
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from typing import Any, Dict

from phoenix.fgen.builder import Builder, BuildChain
from phoenix.fgen.codecontainer import (
    CodeLine,
    StatementLine,
    CommentLine,
    EmbeddingContainer,
    DefinitionContainer,
    # LoopContainer,
    RoutineContainer,
    ConditionalContainer,
    NamedContainer,
    KernelContainer,
    LibraryContainer,
    MultiFrameContainer,
)
from phoenix.fgen.libroutinevar import (
    LibRoutineVariable,
    LibRoutineInputVariable,
    LibRoutineOutputVariable,
    LibRoutineInOutVariable,
    LibRoutineLocalVariable,
    LibRoutineConstant,
    LibRoutineMultiFrame,
)

from phoenix.fgen.libroutine import LibRoutine
from phoenix.fgen.library import Library

from phoenix.fgen.instruction import AffineOperationInstruction

from phoenix.toolbox.logger import GLOBAL_LOGGER

from phoenix.aux import multiline_iterable

GLOBAL_LOGGER.set_logfile("fortranbuilder")
GLOBAL_LOGGER.set_loglevel("INFO")
GLOBAL_LOGGER.add_note(
    """
    This is the first version of the FORTRAN builder.
    The supported data is compatible to numpy. At this point I can
    start to design how call patterns are implemented and how they
    come from the signature of the ADAAs.
    Also a basic compilation call is required, let's see how that's
    gonna play out.
    """
)

GLOBAL_LOGGER.log_to_stdout(False)


###############################################################################
#
# .oPYo.                   o            o
# 8    8                   8
# 8       .oPYo.  odYo.   o8P  .oPYo.  o8  odYo.  .oPYo.  oPYo.  .oPYo.
# 8       8    8  8' `8    8   .oooo8   8  8' `8  8oooo8  8  `'  Yb..
# 8    8  8    8  8   8    8   8    8   8  8   8  8.      8        'Yb.
# `YooP'  `YooP'  8   8    8   `YooP8   8  8   8  `Yooo'  8      `YooP'
# :.....: :.....: ..::.. ::..: :.....: :.. ..::.. :.....: ..:::: :.....:
# ::::::: ::::::: :::::: ::::: ::::::: ::: :::::: ::::::: :::::: :::::::
# ::::::: ::::::: :::::: ::::: ::::::: ::: :::::: ::::::: :::::: :::::::
###############################################################################


class F90CodeLine(CodeLine):
    """Plain Text version of a StatementLine"""


class F90CommentLine(CommentLine):
    """Plain Text version of a CommentLine"""

    COMMENT_PREFIX = "! "

    # some_aux_variable = LibRoutineLocalVariable("testvar")


class F90MultiFrameContainer(MultiFrameContainer):
    """Plain Text version of a DefinitionContainer"""

    INDENT_BODY = True

    def generate_head_containers(self):
        if self._multiframe_variable is not None:
            yield from self.codelines_from_text(
                f"DO {self._multiframe_variable.expr()} = {self._min_value}, {self._max_value-1}"
            )

    def generate_foot_containers(self):
        if self._multiframe_variable is not None:
            yield from self.codelines_from_text(
                f"END DO  ! {self._multiframe_variable.expr()}"
            )


class F90DefinitionContainer(DefinitionContainer):
    """Plain Text version of a DefinitionContainer"""

    INDENT_BODY = False


class F90RoutineContainer(RoutineContainer):
    """Plain Text version of a RoutineDefinition"""

    INDENT_BODY = True
    multiframe_container_class = F90MultiFrameContainer

    def generate_head_containers(self, **_):
        call_args = (var.as_argument() for var in self.get_argument_variables())
        yield F90CommentLine(f"Subroutine: {self.name}", context=self.context)
        yield from self.codelines_from_text(
            f"SUBROUTINE {self.name}({', '.join(call_args)})"
        )

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text(f"END SUBROUTINE {self.name}")


class F90KernelContainer(KernelContainer):
    """Plain Text version of a RoutineDefinition"""

    INDENT_BODY = True

    def generate_head_containers(self, **_):
        call_args = (var.as_argument() for var in self.get_argument_variables())
        yield F90CommentLine(f"Kernel: {self.name}", context=self.context)
        yield from self.codelines_from_text(
            f"SUBROUTINE {self.name}({', '.join(call_args)})"
        )

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text(f"END SUBROUTINE {self.name}")


class F90AffineContainer(StatementLine):
    INDENT_BODY = False
    _BLUEPRINT = "{y_expression} = {y_expression} + {a_value} * {x_expression} + {b_value}"

    def __init__(self, y, yo, a, x, xo, b, *, context, **params):
        super().__init__(
            {
                "y_expression": y.expr_at(*yo),
                "x_expression": x.expr_at(*xo),
                "a_value": a,
                "b_value": b,
            },
            context=context,
            **params,
        )
        self.requires(x)
        self.requires(y)


class F90LibraryContainer(LibraryContainer):
    """Plain Text version of a RoutineDefinition"""

    INDENT_BODY = True

    def __init__(self, name, *, context, **buildargs):
        # print("f90lib init")
        super().__init__(name, context=context, **buildargs)

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(f"MODULE {self.name}")

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text(f"END MODULE {self.name}")

    def generate_preamble_containers(self, **_):
        yield from self.codelines_from_text("")
        yield from self.codelines_from_text("IMPLICIT NONE")
        yield from self.codelines_from_text("")
        yield from super().generate_preamble_containers()
        yield from self.codelines_from_text("")
        yield from self.codelines_from_text("CONTAINS")
        yield from self.codelines_from_text("")


class F90LibRoutineVariable(LibRoutineVariable):
    """LibRoutineVariable F90 Base class"""

    _intent = None

    def lookup_intent(self, intent):
        if intent is None:
            return None
        if intent == "RO":
            return "IN"
        if intent == "WO":
            return "OUT"
        if intent == "RW":
            return "INOUT"
        raise ValueError(f"Unknown intent: {intent}")

    def get_definition_lines(self) -> str:
        """create the line that defines the variable"""
        intent_str = ""
        dimension_str = ""
        intent = self.lookup_intent(type(self)._intent)
        if intent:
            intent_str = f", intent({intent})"
        if not self.is_scalar:
            dimension_str = f", dimension({self._size})"
        yield f"{self.lookup_dtype(self._dtype)}{intent_str}{dimension_str} :: {self._name}"

    def lookup_dtype(self, dtype):
        match dtype:
            case "f64":
                return "double precision"
            case "f32":
                return "real"
            case "i64":
                return "integer(8)"
            case "i32":
                return "integer"
        raise ValueError(f"Unknown dtype: {dtype}")

    def expr_at(self, *offsets, **kwargs):
        """Fortran variables start at 1, not 0"""
        return super().expr_at(1, *offsets, **kwargs)


class F90LocalVariable(F90LibRoutineVariable, LibRoutineLocalVariable):
    """LibRoutineVariable F90 Base class"""


class F90InputVariable(F90LibRoutineVariable, LibRoutineInputVariable):
    _intent = "RO"


class F90OutputVariable(F90LibRoutineVariable, LibRoutineOutputVariable):
    _intent = "WO"


class F90InOutVariable(F90LibRoutineVariable, LibRoutineInOutVariable):
    _intent = "RW"


class F90MultiFrame(F90LibRoutineVariable, LibRoutineMultiFrame):
    local_variable_class = F90LocalVariable
    input_variable_class = F90InputVariable


class F90Constant(F90LibRoutineVariable, LibRoutineConstant):
    def get_definition_lines(self) -> str:
        """create the line that defines the variable"""
        dimension_str = ""
        if not self.is_scalar:
            dimension_str = f", dimension({self._size})"
        if self.is_scalar:
            yield f"{self.lookup_dtype(self._dtype)}, parameter :: {self._name} = {self.value}"
            return
        line = f"{self.lookup_dtype(self._dtype)}, parameter :: {self._name}({self.size}) = "
        prefix = "(/"
        suffix = "/)"
        conv = float
        if self.dtype[0] == "i":
            conv = int
        for line in multiline_iterable(
            [conv(value) for value in self.values],
            separator=", ",
            max_line_length=100,
            indent="",
            extra_indent="  ",
            linebreak=" &",
            prefix=line + prefix,
            suffix=suffix,
            prefix_suffix_lines=True,
        ):
            yield line


class F90Library(Library):
    """F90 Version of a Library"""

    FILEENDING = "f90"
    INDENTSTR = "  "
    LIBRARY_CONTAINER = F90LibraryContainer


###############################################################################
#
#  .oPYo.           o  8       8
#  8   `8              8       8
# o8YooP'  o    o  o8  8  .oPYo8  .oPYo.  oPYo.
#  8   `b  8    8   8  8  8    8  8oooo8  8  `'
#  8    8  8    8   8  8  8    8  8.      8
#  8oooP'  `YooP'   8  8  `YooP'  `Yooo'  8
# :......: :.....: :.. .. :.....: :.....: ..::::
# :::::::: ::::::: ::: :: ::::::: ::::::: ::::::
# :::::::: ::::::: ::: :: ::::::: ::::::: ::::::
###############################################################################


my_fancy_var = F90InOutVariable(
    None, None, name="my_fancy_var", dtype="f64", size=20
)


class Fortran90Builder(Builder, identifier="FORTRAN90"):
    """F90 Builder"""

    # _routine_cls = F90RoutineContainer
    # _comment_cls = F90CommentLine

    # def handle_group_instruction(self, instruction, context, buildargs):
    #     yield from super().handle_group_instruction(
    #         instruction, context, buildargs
    #     )

    # def handle_content_instruction(self, instruction, context, buildargs):
    #     yield from super().handle_content_instruction(
    #         instruction, context, buildargs
    #     )

    # def handle_routine_instruction(self, instruction, context, buildargs):
    #     yield from super().handle_routine_instruction(
    #         instruction, context, buildargs
    #     )

    # def handle_mapapply_instruction(self, instruction, context, buildargs):
    #     yield from super().handle_mapapply_instruction(
    #         instruction, context, buildargs
    #     )

    def handle_environment_instruction(self, instruction, context, buildargs):
        foo = F90CommentLine(context=context)
        lvar = F90MultiFrame(14)
        foo.requires(lvar)
        foo.set_line(
            f"I probably need a multiframe variable here. I will use {lvar.name}"
        )
        yield foo
        yield from super().handle_environment_instruction(
            instruction, context, buildargs
        )

    def handle_affine_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        alpha = instruction_dict.get("alpha")
        beta = instruction_dict.get("beta")
        otgt = list(tgt0.offsets)
        osrc = list(src0.offsets)
        yield F90CommentLine(f"tgt0={tgt0.name} @ {otgt}", context=context)
        yield F90CommentLine(f"src0={src0.name} @ {osrc}", context=context)
        yield F90CommentLine(f"alpha = {alpha}", context=context)
        yield F90CommentLine(f"beta  = {beta}", context=context)
        x_var_real = context.namespace.find_assignment(type(src0), "real")
        x_var_imag = context.namespace.find_assignment(type(src0), "imag")
        y_var_real = context.namespace.find_assignment(type(tgt0), "real")
        y_var_imag = context.namespace.find_assignment(type(tgt0), "imag")
        x_var_offs = src0.offsets
        y_var_offs = tgt0.offsets
        a_real = alpha.real
        a_imag = alpha.imag
        b_real = beta.real
        b_imag = beta.imag
        yield F90AffineContainer(
            y_var_real,
            y_var_offs,
            a_real,
            x_var_real,
            x_var_offs,
            0,
            context=context,
        )
        yield F90AffineContainer(
            y_var_real,
            y_var_offs,
            -a_imag,
            x_var_imag,
            x_var_offs,
            b_real,
            context=context,
        )
        yield F90AffineContainer(
            y_var_imag,
            y_var_offs,
            a_real,
            x_var_imag,
            x_var_offs,
            0,
            context=context,
        )
        yield F90AffineContainer(
            y_var_imag,
            y_var_offs,
            a_imag,
            x_var_real,
            x_var_offs,
            b_imag,
            context=context,
        )
        yield CodeLine("", context=context)

    def handle_generic_instruction(self, instruction, context, buildargs):
        yield from super().handle_generic_instruction(
            instruction, context, buildargs
        )
        foo = CodeLine("! this is a test expression {foo}", context=context)
        temp1 = self.request_temp(
            foo,
            "test_temporary1",
            F90LocalVariable,
            size=42,
            dtype="i64",
        )
        foo.format(foo=f"{temp1.expr_at(5)} + 2")
        foo.requires(my_fancy_var)
        yield foo


Fortran90Builder.set_instruction_class_handler(
    AffineOperationInstruction, Fortran90Builder.handle_affine_instruction
)

F90LibraryContainer.set_comment_class(F90CommentLine)
F90RoutineContainer.set_comment_class(F90CommentLine)
Fortran90Builder.set_comment_class(None)
Fortran90Builder.set_comment_class(F90CommentLine)

# Fortran90Builder.set_routine_class(F90RoutineContainer)
# Fortran90Builder.set_routine_class(F90KernelContainer)

from phoenix.fgen.builder import Context
import sys
from phoenix.fgen.instruction import GenericInstruction, InstructionGroup


my_builder = Fortran90Builder()

test_chain = BuildChain(my_builder)

"""test = InstructionGroup(
    [
        GenericInstruction(foo="bar1", answer=42.1),
        GenericInstruction(foo="bar2", answer=42.2),
        GenericInstruction(foo="bar3", answer=42.3),
        GenericInstruction(foo="bar4", answer=42.4),
        GenericInstruction(foo="bar5", answer=42.5),
    ]
)

largegroup = InstructionGroup([test, test, test])

"""


from phoenix.keymap import KeyMap
from phoenix.fgen.instructionvar import InstructionVariable
from phoenix.fgen.instruction import (
    LinearOperationInstruction,
    OffsetEnvironmentInstruction,
)


ltl_km = KeyMap(name="little")
ltl_km.entry("key1")
ltl_km.entry("key2")
ltl_km.entry("key3")

big_km = KeyMap(name="big")
big_km.link("foo0", ltl_km)
big_km.link("foo1", ltl_km)
big_km.link("foo2", ltl_km)
big_km.link("foo3", ltl_km)
big_km.link("foo4", ltl_km)

big_km.update()
# print(list(big_km.keys()))

VarInp = InstructionVariable.new(name="input1", config=big_km)
VarOut = InstructionVariable.new(name="output1", config=big_km)
# VarOut = KeyMapInstructionVariable("output1", keymap=big_km)
# KeyMapInstructionVariable("input1", keymap=big_km)

VarInpInner = InstructionVariable.new("inner_input1", config=None)
VarOutInner = InstructionVariable.new("inner_output1", config=None)

# print(InstructionVariable().name)

test_instructions_inner = InstructionGroup(
    [
        LinearOperationInstruction(
            VarOutInner("key1"), VarInpInner("key3"), 1.0 + 2j
        ),
        LinearOperationInstruction(
            VarOutInner("key2"), VarInpInner("key2"), 1.0 + 2j
        ),
        LinearOperationInstruction(
            VarOutInner("key3"), VarInpInner("key1"), 1.0 + 2j
        ),
    ]
)
test_instructions1 = InstructionGroup(
    [
        OffsetEnvironmentInstruction(
            test_instructions_inner,
            offsets={
                VarInpInner: VarInp(f"foo{val}"),
                VarOutInner: VarOut(f"foo{val}"),
            },
        )
        for val in range(1)
    ]
)

test_instructions2 = InstructionGroup(
    [
        OffsetEnvironmentInstruction(
            InstructionGroup(
                [
                    OffsetEnvironmentInstruction(
                        test_instructions_inner,
                        offsets={
                            VarInpInner: VarInp(f"foo{val_inp}"),
                        },
                    )
                    for val_inp in range(2)
                ]
            ),
            offsets={
                VarOutInner: VarOut(f"foo{val_out}"),
            },
        )
        for val_out in range(1)
    ]
)

# largegroup = test_instructions1.flatten()
largegroup = test_instructions1

ctxt = Context()
ctxt.namespace.assign(
    VarInp,
    "real",
    F90InputVariable(VarInp, "real", "input_real", size=999),
)
ctxt.namespace.assign(
    VarInp,
    "imag",
    F90InputVariable(VarInp, "imag", "input_imag", size=999),
)
ctxt.namespace.assign(
    VarOut,
    "real",
    F90OutputVariable(VarOut, "real", "output_real", size=999),
)
ctxt.namespace.assign(
    VarOut,
    "imag",
    F90OutputVariable(VarOut, "imag", "output_imag", size=999),
)


lib_container = F90LibraryContainer("test_library", context=ctxt)

# lib_container.add_capture_trigger(lambda x: True)

# container_tree = a.create_routine_container(
#     "foo", largegroup, context=lib_container.context
# )

container_tree = my_builder.create_routine_container(
    # container_tree = my_builder.build(
    "foo",
    largegroup,
    context=lib_container.context,
    routine_container=F90KernelContainer,
    # routine_container=F90RoutineContainer,
)


lib_container.append(container_tree)
lib_container.build()


# for indent, line in lib_container.get_codelines():
#     print(indent * "  " + line)


my_library = F90Library("testlibrary")

assignments = {
    (VarInp, "real"): F90InputVariable(VarInp, "real", "inp_real", size=99),
    (VarInp, "imag"): F90InputVariable(VarInp, "imag", "inp_imag", size=99),
    (VarOut, "real"): F90OutputVariable(VarOut, "real", "out_real", size=99),
    (VarOut, "imag"): F90OutputVariable(VarOut, "imag", "out_imag", size=99),
}

my_builder.instructions_to_libroutine(
    "foofoo",
    largegroup,
    my_library,
    assignments,
    routine_container=F90RoutineContainer,
)

print(my_library._library_container)

my_library.build_all()

for indent, line in my_library.get_codelines():
    print(indent * "  " + line)


print("####")

print(
    my_library["foofoo"],
    my_library["foofoo"].library,
    my_library["foofoo"].name,
)
sys.exit()


"""
class Library:

    library container class
    [(builder, routine), ...]

    create_container_tree():
        create library container
        capture container
        include routines
        build captures

"""


# inside library (autocreate library if none given)
# Builder/BuildChain places CodeContainer from Instruction(s) in
# LibraryContainer, managed by Library via standardized routines

# Routine has instruction inside and information on InstructionVariables
# It is completely abstract and is based on instruction related objects.

# A Builder/Buildchain is loaded from a default file. Or created.

# It will either create code in an existing library and refer to that or
# create its own library (and refer to that) based on the routines name,
# instructions, properties (e.g. no_imag), ...

# the result is a LibRoutine object for every routine in a library, storing
# name and signature of the implemented piece of code. The library object is
# aware of the libroutine object and its dependencies to be able to generate
# a proper make file

# The libroutine object can be called in python, too, as it now is specific
# to a backend.
