"""
#autogenerated#header#do#not#modify############################################
#
# File:        instructionvar.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   06/02/2025
# Last Update: 24/02/2025, 16:14
# Version:     0.0.224
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from typing import Self, Dict

import weakref
from phoenix.keymap import KeyMap


class InstructionVariable:
    """Represents a variable in an instruction"""

    # every variable is derived as a subclass
    # every instance represents a certain entry in that class

    _name: None | str = None
    _dtype: None | str = None
    _count: int = 0

    def __init__(self, *params, offsets=None, history=None):
        if offsets is None:
            offsets = []
        if history is None:
            history = []
        self._offsets = offsets
        self._history = history
        self._params = []
        self.progress(*params)

    def __str__(self):
        dtype = self._dtype or "?"
        offset = (
            f"({'|'.join(map(str, self.offsets))})" if self.offsets else "O"
        )
        return f"<{self._name}({dtype})@{offset}{self.params}>"

    def __repr__(self):
        return f"<{self._name}>"

    @classmethod
    def new(cls, name, *, dtype=None):
        """create a new subclass from the name"""
        return type(name, (cls,), {"_name": name, "_dtype": dtype})

    def __init_subclass__(cls, name=None, dtype=None, **kwargs):
        cls._count += 1
        if name is not None:
            cls._name = name
        if dtype is not None:
            cls._dtype = dtype
        if cls._name is None:
            cls._name = f"ivar{cls._count}"
        if cls._dtype is None:
            cls._dtype = "f64"

    @property
    def name(self):
        """access name attribute"""
        return self._name

    @property
    def offsets(self):
        """access offsets"""
        return list(self._offsets)

    @property
    def history(self):
        """access offsets"""
        return list(self._history)

    @property
    def params(self):
        """access params"""
        return list(self._params)

    def copy(self):
        """return a copy"""
        return self.__class__(
            *self.params,
            offsets=list(self.offsets),
            history=list(self.history),
        )

    def progress(self, *params) -> Self:
        """progress params"""
        for param in params:
            self._params.append(param)
        return self

    def resolve(self) -> Self:
        """resolve num steps in param"""
        raise NotImplementedError("Must be implemented in subclass")

    def resolved(self):
        """return a resolved copy of self"""
        return self.copy().resolve()

    def apply_as_offset_to(self, other):
        """combine two variables"""
        return self.copy().progress(*other.history, *other.params)

    def __or__(self, other):
        return self.apply_as_offset_to(other)


class InstructionParameter(InstructionVariable):
    """A parameter is overwritten instead of extended"""

    def progress(self, *params) -> Self:
        """progress params"""
        if len(params) != 1:
            raise ValueError("Only one parameter allowed")
        self._history.extend(self._params)
        self._params = [params[0]]
        return self

    def resolve(self) -> Self:
        """resolve"""
        return self

    def resolved(self):
        """return a resolved copy of self"""
        return self.copy().resolve()

    def apply_as_offset_to(self, other):
        """combine two variables"""
        return self.resolved().progress(*other.params)


class KeyMapInstructionVariable(
    InstructionVariable, name=None, dtype=None, _exc=False
):
    """
    KeyMapInstructionVar

    Represents a variable that is based on a keymap.

    The main purpose is that there is a representation of input and output
    variables in instructions. They can be assigned to the ADAAs and have
    information on datatype and names.

    Especially for the keymap-version, the variable can be progressed when we
    move along nested keymaps, accumulating offsets.

    """

    _keymap: None | KeyMap = None

    def __init__(self, *params, offsets=None, history=None):
        self._pointer = weakref.ref(self._keymap)
        super().__init__(*params, offsets=offsets, history=history)
        # will resolve the key sequence params as seen from keymap

    def __init_subclass__(cls, keymap=None, **kwargs):
        super().__init_subclass__(**kwargs)
        if keymap is not None:
            cls._keymap = keymap
        if cls._keymap is None:
            raise ValueError("No keymap provided")

    # this simply repeats so the linter knows what's going on
    @classmethod
    def new(cls, name, keymap=None, *, dtype=None):
        """create a new subclass from the name"""
        return type(
            name,
            (cls,),
            {
                "_name": name,
                "_dtype": dtype,
                "_keymap": keymap,
            },
        )

    @property
    def keymap(self):
        """access keymap"""
        return self._keymap

    def resolve(self):
        """resolve num steps in param"""
        newpointer = self._pointer()
        for param in self._params:
            param = self._params.pop(0)
            assert newpointer is not None
            offset, newpointer = newpointer.goto(param)
            self._pointer = weakref.ref(newpointer)
            self._offsets.append(offset)
        self._pointer = weakref.ref(newpointer)
        return self


class InstructionEnvironment:
    """Defines an instruction environment where all known variables can be stored"""

    def __init__(self, **variables):
        self._variables: Dict[str, InstructionVariable] = variables

    def items(self):
        """iterate through dict-like items"""
        yield from self._variables.items()

    def as_dict(self):
        """display as a dictionary"""
        return {key: val for key, val in self.items()}

    def copy(self) -> InstructionEnvironment:
        """make a proper copy"""
        return self.__class__(
            **{key: var.copy() for key, var in self._variables.items()}
        )

    def merge(
        self, other_environment: InstructionEnvironment
    ) -> InstructionEnvironment:
        """merge an environment with another"""
        new_environment = self.copy()
        new_environment.update(**other_environment.as_dict())
        return new_environment

    def __or__(self, other: InstructionEnvironment) -> InstructionEnvironment:
        return self.merge(other)

    def update(self, **kwargs):
        """update the internal dictionary. Extend if possible"""
        for varname, variable in kwargs.items():
            if varname in self._variables:
                self._variables[varname] |= variable
            else:
                self._variables[varname] = variable
        return self

    def keys(self):
        """access keys of inner dict"""
        return self._variables.keys()

    def __getitem__(self, key):
        return self._variables[key]

    def __contains__(self, key):
        return key in self._variables
