"""
#autogenerated#header#do#not#modify############################################
#
# File:        instructions3.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/10/2024
# Last Update: 01/10/2024, 16:59
# Version:     0.0.441
#
#################################################end#of#autoheader#do#not#modify


"""


__doc__ = """
Instruction module description
==============================

"""

_ALL_INSTRUCTIONS = {}


def all_same(somelist):
    """checks if all elements in a list are the same, returns that element if
    true and raises exception when not"""
    if not somelist:
        raise ValueError("List is empty")
    first = somelist[0]
    assert first
    for other in somelist[1:]:
        if not first == other:
            raise ValueError("Not all elements are the same")
    return first


def segment_overlap(*segments_list):
    """get the list of overlapping entries in all lists"""
    common_segments = []
    for segments in zip(*segments_list):
        try:
            common = all_same(segments)
        except ValueError:
            break
        common_segments.append(common)
    return common_segments


class Instruction:
    """Base class for instructions"""

    _ftype = "instruction"

    @staticmethod
    def _get_itype_common_root(instruction_list):
        if len(instruction_list) == 0:
            return None
        segments_list = [instr.itype.split(".") for instr in instruction_list]
        return ".".join(segment_overlap(*segments_list))

    def __len__(self):
        return 1

    def __init__(self, *, itype=None):
        self._sort_key = None
        self._itype = itype

    def __init_subclass__(cls, ftype):
        # print("asd", cls._ftype, ftype, cls.__name__)
        ftype = ftype.replace(".", ":")
        cls._ftype += f".{ftype}"

    @property
    def instructions(self):
        """access instructions"""
        # break recursive loop
        yield self

    def unpack(self, recursive=True):
        """unpack the instruction"""
        # break recursive loop
        yield self

    @property
    def itype(self):
        """access read-only attribute itype"""
        return self._itype

    @property
    def ftype(self):
        """property for class level ftype attribute"""
        return self._ftype

    @property
    def sort_key(self):
        """access protected sort key attribute"""
        if self._sort_key is None:
            self._sort_key = self._get_sort_key()
        return self._sort_key

    def update_sort_key(self, function=None):
        """update the sort key"""
        self._sort_key = self._get_sort_key(function=function)

    def _get_default_sort_key(self):
        return tuple()

    def _get_sort_key(self, function=None):
        """get a sort key for the instruction, use default function if none is
        given"""
        if function is None:
            return self._get_default_sort_key()
        return function(self)

    def is_subtype(self, itype):
        """check if this instruction is a subtype of a reference.
        Returns true if this instruction's type can be derived from or is equal
        to the reference, i.e. the overlap of the instruction type is exactly
        the reference (which has at most the same length but all segments are
        identical)"""
        if isinstance(itype, Instruction):
            itype = itype.itype
        overlap = segment_overlap(*[self.itype.split("."), itype.split(".")])
        return overlap == itype.split(".")

    def __gt__(self, other):
        return self.itype > other.itype

    def __eq__(self, other):
        return self.itype == other.itype


class GenericInstruction(Instruction, ftype="generic"):
    """Generic instruction"""

    def __init__(self, **params):
        super().__init__(itype=self.ftype)
        self._params = params
        self._protected = True

    def __enter__(self):
        self._protected = False

    def __exit__(self, exc_type, exc_val, exc_tb):
        self._protected = True

    def __gt__(self, other):
        return self.sort_key > other.sort_key

    def __eq__(self, other):
        return self.sort_key == other.sort_key

    def _get_default_sort_key(self):
        return tuple(self.values())

    def keys(self):
        """dict like call to keys"""
        yield from self._params.keys()

    def items(self):
        """dict like call to items"""
        yield from self._params.items()

    def values(self):
        """dict like call to values"""
        yield from self._params.values()

    def __getitem__(self, key):
        return self.get(key)

    def __setitem__(self, key, value):
        self.set(key, value)

    @property
    def params(self):
        """access values as list"""
        return list(self.values())

    def get(self, *in_args):
        """mimic the get behaviour of dicts"""
        match in_args:
            case (key, default):
                return self._params.get(key, default)
            case (key,):
                return self._params.get(key)
            case _:
                raise RuntimeError("You shouldn't be here!")

    def set(self, key, value):
        """set a value, consider protection"""
        if self._protected:
            raise ValueError(
                f"cannot access protected value of key '{key}' for writing"
            )
        self._params[key] = value

    def to_dict(self, *keys, defaults=None):
        """get a dictionary from keys, filled with the values"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        return {
            key: self._params.get(key, defaults.get(key, None)) for key in keys
        }


class InstructionGroup(Instruction, ftype="group"):
    """Base class for instruction groups"""

    def __init__(self, instructions, itype=None):
        self._instructions = list(instructions)
        self._len = len(self._instructions)
        super().__init__(itype=itype)

    def __len__(self):
        return sum(len(instr) for instr in self.instructions)

    @property
    def itype(self):
        if self._itype is None:
            self._itype = InstructionGroup._get_itype_common_root(
                self._instructions
            )
        return self._itype

    def _update(self):
        self._len = len(self._instructions)
        self._itype = InstructionGroup._get_itype_common_root(
            self._instructions
        )

    @property
    def instructions(self):
        """access read-only attribute instructions as generator"""
        yield from self._instructions

    def unpack(self, recursive=True):
        """unpack all instructions, including inner groups"""
        for instr in self.instructions:
            if recursive:
                yield from instr.unpack(recursive=True)
            else:
                yield instr

    def flatten(self):
        """flatten instructions, which will unpack all inner groups"""
        return InstructionGroup(list(self.unpack()), itype=self._itype)

    def sorted(self, function=None):
        """return a sorted version. Sort function is optional. Does not
        overwrite sort keys. If no function is given, the default
        sort keys are used"""
        if function is None:
            return InstructionGroup(
                list(sorted(self.instructions)), itype=self._itype
            )
        sorted_instructions = sorted(
            [(function(instr), instr) for instr in self.instructions]
        )
        return InstructionGroup(
            [instr for _, instr in sorted_instructions], itype=self._itype
        )

    def grouped(self, function=None, size=None, number=None):
        """subdivide the current instruction group into smaller groups"""

        match (function, size, number):
            case (function, None, None):
                assert callable(function)
                return self.group_by_key(function)

            case (None, size, None):
                assert isinstance(size, int)
                return self.group_to_size(size)

            case (None, None, number):
                assert isinstance(number, int)
                return self.group_to_batches

            case _:
                raise ValueError(
                    "only one of 'function', 'size' and 'number' can be set"
                )

    def group_by_key(self, function):
        """generate groups by a key generating function"""
        groups = {}
        for instr in self.instructions:
            group_id = function(instr)
            if group_id not in groups:
                groups[group_id] = []
            groups[group_id].append(instr)
        return InstructionGroup(
            [
                InstructionGroup(group, itype=self._itype)
                for group in groups.values()
            ],
            itype=self._itype,
        )

    def group_to_batches(self, num_batches):
        """subdivide the group into a number of batches.
        Does not conserve continuousity of data"""
        groups = [[] for _ in num_batches]
        for num, instr in enumerate(self.instructions):
            groups[num % num_batches].append(instr)
        return InstructionGroup(
            [InstructionGroup(group) for group in groups], itype=self._itype
        )

    def group_to_size(self, max_size):
        """split the instructions into groups of a certain (maximum) size"""
        group = []
        collect = []
        for instr in self.instructions:
            if len(group) >= max_size:
                collect.append(InstructionGroup(group, itype=self._itype))
                group = []
            group.append(instr)
        if group:
            collect.append(InstructionGroup(group, itype=self._itype))
        return InstructionGroup(collect, itype=self._itype)


if __name__ == "__main__":
    x = GenericInstruction(foo="bar")
    print(x.params)
    print(x.ftype)

    class SpecificInstruction(GenericInstruction, ftype="specific"):
        pass

    class OtherSpecificInstruction(GenericInstruction, ftype="otherspecific"):
        pass

    class MoreSpecificInstruction(SpecificInstruction, ftype="more"):
        pass

    y = SpecificInstruction(foo="foo")
    z = OtherSpecificInstruction(foo="bar")
    k = MoreSpecificInstruction(foo="baz")
    print(y.ftype)

    print(InstructionGroup._get_itype_common_root([z, k]))

    foo = InstructionGroup([y, k])
    print(foo.ftype)
    print(foo._itype)
    print(foo.itype)
    print(foo._itype)

    print(y.is_subtype(x))
    print(y.is_subtype(y))
    # print(foo.is_subtype(y))

    print()
    bar = InstructionGroup(
        [
            foo,
            foo,
        ]
    )
    for instruction in bar.instructions:
        print(instruction)

    print()

    baz = bar.flatten()
    foo = baz.grouped(lambda x: x["foo"])
    print([len(instr) for instr in foo.instructions])
    bar = baz.group_to_size(5)
    print([len(instr) for instr in bar.instructions])

    for instruction in baz.instructions:
        print(instruction)

    test = InstructionGroup(list(baz.unpack()) + [z, z])

    print(len(test))
    for ins in test.instructions:
        print(ins)

    for ins in foo.unpack(recursive=False):
        print(ins, len(ins))
