"""
#autogenerated#header#do#not#modify############################################
#
# File:        instruction3.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/10/2024
# Last Update: 06/03/2025, 13:03
# Version:     0.0.2259
#
#################################################end#of#autoheader#do#not#modify


"""


from __future__ import annotations

__doc__ = """
Instruction module description

Important note: we distinguish the ftype and the itype of an instruction
instance. While the ftype is the functional type of the instruction instance
such as a specific kind of instruction, a group or else, the itype refers to
how it is applied on data.

Example: An InstructionGroup is an Instruction that has ftype 'group' but itype
can be 'instruction.someinstruction', which defines the greatest common
denominator of instruction types within the group, i.e. how it is to be applied
to data.
"""

from typing import Any, List, Dict, Tuple
import weakref

from phoenix._aux import segment_overlap
from phoenix.keymap import Key, KeyMap
from phoenix.fgen.instructionvar import (
    InstructionVariable,
    KeyMapInstructionVariable,
    InstructionEnvironment,
    SymbolicInstructionVariable,
)

# class _PartialFormatDict(dict):
#     """allows partial formatting of strings"""

#     def __setitem__(self, key, value):
#         if not isinstance(key, str):
#             raise ValueError("Key must be a string")
#         return super().__setitem__(key, value)

#     def __getitem__(self, key):
#         if key in self:
#             return super().__getitem__(key)
#         return "{" + key + "}"


###############################################################################
#
#  .oPYo.       .oo  .oPYo.  .oPYo.
#  8   `8      .P 8  8       8.
# o8YooP'     .P  8  `Yooo.  `boo
#  8   `b    oPooo8      `8  .P
#  8    8   .P    8       8  8
#  8oooP'  .P     8  `YooP'  `YooP'
# :......: ..:::::.. :.....: :.....:
# :::::::: ::::::::: ::::::: :::::::
# :::::::: ::::::::: ::::::: :::::::
###############################################################################


class Instruction:
    """Base class for instructions"""

    _ftype = "instruction"
    _obj_id_count = 0

    def _get_obj_id(self):
        self.__class__._obj_id_count += 1
        return f"{self._ftype}#{self.__class__._obj_id_count}"

    def _instruction_hash(self, generating) -> int:
        """
        generate a hash from the generating input

        :param generating: something hashable
        :returns: a valid hash
        """
        return hash(generating)

    @staticmethod
    def _get_itype_common_root(instruction_list: List[Instruction]) -> str:
        """
        get the common root amongst string that are subdividable by '.'

        :param instruction_list: a list of instructions to be processed
        :returns: the greatest common root amongst all instructions.
        """
        if len(instruction_list) == 0:
            return ""
        segments_list = [instr.itype.split(".") for instr in instruction_list]
        latest_parent_itype = ".".join(segment_overlap(*segments_list))
        return latest_parent_itype

    def __str__(self):
        return f"<{self.identifier}>"

    def __repr__(self):
        return f"<{self.identifier}>"

    def __len__(self) -> int:
        """
        Return the length of the instruction

        :returns: instruction length
        """
        return 1

    def __init__(self, *, itype=None):
        self._sort_key = None
        self._itype = itype
        self._obj_id = self._get_obj_id()
        self._protected = True

    def __init_subclass__(cls, ftype: str):
        """
        init the subclass.

        :param ftype: the functional type of the subclass
        """
        ftype = ftype.replace(".", ":")
        cls._obj_id_count = 0
        cls._ftype += f".{ftype}"

    def __enter__(self):
        """
        enter an environment, where the write-protection is lifted
        """
        self._protected = False
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """
        exit the environment for write access, protection reenabled
        """
        self._protected = True

    def checksum(self) -> int:
        """
        Get a checksum object that can be fed to a hash function.
        Used to identify instructions being identical.
        """
        test_tuple = (
            self.identifier,
            self._itype,
            self._ftype,
        )
        return self._instruction_hash(test_tuple)

    @property
    def identifier(self) -> str:
        """
        get a unique identifier for the instruction.

        This identifier is typically composed from the ftype and a
        number that increases within the subclass
        :returns: identifier
        """
        return self._obj_id

    @property
    def instructions(self):
        """
        Iterate among the instructions. No offsets or anything applied, not recursion.
        """
        yield self

    # pylint: disable=unused-argument
    def unpack(self, recursive: bool | int = True, environment=None):
        """
        Unpacking goes through the instructions but interprets them wrt an environment.

        If recursive is set to an integer, this is the level of recursion (0=no unpacking, only
        self). If recursive is set to true, there is no level assumed an infinite unpacking is
        performed (default).
        Environments provide offsets, local definitions and special groupings.

        :param environment: optional environment.
        """
        for is_leaf, ref, ref_env in self.walk(
            recursive=recursive,
            environment=environment,
            include_groups=False,
        ):
            if is_leaf:
                yield ref.apply_environment(ref_env)

    def walk(
        self,
        environment=None,
        recursive: bool | int = True,
        include_groups=True,
    ):
        """
        walk the instruction tree. A generator that yields information on
        self, the environment and a flag whether it is a leaf
        """
        if environment is None:
            environment = InstructionEnvironment()
        if isinstance(recursive, int):
            if recursive == 0:
                return
        yield True, self, environment

    def to_dict(self, *keys, defaults: dict | None = None):
        """get a dictionary from keys, filled with the values"""
        raise NotImplementedError("Must be implemented in subclass")

    # pylint: enable=unused-argument

    @property
    def itype(self):
        """access read-only attribute itype"""
        return self._itype

    @property
    def ftype(self):
        """property for class level ftype attribute"""
        return self.__class__._ftype

    @property
    def sort_key(self):
        """access protected sort key attribute"""
        if self._sort_key is None:
            self._sort_key = self._get_sort_key()
        return self._sort_key

    def update_sort_key(self, function=None):
        """update the sort key"""
        self._sort_key = self._get_sort_key(function=function)

    def _get_default_sort_key(self):
        return tuple()

    def _get_sort_key(self, function=None):
        """get a sort key for the instruction, use default function if none is
        given"""
        if function is None:
            return self._get_default_sort_key()
        return function(self)

    def is_subtype(self, itype):
        """check if this instruction is a subtype of a reference.
        Returns true if this instruction's type can be derived from or is equal
        to the reference, i.e. the overlap of the instruction type is exactly
        the reference (which has at most the same length but all segments are
        identical)"""
        if isinstance(itype, Instruction):
            itype = itype.itype
        overlap = segment_overlap(*[self.itype.split("."), itype.split(".")])
        return overlap == itype.split(".")

    def __gt__(self, other):
        return self.itype > other.itype

    def __eq__(self, other):
        return self.itype == other.itype

    def __deepcopy__(self, memo=None):
        raise NotImplementedError("subclasses must implement this method")

    def deepcopy(self, memo=None):
        """
        Create a proper deep copy of the object.
        To ensure compatibility with traditional copy.copy, I go with a dict of
        weakref.refs instead of using weakref.WeakValueDictionary. Keep in mind
        that weakref.ref objects must be called to be properly referenced.
        """
        if memo is None:
            memo = {}
        # keep the linter happy...
        # pylint: disable=unnecessary-dunder-call
        return self.__deepcopy__(memo=memo)
        # pylint: enable=unnecessary-dunder-call

    def _apply_environment(
        self,
        environment: InstructionEnvironment,
        memo: dict,
    ) -> Instruction:
        """actually apply the environment"""
        raise NotImplementedError("Must be implemented in subclass")

    def apply_environment(
        self,
        environment: InstructionEnvironment | None = None,
        *,
        memo=None,
    ) -> Instruction:
        """
        Apply an environment to the instruction. User call, handles memo and environment initialization.
        """
        if environment is None:
            environment = InstructionEnvironment()
        if memo is None:
            memo = {}
        if (id(environment), id(self)) in memo:
            if (memorized := memo[(id(environment), id(self))]()) is not None:
                return memorized
        env_applied = self._apply_environment(environment, memo=memo)
        memo[(id(environment), id(self))] = weakref.ref(env_applied)
        return env_applied


###############################################################################
#
# .oPYo.  .oPYo.  o    o  .oPYo.   .oPYo.  o  .oPYo.
# 8    8  8.      8b   8  8.       8   `8  8  8    8
# 8       `boo    8`b  8  `boo    o8YooP'  8  8
# 8   oo  .P      8 `b 8  .P       8   `b  8  8
# 8    8  8       8  `b8  8        8    8  8  8    8
# `YooP8  `YooP'  8   `8  `YooP'   8    8  8  `YooP'
# :....8  :.....: ..:::.. :.....: :..:::.. .. :.....:
# :::::8  ::::::: ::::::: ::::::: :::::::: :: :::::::
# :::::.. ::::::: ::::::: ::::::: :::::::: :: :::::::
###############################################################################


class GenericInstruction(Instruction, ftype="generic"):
    """Generic instruction.

    At this point the params dictionary is introduced. Multiple aliases are
    supported for flexible entry access without creating duplicates.
    """

    _alias: dict[str, str] = {}

    def __init__(self, itype=None, **params):
        if itype is None:
            itype = self.ftype
        super().__init__(itype=itype)
        # itype of generic instructions is by default the ftype
        self._params = params

    def __gt__(self, other):
        return self.sort_key > other.sort_key

    def __eq__(self, other):
        return self.sort_key == other.sort_key

    def _get_default_sort_key(self):
        return tuple(self.values())

    def keys(self):
        """dict like call to keys"""
        yield from self._params.keys()

    def items(self):
        """dict like call to items"""
        yield from self._params.items()

    def values(self):
        """dict like call to values"""
        yield from self._params.values()

    def __getitem__(self, key):
        if key in self._params:
            return self._params[key]
        return self._from_alias(key)

    def __setitem__(self, key, value):
        self.set(key, value)

    @classmethod
    def set_alias(cls, alias, reference):
        """add an alias to the class"""
        cls._alias[alias] = reference

    def checksum(self):
        test_tuple = (
            *super().checksum(),
            tuple(self.params),
        )
        return test_tuple

    @property
    def params(self):
        """access values as list"""
        return tuple(self.values())

    def get(self, *in_args):
        """mimic the get behaviour of dicts"""
        match in_args:
            case (key, default):
                if key in self._params:
                    return self._params[key]
                try:
                    return self._from_alias(key)
                except KeyError:
                    return default
                return default
            case (key,):
                if key in self._params:
                    return self._params[key]
                return self._from_alias(key)
            case _:
                raise ValueError(
                    "get requires a key and an optional default value to return"
                )

    def set(self, key, value):
        """set a value, consider protection"""
        if self._protected:
            raise ValueError(
                f"cannot access protected value of key '{key}' for writing"
            )
        self._params[key] = value

    def to_dict(self, *keys, defaults: dict | None = None):
        """get a dictionary from keys, filled with the values"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        data_dict = {}  # _PartialFormatDict
        if keys:
            data_dict.update(
                {key: self.get(key, defaults.get(key, None)) for key in keys}
            )
        else:
            data_dict.update(
                {
                    key: self.get(key, defaults.get(key, None))
                    for key in self.keys()
                }
            )
        return data_dict

    def to_tuple(self, *keys, defaults: dict | None = None):
        """get a data tuple from keys in the order the keys are requested"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        if keys:
            return tuple(
                self.get(key, defaults.get(key, None)) for key in keys
            )
        return tuple(
            self.get(key, defaults.get(key, None)) for key in self.keys()
        )

    def _from_alias(self, key):
        print(f"look up potential alias {key} in {self.__class__.__name__}")
        if key in self.__class__._alias:
            # don't call self._params here, so alias can chain
            return self[self.__class__._alias[key]]
        raise KeyError(f"Key '{key}' not found in dict nor alias map")

    def __deepcopy__(self, memo=None):
        if memo is None:
            memo = {}
        if id(self) in memo:
            return memo[id(self)]()  # beware, must be called due to weakref
        copied = self.__class__.from_dict(self._params)
        memo[id(self)] = weakref.ref(copied)
        return copied

    @classmethod
    def from_dict(cls, params):
        """
        generate a new class instance from a dictionary.
        Consider renaming here
        """
        return cls(**params)


class KeyMapInstruction(GenericInstruction, ftype="kmap"):
    """Represents an Expression"""

    def _apply_environment(
        self,
        environment: InstructionEnvironment,
        memo: dict,
    ) -> Instruction:
        """actually apply the environment"""
        modified_params = {}
        for key, val in self._params.items():
            if isinstance(val, InstructionVariable):
                if val.name in environment:
                    modified_params[key] = environment[val.name] | val
                else:
                    modified_params[key] = val
            else:
                modified_params[key] = val
        return self.__class__.from_dict(modified_params)


###############################################################################
#
# .oPYo.   .oPYo.  .oPYo.  o    o   .oPYo.  .oPYo.
# 8    8   8   `8  8    8  8    8   8    8  8
# 8       o8YooP'  8    8  8    8  o8YooP'  `Yooo.
# 8   oo   8   `b  8    8  8    8   8           `8
# 8    8   8    8  8    8  8    8   8            8
# `YooP8   8    8  `YooP'  `YooP'   8       `YooP'
# :....8  :..:::.. :.....: :.....: :..::::: :.....:
# :::::8  :::::::: ::::::: ::::::: :::::::: :::::::
# :::::.. :::::::: ::::::: ::::::: :::::::: :::::::
###############################################################################


class InstructionGroup(Instruction, ftype="group"):
    """Base class for instruction groups"""

    # TODO
    # I consider an allow_parallel keyword, that enables or disables the
    # parallel execution of content.

    # Is it required?
    # Operations that enforce an order should maybe be executed in separate
    # subroutines.

    # Is it transferable?
    # Will an operation, that should be parallelized on a gpu will be properly
    # parallelized on a cpu, where blocks might be better?

    # Is it useful?
    # Most definitely, as we have some say in the later code design.

    # How would I do it?
    # Right now I think of parallelization levels, that can be chosen and even
    # varied in the implementation step. A single operation parallelization
    # could have a higher level, that we only enable on GPUs.

    def __init__(self, instructions, itype=None, **params):
        self._instructions = list(instructions)
        self._len = len(self._instructions)
        self._params = params
        if itype is None:
            itype = InstructionGroup._get_itype_common_root(self._instructions)
        super().__init__(itype=itype)

    def __len__(self):
        return sum(len(instr) for instr in self.instructions)

    def __deepcopy__(self, memo=None):
        if memo is None:
            memo = {}
        if id(self) in memo:
            return memo[id(self)]()  # beware, must be called due to weakref
        copied_instructions = []
        for instr in self._instructions:
            if id(instr) in memo:
                copied_instr = memo[id(instr)]()
            else:
                copied_instr = instr.deepcopy(memo)
            copied_instructions.append(copied_instr)
        copied_group = self.__class__(
            copied_instructions, itype=self.itype, **self._params
        )
        memo[id(self)] = weakref.ref(copied_group)
        return copied_group

    @property
    def itype(self):
        return self._itype

    @property
    def instructions(self):
        """access read-only attribute instructions as generator"""
        yield from self._instructions

    def walk(
        self,
        environment=None,
        recursive: bool | int = True,
        include_groups=True,
    ):
        """
        walk the instruction tree. A generator that yields information on
        self, the environment and a flag whether it is a leaf
        """
        if environment is None:
            environment = InstructionEnvironment()
        if include_groups:
            if recursive is False or recursive:
                yield False, self, environment
        if recursive is True:
            for instr in self.instructions:
                yield from instr.walk(
                    environment=environment,
                    recursive=True,
                    include_groups=include_groups,
                )
        elif recursive >= 1:
            for instr in self.instructions:
                yield from instr.walk(
                    environment=environment,
                    recursive=recursive - int(include_groups),
                    include_groups=include_groups,
                )

    def flatten(self):
        """replace content by flattened instructions, which will unpack all inner groups"""
        return self.__class__(list(self.unpack()))

    def sorted(self, ordering_function=None, sort_function=None):
        """return a sorted version. Sort function is optional. Does not
        overwrite sort keys. If no function is given, the default
        sort keys are used"""
        if sort_function is None:
            sort_function = sorted
        if ordering_function is None:
            return self.__class__(
                list(sort_function(self.instructions)), itype=self._itype
            )
        sorted_instructions = sort_function(
            [(ordering_function(instr), instr) for instr in self.instructions]
        )
        return self.__class__(
            [instr for _, instr in sorted_instructions], itype=self._itype
        )

    def grouped(self, function=None, size=None, number=None):
        """subdivide the current instruction group into smaller groups"""

        match (function, size, number):
            case (function, None, None):
                assert callable(function)
                return self.grouped_by_key(function)

            case (None, size, None):
                assert isinstance(size, int)
                return self.grouped_to_size(size)

            case (None, None, number):
                assert isinstance(number, int)
                return self.grouped_to_batches

            case _:
                raise ValueError(
                    "only one of 'function', 'size' and 'number' can be set"
                )

    def grouped_by_key(self, function, group_type=None, subgroup_type=None):
        """generate groups by a key generating function"""
        groups: Dict[Any, List[Instruction]] = {}
        for instr in self.instructions:
            group_id = function(instr)
            if group_id not in groups:
                groups[group_id] = []
            groups[group_id].append(instr)
        if group_type is None:
            group_type = self.__class__
        if subgroup_type is None:
            subgroup_type = self.__class__
        return group_type(
            [
                subgroup_type(group, itype=self._itype)
                for group in groups.values()
            ],
            itype=self._itype,
        )

    def grouped_to_batches(self, batches, group_type=None, subgroup_type=None):
        """subdivide the group into a number of batches.
        Does not conserve continuousity of data"""
        groups: List[List[Instruction]] = [[] for _ in range(batches)]
        if group_type is None:
            group_type = self.__class__
        if subgroup_type is None:
            subgroup_type = self.__class__
        for num, instr in enumerate(self.instructions):
            groups[num % batches].append(instr)
        return group_type(
            [subgroup_type(group) for group in groups], itype=self._itype
        )

    def grouped_to_size(self, max_size, group_type=None, subgroup_type=None):
        """split the instructions into groups of a certain (maximum) size"""
        group: List[Instruction] = []
        collect: List[List[Instruction]] = []
        if group_type is None:
            group_type = self.__class__
        if subgroup_type is None:
            subgroup_type = self.__class__
        for instr in self.instructions:
            if len(group) >= max_size:
                collect.append(subgroup_type(group, itype=self._itype))
                group = []
            group.append(instr)
        if group:
            collect.append(subgroup_type(group, itype=self._itype))
        return group_type(collect, itype=self._itype)

    def _apply_environment(
        self, environment: InstructionEnvironment, memo: dict
    ) -> Instruction:
        return self.__class__(
            [
                instr.apply_environment(environment, memo=memo)
                for instr in self.instructions
            ],
            itype=self.itype,
        )


######################################################################################
#
# .oPYo.  o    o  o     o  o   .oPYo.  .oPYo.  o    o  o     o  .oPYo.  o    o  ooooo
# 8.      8b   8  8     8  8   8   `8  8    8  8b   8  8b   d8  8.      8b   8    8
# `boo    8`b  8  8     8  8  o8YooP'  8    8  8`b  8  8`b d'8  `boo    8`b  8    8
# .P      8 `b 8  `b   d'  8   8   `b  8    8  8 `b 8  8 `o' 8  .P      8 `b 8    8
# 8       8  `b8   `b d'   8   8    8  8    8  8  `b8  8     8  8       8  `b8    8
# `YooP'  8   `8    `8'    8   8    8  `YooP'  8   `8  8     8  `YooP'  8   `8    8
# :.....: ..:::.. :::..::: .. :..:::.. :.....: ..:::.. ..::::.. :.....: ..:::.. ::..::
# ::::::: ::::::: :::::::: :: :::::::: ::::::: ::::::: :::::::: ::::::: ::::::: ::::::
# ::::::: ::::::: :::::::: :: :::::::: ::::::: ::::::: :::::::: ::::::: ::::::: ::::::
######################################################################################


###############################################################################
#
# PARENT CLASS ENVIRONMENT
# ========================


class EnvironmentInstruction(Instruction, ftype="environment"):
    """Within this environment, variables are provided, renamed or offsetted"""

    def __init__(self, content, *, environment=None, itype=None, **params):
        if itype is None:
            itype = content.itype
        super().__init__(itype=itype)
        if not isinstance(content, InstructionGroup):
            raise TypeError("content must be an InstructionGroup")
        if not isinstance(content, Instruction):
            raise TypeError(
                "content of environment must be of type instruction"
            )
        self._content = content
        self._environment = InstructionEnvironment()
        if environment is not None:
            self._environment.update(**environment)
        self._params = params

    @property
    def instructions(self):
        """access instructions"""
        yield from self._content.instructions

    def __deepcopy__(self, memo=None):
        if memo is None:
            memo = {}
        copied_content = self._content.deepcopy(memo=memo)
        return self.__class__(
            copied_content,
            environment={
                key: (
                    val.deepcopy(memo=memo)
                    if isinstance(val, Instruction)
                    else val
                )
                for key, val in self._environment.items()
            },
            itype=self.itype,
            **self._params,
        )

    def _apply_environment(
        self, environment: InstructionEnvironment, memo: dict
    ) -> Instruction:
        combined_environment = environment.merge(self._environment)
        # environments are replaced by their transformed content
        return self._content.apply_environment(combined_environment, memo=memo)

    def walk(
        self,
        environment=None,
        recursive: bool | int = True,
        include_groups=True,
    ):
        """
        walk the instruction tree. A generator that yields information on
        self, the environment and a flag whether it is a leaf
        """
        # an environment does not count as recursive step!!
        if environment is None:
            environment = InstructionEnvironment()
        combined_environment = environment.merge(self._environment)
        yield from self._content.walk(
            environment=combined_environment,
            recursive=recursive,
            include_groups=include_groups,
        )


###############################################################################
#
# OFFSET ENVIRONMENT
# ==================


class OffsetEnvironmentInstruction(EnvironmentInstruction, ftype="offset"):
    """
    Within this environment, variables are offsetted
    """

    # TODO
    # Unpack (and therefore indirectly flatten) needs to consider offsets!

    # Contains
    # - Instructions to be offsetted

    # requires:
    # - value of offset
    # - variable mapping if names change


###############################################################################
#
# VARIATION ENVIRONMENT
# =====================


class VariationEnvironmentInstruction(
    OffsetEnvironmentInstruction, ftype="variation"
):
    """
    A variation is a special kind of offset that implies, that data contains copies
    that are addressable via offsets and independent and non-overlapping. E.g. a state
    operator interacts with several different sets of dynamic, but these different
    versions do not interact anywhere, implying some wiggle room for safe parallelization
    """

    # TODO
    # Unpack (and therefore indirectly flatten) needs to consider offsets!

    # Contains
    # - Instructions to be offsetted

    # requires:
    # - value of offset
    # - variable mapping if names change


###############################################################################
#
# SUBROUTINE ENVIRONMENT
# ======================


class SubroutineEnvironmentInstruction(
    EnvironmentInstruction, ftype="subroutine"
):
    """
    SubroutineGroup

    suggests that upon implementation these instructions are grouped in a
    subroutine
    """

    def __init__(self, operations, inp_variables, out_variables, itype=None):
        super().__init__(operations, itype=itype)
        self._inp_variables = inp_variables
        self._out_variables = out_variables

    @property
    def inp_variables(self):
        return tuple(self._inp_variables)

    @property
    def out_variables(self):
        return tuple(self._out_variables)

    def __deepcopy__(self, memo=None):
        copied_environment = super().__deepcopy__(memo=memo)
        copied_environment._inp_variables = tuple(self.inp_variables)
        copied_environment._inp_variables = tuple(self.inp_variables)


###############################################################################
#
# PARALLEL ENVIRONMENT GROUPS
# ===========================


class MapInstructionGroup(InstructionGroup, ftype="map"):
    """
    Within this environment, Environment groups (e.g. OffsetGroups) are applied
    to an instructiongroup that is then executed from within every environment.
    """

    # TODO
    # Decide what happens to instructions in environment when map is applied
    # consider pre-map and post-map operations

    def __init__(self, environments, mapped, itype=None):
        super().__init__(environments, itype=itype)
        self._mapped = mapped


###############################################################################
#
# VARIATION ENVIRONMENT
# =====================


# class VariationGroup(InstructionGroup, ftype="variation"):
#     """Within this environment, variables are offsetted"""

#     # TODO

#     # Contains
#     # - Multiple Instruction groups accessible via keywords
#     # - a default choice, e.g. the first submitted group

#     # Functionality
#     # User can select another keyword to alter the chosen instruction group


###############################################################################
#
# .oPYo.   .oPYo.  .oPYo.  .oPYo.  o   ooooo  o  .oPYo.
# 8        8    8  8.      8    8  8   8      8  8    8
# `Yooo.  o8YooP'  `boo    8       8  o8oo    8  8
#     `8   8       .P      8       8   8      8  8
#      8   8       8       8    8  8   8      8  8    8
# `YooP'   8       `YooP'  `YooP'  8   8      8  `YooP'
# :.....: :..::::: :.....: :.....: .. :..:::: .. :.....:
# ::::::: :::::::: ::::::: ::::::: :: ::::::: :: :::::::
# ::::::: :::::::: ::::::: ::::::: :: ::::::: :: :::::::
###############################################################################


###############################################################################
#
# POLYNOMIAL INSTRUCTION
# ======================


class PolynomialInstruction(KeyMapInstruction, ftype="polynomial"):
    """
    Base class for polynomial instructions
    y[key_tgt0] = c0 x[key_tgt0]^0 + c1 x[key_tgt0]^1 + c2 x[key_tgt0]^2 + ...
    """

    def __init__(
        self,
        tgt0: InstructionVariable,
        src0: InstructionVariable,
        *coeffs,
        **other,
    ):
        degree = len(coeffs) - 1
        assert isinstance(tgt0, InstructionVariable)
        assert isinstance(src0, InstructionVariable)
        dcoeffs: dict[str, Any] = {}
        for exp, coeff in enumerate(coeffs):
            dcoeffs[f"coeff_x{exp}"] = coeff
        super().__init__(
            tgt0=tgt0,
            src0=src0,
            degree=degree,
            **dcoeffs,
            itype=self.ftype,
        )


###############################################################################
#
# AFFINE INSTRUCTION
# ==================


class AffineOperationInstruction(PolynomialInstruction, ftype="affine"):
    """y[key_tgt0] = a * x[key_src] + b type instruction"""

    def __init__(self, tgt0, src0, alpha, beta):
        assert isinstance(tgt0, InstructionVariable)
        assert isinstance(src0, InstructionVariable)
        super().__init__(tgt0, src0, beta, alpha)

    @classmethod
    def from_dict(cls, params):
        """
        generate a new class instance from a dictionary.
        Consider renaming here
        """
        return cls(
            params["tgt0"],
            params["src0"],
            params["coeff_x1"],
            params["coeff_x0"],
        )


###############################################################################
#
# LINEAR INSTRUCTION
# ==================


class LinearOperationInstruction(AffineOperationInstruction, ftype="linear"):
    """y[key_tgt0] = a * x[key_src] type instruction"""

    def __init__(self, tgt0, src0, alpha):
        assert isinstance(tgt0, InstructionVariable)
        assert isinstance(src0, InstructionVariable)
        super().__init__(tgt0, src0, alpha, 0.0)

    @classmethod
    def from_dict(cls, params):
        """
        generate a new class instance from a dictionary.
        Consider renaming here
        """
        return cls(
            params["tgt0"],
            params["src0"],
            params["coeff_x1"],
        )


###############################################################################
#
# TESTING
# =======

if __name__ == "__main__":
    ltl_km = KeyMap(name="little")
    ltl_km.entry("key1")
    ltl_km.entry("key2")
    ltl_km.entry("key3")

    big_km = KeyMap(name="big")
    big_km.link("foo0", ltl_km)
    big_km.link("foo1", ltl_km)
    big_km.link("foo2", ltl_km)
    big_km.link("foo3", ltl_km)
    big_km.link("foo4", ltl_km)

    big_km.update()
    print(list(big_km.keys()))

    VarInp = KeyMapInstructionVariable("input1", keymap=big_km)
    VarOut = KeyMapInstructionVariable("output1", keymap=big_km)

    VarInpInner = KeyMapInstructionVariable("input1", keymap=ltl_km)
    VarOutInner = KeyMapInstructionVariable("output1", keymap=ltl_km)

    test_instructions_inner = InstructionGroup(
        [
            LinearOperationInstruction(
                VarOutInner("key1"), VarInpInner("key3"), 1.0
            ),
            LinearOperationInstruction(
                VarOutInner("key2"), VarInpInner("key2"), 1.0
            ),
            LinearOperationInstruction(
                VarOutInner("key3"), VarInpInner("key1"), 1.0
            ),
        ]
    )
    test_instructions = InstructionGroup(
        [
            OffsetEnvironmentInstruction(
                test_instructions_inner,
                environment={
                    "input1": VarInp(f"foo{val}"),
                    "output1": VarOut(f"foo{val}"),
                },
            )
            for val in range(5)
        ]
    )

    for instruction in test_instructions.instructions:
        print(instruction._obj_id)

    print(SubroutineEnvironmentInstruction._obj_id_count)
    print(PolynomialInstruction._obj_id_count)
    print(LinearOperationInstruction._obj_id_count)
    print(AffineOperationInstruction._obj_id_count)

    print(VarInp._name)

    print(VarInp("foo1", "key2"))
    # print(VarInp("foo1", "key2").resolve())

    print("Distinction")

    print(len(test_instructions))
    print(len(test_instructions.flatten()))

    import sys

    print("unpack, 0 recursive")
    for isleaf, el, env in test_instructions.walk(recursive=0):
        if isleaf:
            env_el = el.apply_environment(env)
            print(
                "\t",
                env_el.identifier,
                env_el["tgt0"].offset,
                env_el["src0"].offset,
                env_el["coeff_x1"],
            )
        else:
            print("\t", el, env)

    print("unpack, non recursive")
    for isleaf, el, env in test_instructions.walk(recursive=False):
        if isleaf:
            env_el = el.apply_environment(env)
            print(
                "\t",
                env_el.identifier,
                env_el["tgt0"].offset,
                env_el["src0"].offset,
                env_el["coeff_x1"],
            )
        else:
            print("\t", el, env)

    print("unpack, 1 recursive")
    for isleaf, el, env in test_instructions.walk(recursive=1):
        if isleaf:
            env_el = el.apply_environment(env)
            print(
                "\t",
                env_el.identifier,
                env_el["tgt0"].offset,
                env_el["src0"].offset,
                env_el["coeff_x1"],
            )
        else:
            print("\t", el, env)

    print("unpack, 2 recursive")
    for isleaf, el, env in test_instructions.walk(recursive=2):
        if isleaf:
            env_el = el.apply_environment(env)
            print(
                "\t",
                env_el.identifier,
                env_el["tgt0"].offset,
                env_el["src0"].offset,
                env_el["coeff_x1"],
            )
        else:
            print("\t", el, env)

    print("unpack, True recursive")
    for isleaf, el, env in test_instructions.walk(recursive=True):
        if isleaf:
            env_el = el.apply_environment(env)
            print(
                "\t",
                env_el.identifier,
                env_el["tgt0"].offset,
                env_el["src0"].offset,
                env_el["coeff_x1"],
            )
        else:
            print("\t", el, env)

    some_value_x = SymbolicInstructionVariable("offset")
    some_value_x.associate_variable("x")

    print("unpack, True recursive, extra tests on variable variables")
    for el in test_instructions.unpack(recursive=True):
        print("\t", el["tgt0"] | some_value_x)

    sys.exit(0)

    print(
        """
    Strategy
    ========

    Comment 25/02/10: partly outdated.

    We introduce the variable data type to remember the variable name and the
    proper way to access it. At the instruction level, this access is not
    specific to a backend yet.

    A variable is represented by its own subclass of the proper parent class.
    Loops over offset variations can be realized by resolving the accumulated
    param values that refer to KeyMap Keys in case of a
    KeyMapInstructionVariable. They can be translated into an offset. 

    Upon application, this offset can be included into a loop variable, that
    can be used symbolically.

    This loop variable can be hard coded in the instruction group. For example,
    the GPU implementation might not need it, and at instruction level I don't
    want the structure to be too specific.

    My dream-procedure:
    We introduce a offset-repeat instruction, where a single instructiongroup
    is repeated for multiple offsets. This instruction group can take offset
    configurations. Right now I am not sure if these offset configurations
    should be a list of offsets passed to a special group, or just repetitions
    of a special apply-offset command and some code magic. Or maybe a special
    group and a special operation that simply says "repeat".

    As of now I think, that an OffsetApplyInstruction in a RepeatGroup is the
    right way to go. Upon evaluation, the Instruction group to be offsetted
    will be recognized by ID once it is repeated a couple times. In this case,
    OffsetApply should group automatically. At least if the Group is purely
    made from OffsetApplyInstructions.

    This might be elegant to implement as an environment, and the repeat group
    would repeat the environment for the instructiongroup to be repeated.

    A potential reason to introduce the RepeatGroup would be external
    affirmation, that the computation can be done in parallel.

    In this case it would be a ParallelGroup that expects subgroups of type
    environment.


    Update 25/02/10
    ---------------

    Only the flattening of OffsetGroups and -Environments has to consider the
    entry offset merge. If not unpacked, the libroutine decides how it will be
    implemented in detail.

    To implement a proper copy, __deepcopy__ should be implemented, that takes
    a memo dict as extra argument to keep track of all entries that have been
    copied, with their id as a key. Doing that, references to a single object
    will be represented by new references to a single new object via lookup.
    """
    )


#
#
#
#
#
#
#
if __name__ == "__nothing__":
    import gc
    import weakref

    import psutil
    import os

    def memory_usage():
        process = psutil.Process(os.getpid())
        return process.memory_info().rss / 1024**2  # Convert to MB

    class LeakyClass:
        def __init__(self):
            self.ref = None  # Will hold circular reference
            self.something_big = ["some string"] * 60000000

        def __del__(self):
            # print(f"__del__ called for {self}")
            pass

    for _ in range(4):
        print(f"Memory usage: {memory_usage():.2f} MB")

        # Create objects with cyclic references
        a = LeakyClass()
        b = LeakyClass()

        a.ref = weakref.ref(b)  # Circular reference
        b.ref = weakref.ref(a)  # Circular reference

        a.ref = b  # Circular reference
        b.ref = a  # Circular reference

    print("before del")
    del a  # Delete objects
    print("del 1")
    del b
    print("del 2")

    print("call gc")
    gc.collect()  # Force garbage collection
    print("called")

    print("Garbage objects:", gc.garbage)  # Objects remain in gc.garbage
