"""
#autogenerated#header#do#not#modify############################################
#
# File:        instruction3.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/10/2024
# Last Update: 05/02/2025, 19:48
# Version:     0.0.1455
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """
Instruction module description

Important note: we distinguish the ftype and the itype of an instruction
instance. While the ftype is the functional type of the instruction instance
such as a specific kind of instruction, a group or else, the itype refers to
how it is applied on data.

Example: An InstructionGroup is an Instruction that has ftype 'group' but itype
can be 'instruction.someinstruction', which defines the greatest common
denominator of instruction types within the group, i.e. how it is to be applied
to data.
"""

from typing import Self

from phoenix._aux import segment_overlap
from phoenix.keymap import Key, KeyMap

# class _PartialFormatDict(dict):
#     """allows partial formatting of strings"""

#     def __setitem__(self, key, value):
#         if not isinstance(key, str):
#             raise ValueError("Key must be a string")
#         return super().__setitem__(key, value)

#     def __getitem__(self, key):
#         if key in self:
#             return super().__getitem__(key)
#         return "{" + key + "}"


class InstructionVar:
    """Represents a variable in an instruction"""

    # every variable is derived as a subclass
    # every instance represents a certain entry in that class

    _name: None | str = None
    _dtype: None | str = None
    _count: int = 0

    def __init__(self, *params, offsets=None, history=None):
        if offsets is None:
            offsets = []
        if history is None:
            history = []
        self._offs = offsets
        self._hist = history
        self._pars = list(params)
        self.progress()

    def __str__(self):
        dtype = self._dtype or "?"
        return f"<{self._name}({dtype}){self.params}>"

    def __repr__(self):
        return f"<{self._name}{self.params}>"

    @classmethod
    def new(cls, name=None, dtype=None):
        """create a new subclass from the name"""
        return type(name, (cls,), {"_name": name, "_dtype": dtype})

    def __init_subclass__(cls, **kwargs):
        cls._count += 1
        name = kwargs.get("name", None)
        dtype = kwargs.get("dtype")
        if name is None:
            name = f"ivar{cls._count}"
        if dtype is None:
            dtype = "f64"
        cls._dtype = dtype
        cls._name = name

    @property
    def offsets(self):
        """access offsets"""
        return list(self._offs)

    @property
    def history(self):
        """access offsets"""
        return list(self._hist)

    @property
    def params(self):
        """access params"""
        return list(self._pars)

    def copy(self):
        """return a copy"""
        return self.__class__(
            *self.params, offsets=self.offsets, history=self.history
        )

    def progress(self, *params) -> Self:
        """progress another param"""
        raise NotImplementedError("Must be implemented in subclass")

    def resolve(self, num=None) -> Self:
        """resolve num steps in param"""
        raise NotImplementedError("Must be implemented in subclass")

    def resolved(self):
        """return a resolved copy of self"""
        return self.copy().resolve()

    def apply_as_offset_to(self, other):
        """combine two variables"""
        return self.resolved().progress(*other.history, *other.params)

    def __xor__(self, other):
        return self.apply_as_offset_to(other)


class KeyMapInstructionVar(InstructionVar, name=None, dtype=None, _exc=False):
    """
    KeyMapInstructionVar

    Represents a variable that is based on a keymap.

    The main purpose is that there is a representation of input and output
    variables in instructions. They can be assigned to the ADAAs and have
    information on datatype and names.

    Especially for the keymap-version, the variable can be progressed when we
    move along nested keymaps, accumulating offsets.

    """

    _ckeymap: None | KeyMap = None

    def __init__(self, *params, offsets=None, history=None):
        self._kmap_ptr = self._ckeymap
        super().__init__(*params, offsets=offsets, history=history)
        # will resolve the key sequence params as seen from keymap

    def __init_subclass__(cls, **kwargs):
        cls._count += 1
        name = kwargs.get("name", None)
        dtype = kwargs.get("dtype", None)
        ckeymap = kwargs.get("keymap", cls._ckeymap)
        if name is None:
            name = f"ivar{cls._count}"
        if dtype is None:
            dtype = "f64"
        if ckeymap is None:
            raise ValueError("No keymap provided")
        cls._dtype = dtype
        cls._name = name
        cls._ckeymap = ckeymap

    # this simply repeats so the linter knows what's going on
    @classmethod
    def new(cls, name=None, keymap=None, dtype=None):
        """create a new subclass from the name"""
        return type(
            name, (cls,), {"_name": name, "_dtype": dtype, "_ckeymap": keymap}
        )

    @property
    def keymap(self):
        """access keymap"""
        return self._kmap_ptr

    def progress(self, *params):
        """progress params"""
        for param in params:
            self._pars.append(param)
        return self

    def resolve(self, num=None):
        """resolve num steps in param"""
        if num is None:
            num = len(self._pars)
        for _ in range(num):
            if self._pars:
                param = self._pars.pop(0)
                offset, self._kmap_ptr = self._kmap_ptr.find(param)
                self._offs.append(offset)
                self._hist.append(param)
            else:
                raise ValueError("No more parameters to resolve")
        return self


class Instruction:
    """Base class for instructions"""

    _ftype = "instruction"
    _obj_id_count = 0

    def _get_obj_id(self):
        self.__class__._obj_id_count += 1
        return f"{self._ftype}#{self.__class__._obj_id_count}"

    @staticmethod
    def _get_itype_common_root(instruction_list):
        if len(instruction_list) == 0:
            return None
        segments_list = [instr.itype.split(".") for instr in instruction_list]
        latest_parent_itype = ".".join(segment_overlap(*segments_list))
        return latest_parent_itype

    def __len__(self):
        return 1

    def __init__(self, *, itype=None):
        self._sort_key = None
        self._itype = itype
        self._obj_id = self._get_obj_id()

    def __init_subclass__(cls, ftype):
        # print("asd", cls._ftype, ftype, cls.__name__)
        ftype = ftype.replace(".", ":")
        cls._obj_id_count = 0
        cls._ftype += f".{ftype}"

    def checksum(self):
        """get a checksum of the instruction"""
        test_tuple = (
            self._itype,
            self._ftype,
        )
        return test_tuple

    @property
    def instructions(self):
        """access instructions"""
        # break recursive loop
        yield self

    # pylint: disable=unused-argument
    def unpack(self, recursive: bool = True):
        """unpack the instruction"""
        # break recursive loop
        yield self

    # pylint: enable=unused-argument

    @property
    def itype(self):
        """access read-only attribute itype"""
        return self._itype

    @property
    def ftype(self):
        """property for class level ftype attribute"""
        return self.__class__._ftype

    @property
    def sort_key(self):
        """access protected sort key attribute"""
        if self._sort_key is None:
            self._sort_key = self._get_sort_key()
        return self._sort_key

    def update_sort_key(self, function=None):
        """update the sort key"""
        self._sort_key = self._get_sort_key(function=function)

    def _get_default_sort_key(self):
        return tuple()

    def _get_sort_key(self, function=None):
        """get a sort key for the instruction, use default function if none is
        given"""
        if function is None:
            return self._get_default_sort_key()
        return function(self)

    def is_subtype(self, itype):
        """check if this instruction is a subtype of a reference.
        Returns true if this instruction's type can be derived from or is equal
        to the reference, i.e. the overlap of the instruction type is exactly
        the reference (which has at most the same length but all segments are
        identical)"""
        if isinstance(itype, Instruction):
            itype = itype.itype
        overlap = segment_overlap(*[self.itype.split("."), itype.split(".")])
        return overlap == itype.split(".")

    def __gt__(self, other):
        return self.itype > other.itype

    def __eq__(self, other):
        return self.itype == other.itype


class GenericInstruction(Instruction, ftype="generic"):
    """Generic instruction.

    At this point the params dictionary is introduced. Multiple aliases are
    supported for flexible entry access without creating duplicates.
    """

    _alias: dict[str, str] = {}

    def __init__(self, **params):
        super().__init__(itype=self.ftype)
        self._params = params
        self._protected = True

    def __enter__(self):
        self._protected = False
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self._protected = True

    def __gt__(self, other):
        return self.sort_key > other.sort_key

    def __eq__(self, other):
        return self.sort_key == other.sort_key

    def _get_default_sort_key(self):
        return tuple(self.values())

    def keys(self):
        """dict like call to keys"""
        yield from self._params.keys()

    def items(self):
        """dict like call to items"""
        yield from self._params.items()

    def values(self):
        """dict like call to values"""
        yield from self._params.values()

    def __getitem__(self, key):
        if key in self._params:
            return self._params[key]
        return self._from_alias(key)

    def __setitem__(self, key, value):
        self.set(key, value)

    @classmethod
    def set_alias(cls, alias, reference):
        """add an alias to the class"""
        cls._alias[alias] = reference

    def checksum(self):
        test_tuple = (
            *super().checksum(),
            tuple(self.params),
        )
        return test_tuple

    @property
    def params(self):
        """access values as list"""
        return tuple(self.values())

    def get(self, *in_args):
        """mimic the get behaviour of dicts"""
        match in_args:
            case (key, default):
                if key in self._params:
                    return self._params[key]
                try:
                    return self._from_alias(key)
                except KeyError:
                    return default
                return default
            case (key,):
                if key in self._params:
                    return self._params[key]
                return self._from_alias(key)
            case _:
                raise ValueError(
                    "get requires a key and an optional default value to return"
                )

    def set(self, key, value):
        """set a value, consider protection"""
        if self._protected:
            raise ValueError(
                f"cannot access protected value of key '{key}' for writing"
            )
        self._params[key] = value

    def to_dict(self, *keys, defaults: dict | None = None):
        """get a dictionary from keys, filled with the values"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        pfd = {}  # _PartialFormatDict
        if keys:
            pfd.update(
                {key: self.get(key, defaults.get(key, None)) for key in keys}
            )
        else:
            pfd.update(
                {
                    key: self.get(key, defaults.get(key, None))
                    for key in self.keys()
                }
            )
        return pfd

    def to_tuple(self, *keys, defaults: dict | None = None):
        """get a data tuple from keys in the order the keys are requested"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        if keys:
            return tuple(
                self.get(key, defaults.get(key, None)) for key in keys
            )
        return tuple(
            self.get(key, defaults.get(key, None)) for key in self.keys()
        )

    def _from_alias(self, key):
        print(f"look up potential alias {key} in {self.__class__.__name__}")
        if key in self.__class__._alias:
            # don't call self._params here, so alias can chain
            return self[self.__class__._alias[key]]
        raise KeyError(f"Key '{key}' not found in dict nor alias map")


class ExpressionInstruction(GenericInstruction, ftype="expr"):
    """Represents an Expression"""


class InstructionGroup(Instruction, ftype="group"):
    """Base class for instruction groups"""

    def __init__(self, instructions, itype=None):
        self._instructions = list(instructions)
        self._len = len(self._instructions)
        if itype is None:
            itype = InstructionGroup._get_itype_common_root(self._instructions)
        super().__init__(itype=itype)

    def __len__(self):
        return sum(len(instr) for instr in self.instructions)

    @property
    def itype(self):
        return self._itype

    # def _update(self):
    #     self._len = len(self._instructions)
    #     self._itype = InstructionGroup._get_itype_common_root(
    #         self._instructions
    #     )

    @property
    def instructions(self):
        """access read-only attribute instructions as generator"""
        yield from self._instructions

    def unpack(self, recursive: bool = True):
        """unpack all instructions, including inner groups"""
        for instr in self.instructions:
            if recursive:
                yield from instr.unpack(recursive=True)
            else:
                yield instr

    def flatten(self):
        """flatten instructions, which will unpack all inner groups"""
        return self.__class__(list(self.unpack()), itype=self._itype)

    def sorted(self, ordering_function=None, sort_function=None):
        """return a sorted version. Sort function is optional. Does not
        overwrite sort keys. If no function is given, the default
        sort keys are used"""
        if sort_function is None:
            sort_function = sorted
        if ordering_function is None:
            return self.__class__(
                list(sort_function(self.instructions)), itype=self._itype
            )
        sorted_instructions = sort_function(
            [(ordering_function(instr), instr) for instr in self.instructions]
        )
        return self.__class__(
            [instr for _, instr in sorted_instructions], itype=self._itype
        )

    def grouped(self, function=None, size=None, number=None):
        """subdivide the current instruction group into smaller groups"""

        match (function, size, number):
            case (function, None, None):
                assert callable(function)
                return self.group_by_key(function)

            case (None, size, None):
                assert isinstance(size, int)
                return self.group_to_size(size)

            case (None, None, number):
                assert isinstance(number, int)
                return self.group_to_batches

            case _:
                raise ValueError(
                    "only one of 'function', 'size' and 'number' can be set"
                )

    def group_by_key(self, function, group_type=None):
        """generate groups by a key generating function"""
        groups = {}
        for instr in self.instructions:
            group_id = function(instr)
            if group_id not in groups:
                groups[group_id] = []
            groups[group_id].append(instr)
        if group_type is None:
            group_type = self.__class__
        return self.__class__(
            [
                group_type(group, itype=self._itype)
                for group in groups.values()
            ],
            itype=self._itype,
        )

    def group_to_batches(self, num_batches, group_type=None):
        """subdivide the group into a number of batches.
        Does not conserve continuousity of data"""
        groups = [[] for _ in num_batches]
        if group_type is None:
            group_type = self.__class__
        for num, instr in enumerate(self.instructions):
            groups[num % num_batches].append(instr)
        return self.__class__(
            [group_type(group) for group in groups], itype=self._itype
        )

    def group_to_size(self, max_size, group_type=None):
        """split the instructions into groups of a certain (maximum) size"""
        group = []
        collect = []
        if group_type is None:
            group_type = self.__class__
        for instr in self.instructions:
            if len(group) >= max_size:
                collect.append(group_type(group, itype=self._itype))
                group = []
            group.append(instr)
        if group:
            collect.append(group_type(group, itype=self._itype))
        return self.__class__(collect, itype=self._itype)


class OffsetEnvironment(InstructionGroup, ftype="applyoffset"):
    """Within this environment, variables are offsetted"""

    # TODO

    # Contains
    # - Instructions to be offsetted

    # requires:
    # - value of offset
    # - optional offset mapping if names change


class OffsetRepeat(InstructionGroup, ftype="offsetrepeat"):
    """
    OffsetRepeat

    Repeat the content for multiple offsets
    """

    def __init__(self, instructions, itype=None):
        InstructionGroup.__init__(self, instructions, itype=itype)
        self._offsets = []

    def append_offset(self, **offest_parameters):
        """append offset, consider defaults"""


class SubroutineGroup(InstructionGroup, ftype="subroutine"):
    """
    SubroutineGroup

    suggests that upon implementation these instructions are grouped in a
    subroutine
    """

    def __init__(self, instructions, inp_names, out_names, itype=None):
        super().__init__(instructions, itype=itype)


class PolynomialInstruction(ExpressionInstruction, ftype="polynomial"):
    """
    Base class for polynomial instructions
    y[key_tgt0] = c0 x[key_tgt0]^0 + c1 x[key_tgt0]^1 + c2 x[key_tgt0]^2 + ...
    """

    def __init__(self, trg0, src0, *coeffs):
        params = {}
        degree = len(coeffs) - 1
        assert isinstance(trg0, InstructionVar)
        assert isinstance(src0, InstructionVar)
        params["degree"] = degree
        params["trg0"] = trg0
        params["src0"] = src0
        for exp, coeff in enumerate(coeffs):
            params[f"coeff_x{exp}"] = coeff
        super().__init__(**params, itype=self.ftype)


class AffineOperationInstruction(PolynomialInstruction, ftype="affine"):
    """y[key_tgt0] = a * x[key_src] + b type instruction"""

    def __init__(self, tgt0, src0, alpha, beta):
        super().__init__(tgt0, src0, beta, alpha)


class LinearOperationInstruction(AffineOperationInstruction, ftype="linear"):
    """y[key_tgt0] = a * x[key_src] type instruction"""

    def __init__(self, tgt0, src0, alpha):
        super().__init__(tgt0, src0, 0, alpha)


from phoenix.keymap import KeyMap, Key

ltl_km = KeyMap(name="little")
ltl_km.entry("key1")
ltl_km.entry("key2")
ltl_km.entry("key3")

big_km = KeyMap(name="big")
big_km.link("foo1", ltl_km)
big_km.link("foo2", ltl_km)

big_km.update()
print(list(big_km.keys()))

var_inp = KeyMapInstructionVar.new(name="input1", keymap=big_km)
var_out = KeyMapInstructionVar.new(name="output1", keymap=big_km)

a = SubroutineGroup(
    sum(
        (
            [
                LinearOperationInstruction(
                    var_out(foo, "key1"), var_inp(foo, "key3"), 1.0
                ),
                LinearOperationInstruction(
                    var_out(foo, "key2"), var_inp(foo, "key2"), 1.0
                ),
                LinearOperationInstruction(
                    var_out(foo, "key3"), var_inp(foo, "key1"), 1.0
                ),
            ]
            for foo in ["foo1", "foo2"]
        ),
        start=[],
    ),
    None,
    None,
)
for instruction in a.instructions:
    print(instruction._obj_id)
    print(instruction.to_dict())
print(a._obj_id)

print(SubroutineGroup._obj_id_count)
print(PolynomialInstruction._obj_id_count)
print(LinearOperationInstruction._obj_id_count)
print(AffineOperationInstruction._obj_id_count)

print(var_inp._name)

print(var_inp("foo1"))

print(
    """s
Strategy:

We introduce the variable data type to remember the variable name and the
proper way to access it. At the instruction level, this access is not specific
to a backend yet.

A variable is represented by its own subclass of the proper parent class.
Loops over offset variations can be realized by resolving the accumulated param
values that refer to KeyMap Keys in case of a KeyMapInstructionVar.
They can be translated into an offset. 

Upon application, this offset can be included into a loop variable, that can be
used symbolically.

This loop variable can be hard coded in the instruction group. For example, the
GPU implementation might not need it, and at instruction level I don't want the
structure to be too specific.

My dream-procedure:
We introduce a offset-repeat instruction, where a single instructiongroup is
repeated for multiple offsets. This instruction group can take offset
configurations. Right now I am not sure if these offset configurations should
be a list of offsets passed to a special group, or just repetitions of a
special apply-offset command and some code magic. Or maybe a special group and
a special operation that simply says "repeat".

As of now I think, that an OffsetApplyInstruction in a RepeatGroup is the right
way to go. Upon evaluation, the Instruction group to be offsetted will be 
recognized by ID once it is repeated a couple times. In this case, OffsetApply
should group automatically. At least if the Group is purely made from
OffsetApplyInstructions.

This might be elegant to implement as an environment, and the repeat group
would repeat the environment for the instructiongroup to be repeated.

A potential reason to introduce the RepeatGroup would be external affirmation,
that the computation can be done in parallel.

In this case it would be a ParallelGroup that expects subgroups of type
environment.
"""
)
