"""
#autogenerated#header#do#not#modify############################################
#
# File:        instruction3.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/10/2024
# Last Update: 30/01/2025, 14:40
# Version:     0.0.945
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """
Instruction module description

Important note: we distinguish the ftype and the itype of an instruction
instance. While the ftype is the functional type of the instruction instance
such as a specific kind of instruction, a group or else, the itype refers to
how it is applied on data.

Example: An InstructionGroup is an Instruction that has ftype 'group' but itype
can be 'instruction.someinstruction', which defines the greatest common
denominator of instruction types within the group, i.e. how it is to be applied
to data.
"""


from phoenix._aux import segment_overlap, mro_latest_common_parent
from phoenix.keymap import Key

# class _PartialFormatDict(dict):
#     """allows partial formatting of strings"""

#     def __setitem__(self, key, value):
#         if not isinstance(key, str):
#             raise ValueError("Key must be a string")
#         return super().__setitem__(key, value)

#     def __getitem__(self, key):
#         if key in self:
#             return super().__getitem__(key)
#         return "{" + key + "}"


class Instruction:
    """Base class for instructions"""

    _ftype = "instruction"

    @staticmethod
    def _get_itype_common_root(instruction_list):
        if len(instruction_list) == 0:
            return None
        segments_list = [instr.itype.split(".") for instr in instruction_list]
        latest_parent_itype = ".".join(segment_overlap(*segments_list))
        """
        # TODO: maybe implement this later as alternative to segment_list:
        # if __debug__:
        #     # use __mro__ to find latest common parent
        #     alternative_segment_list = list(
        #         [
        #             list(
        #                 filter(
        #                     lambda x: issubclass(x, Instruction),
        #                     instr.__class__.__mro__,
        #                 )
        #             )[::-1]
        #             for instr in instruction_list
        #         ]
        #     )
        #     print("ASL", alternative_segment_list)
        #     latest_parent = mro_latest_common_parent(*alternative_segment_list)
        #     print(
        #         latest_parent._ftype == latest_parent_itype,
        #         latest_parent._ftype,
        #         latest_parent_itype,
        #         latest_parent,
        #     )
        #     if latest_parent._ftype != latest_parent_itype:
        #         print(latest_parent._itype, latest_parent_itype)
        #         assert False
        # CONCLUSION: No, don't do that, groups are functionally represented by
        # their itype, not their ftype. The class encodes the latter!
        """
        return latest_parent_itype

    def __len__(self):
        return 1

    def __init__(self, *, itype=None):
        self._sort_key = None
        self._itype = itype

    def __init_subclass__(cls, ftype):
        # print("asd", cls._ftype, ftype, cls.__name__)
        ftype = ftype.replace(".", ":")
        cls._ftype += f".{ftype}"

    def checksum(self):
        """get a checksum of the instruction"""
        test_tuple = (
            self._itype,
            self._ftype,
        )
        return test_tuple

    @property
    def instructions(self):
        """access instructions"""
        # break recursive loop
        yield self

    # pylint: disable=unused-argument
    def unpack(self, recursive: bool = True):
        """unpack the instruction"""
        # break recursive loop
        yield self

    # pylint: enable=unused-argument

    @property
    def itype(self):
        """access read-only attribute itype"""
        return self._itype

    @property
    def ftype(self):
        """property for class level ftype attribute"""
        return self.__class__._ftype

    @property
    def sort_key(self):
        """access protected sort key attribute"""
        if self._sort_key is None:
            self._sort_key = self._get_sort_key()
        return self._sort_key

    def update_sort_key(self, function=None):
        """update the sort key"""
        self._sort_key = self._get_sort_key(function=function)

    def _get_default_sort_key(self):
        return tuple()

    def _get_sort_key(self, function=None):
        """get a sort key for the instruction, use default function if none is
        given"""
        if function is None:
            return self._get_default_sort_key()
        return function(self)

    def is_subtype(self, itype):
        """check if this instruction is a subtype of a reference.
        Returns true if this instruction's type can be derived from or is equal
        to the reference, i.e. the overlap of the instruction type is exactly
        the reference (which has at most the same length but all segments are
        identical)"""
        if isinstance(itype, Instruction):
            itype = itype.itype
        overlap = segment_overlap(*[self.itype.split("."), itype.split(".")])
        return overlap == itype.split(".")

    def __gt__(self, other):
        return self.itype > other.itype

    def __eq__(self, other):
        return self.itype == other.itype


class GenericInstruction(Instruction, ftype="generic"):
    """Generic instruction.

    At this point the params dictionary is introduced. Multiple aliases are
    supported for flexible entry access without creating duplicates.
    """

    _alias: dict[str, str] = {}

    def __init__(self, **params):
        super().__init__(itype=self.ftype)
        self._params = params
        self._protected = True

    def __enter__(self):
        self._protected = False
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self._protected = True

    def __gt__(self, other):
        return self.sort_key > other.sort_key

    def __eq__(self, other):
        return self.sort_key == other.sort_key

    def _get_default_sort_key(self):
        return tuple(self.values())

    def keys(self):
        """dict like call to keys"""
        yield from self._params.keys()

    def items(self):
        """dict like call to items"""
        yield from self._params.items()

    def values(self):
        """dict like call to values"""
        yield from self._params.values()

    def __getitem__(self, key):
        if key in self._params:
            return self._params[key]
        return self._from_alias(key)

    def __setitem__(self, key, value):
        self.set(key, value)

    @classmethod
    def set_alias(cls, alias, reference):
        """add an alias to the class"""
        cls._alias[alias] = reference

    def checksum(self):
        test_tuple = (
            *super().checksum(),
            tuple(self.params),
        )
        return test_tuple

    @property
    def params(self):
        """access values as list"""
        return tuple(self.values())

    def get(self, *in_args):
        """mimic the get behaviour of dicts"""
        match in_args:
            case (key, default):
                return self._params.get(key, default)
            case (key,):
                return self._params.get(key)
            case _:
                raise RuntimeError("You shouldn't be here!")

    def set(self, key, value):
        """set a value, consider protection"""
        if self._protected:
            raise ValueError(
                f"cannot access protected value of key '{key}' for writing"
            )
        self._params[key] = value

    def to_dict(self, *keys, defaults: dict | None = None):
        """get a dictionary from keys, filled with the values"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        pfd = {}  # _PartialFormatDict
        if keys:
            pfd.update(
                {key: self.get(key, defaults.get(key, None)) for key in keys}
            )
        else:
            pfd.update(
                {
                    key: self.get(key, defaults.get(key, None))
                    for key in self.keys()
                }
            )
        return pfd

    def to_tuple(self, *keys, defaults: dict | None = None):
        """get a data tuple from keys in the order the keys are requested"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        if keys:
            return tuple(self.get(key, defaults.get(key, None)) for key in keys)
        return tuple(
            self.get(key, defaults.get(key, None)) for key in self.keys()
        )

    def _from_alias(self, key):
        print(f"look up potential alias {key} in {self.__class__.__name__}")
        if key in self.__class__._alias:
            # don't call self._params here, so alias can chain
            return self[self.__class__._alias[key]]
        raise KeyError(f"Key '{key}' not found in dict nor alias map")


class KeyMapBasedInstruction(GenericInstruction, ftype="keymap"):
    """Subclass for KeyMap based instructions"""

    def get_index(self, var):
        return self[f"{var}_idx"]

    def get_key(self, var):
        return self[f"{var}_key"]


class InstructionGroup(Instruction, ftype="group"):
    """Base class for instruction groups"""

    def __init__(self, instructions, itype=None):
        self._instructions = list(instructions)
        self._len = len(self._instructions)
        if itype is None:
            itype = InstructionGroup._get_itype_common_root(self._instructions)
        super().__init__(itype=itype)

    def __len__(self):
        return sum(len(instr) for instr in self.instructions)

    @property
    def itype(self):
        return self._itype

    # def _update(self):
    #     self._len = len(self._instructions)
    #     self._itype = InstructionGroup._get_itype_common_root(
    #         self._instructions
    #     )

    @property
    def instructions(self):
        """access read-only attribute instructions as generator"""
        yield from self._instructions

    def unpack(self, recursive: bool = True):
        """unpack all instructions, including inner groups"""
        for instr in self.instructions:
            if recursive:
                yield from instr.unpack(recursive=True)
            else:
                yield instr

    def flatten(self):
        """flatten instructions, which will unpack all inner groups"""
        return self.__class__(list(self.unpack()), itype=self._itype)

    def sorted(self, ordering_function=None, sort_function=None):
        """return a sorted version. Sort function is optional. Does not
        overwrite sort keys. If no function is given, the default
        sort keys are used"""
        if sort_function is None:
            sort_function = sorted
        if ordering_function is None:
            return self.__class__(
                list(sort_function(self.instructions)), itype=self._itype
            )
        sorted_instructions = sort_function(
            [(ordering_function(instr), instr) for instr in self.instructions]
        )
        return self.__class__(
            [instr for _, instr in sorted_instructions], itype=self._itype
        )

    def grouped(self, function=None, size=None, number=None):
        """subdivide the current instruction group into smaller groups"""

        match (function, size, number):
            case (function, None, None):
                assert callable(function)
                return self.group_by_key(function)

            case (None, size, None):
                assert isinstance(size, int)
                return self.group_to_size(size)

            case (None, None, number):
                assert isinstance(number, int)
                return self.group_to_batches

            case _:
                raise ValueError(
                    "only one of 'function', 'size' and 'number' can be set"
                )

    def group_by_key(self, function, group_type=None):
        """generate groups by a key generating function"""
        groups = {}
        for instr in self.instructions:
            group_id = function(instr)
            if group_id not in groups:
                groups[group_id] = []
            groups[group_id].append(instr)
        if group_type is None:
            group_type = self.__class__
        return self.__class__(
            [group_type(group, itype=self._itype) for group in groups.values()],
            itype=self._itype,
        )

    def group_to_batches(self, num_batches, group_type=None):
        """subdivide the group into a number of batches.
        Does not conserve continuousity of data"""
        groups = [[] for _ in num_batches]
        if group_type is None:
            group_type = self.__class__
        for num, instr in enumerate(self.instructions):
            groups[num % num_batches].append(instr)
        return self.__class__(
            [group_type(group) for group in groups], itype=self._itype
        )

    def group_to_size(self, max_size, group_type=None):
        """split the instructions into groups of a certain (maximum) size"""
        group = []
        collect = []
        if group_type is None:
            group_type = self.__class__
        for instr in self.instructions:
            if len(group) >= max_size:
                collect.append(group_type(group, itype=self._itype))
                group = []
            group.append(instr)
        if group:
            collect.append(group_type(group, itype=self._itype))
        return self.__class__(collect, itype=self._itype)


class OffsetRepeat(InstructionGroup, ftype="offsetrepeat"):
    """
    OffsetRepeat

    Repeat the content for multiple offsets
    """

    def __init__(self, instructions, offsets, itype=None):
        InstructionGroup.__init__(self, instructions, itype=itype)
        self._offsets: dict[str, list[Key]] = offsets


class SubroutineGroup(InstructionGroup, ftype="subroutine"):
    """
    SubroutineGroup

    suggests that upon implementation these instructions are grouped in a
    subroutine
    """

    def __init__(self, instructions, itype=None):
        super().__init__(instructions, itype=itype)


class PolynomialInstruction(KeyMapBasedInstruction, ftype="polynomial"):
    """
    Base class for polynomial instructions
    y[key_trgt] = c0 x[key_trgt]^0 + c1 x[key_trgt]^1 + c2 x[key_trgt]^2 + ...
    """

    def __init__(self, key_trgt, key_src0, *coeffs):
        params = {}
        degree = len(coeffs) - 1
        params["degree"] = degree
        params["trgt_key"] = key_trgt
        params["src0_key"] = key_src0
        for exp, coeff in enumerate(coeffs):
            params[f"coeff_x{exp}"] = coeff
        super().__init__(**params, itype=self.ftype)


class AffineOperationInstruction(PolynomialInstruction, ftype="affine"):
    """y[key_trgt] = a * x[key_src] + b type instruction"""

    def __init__(self, key_trgt, key_src0, alpha, beta):
        super().__init__(key_trgt, key_src0, beta, alpha)


class LinearOperationInstruction(AffineOperationInstruction, ftype="linear"):
    """y[key_trgt] = a * x[key_src] type instruction"""

    def __init__(self, key_trgt, key_src0, alpha):
        super().__init__(key_trgt, key_src0, 0, alpha)


print(SubroutineGroup([GenericInstruction()]).itype)


"""
instructions = [IGroup1, IGroup2, ...]

Routine(instructions)
"""
