"""
#autogenerated#header#do#not#modify############################################
#
# File:        instruction3.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/10/2024
# Last Update: 29/11/2024, 17:22
# Version:     0.0.622
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """
Instruction module description

Important note: we distinguish the ftype and the itype of an instruction
instance. While the ftype is the functional type of the instruction instance
such as a specific kind of instruction, a group or else, the itype refers to
how it is applied on data.

Example: An InstructionGroup is an Instruction that has ftype 'group' but itype
can be 'instruction.someinstruction', which defines the greatest common
denominator of instruction types within the group, i.e. how it is to be applied
to data.
"""


from phoenix._aux import segment_overlap, mro_latest_common_parent


class Instruction:
    """Base class for instructions"""

    _ftype = "instruction"

    @staticmethod
    def _get_itype_common_root(instruction_list):
        if len(instruction_list) == 0:
            return None
        segments_list = [instr.itype.split(".") for instr in instruction_list]
        latest_parent_itype = ".".join(segment_overlap(*segments_list))

        # pylint: disable=pointless-string-statement
        # TODO: maybe implement this later as alternative to segment_list:
        if __debug__:
            # use __mro__ to find latest common parent
            alternative_segment_list = list(
                [
                    list(
                        filter(
                            lambda x: issubclass(x, Instruction),
                            instr.__class__.__mro__,
                        )
                    )[::-1]
                    for instr in instruction_list
                ]
            )
            latest_parent = mro_latest_common_parent(*alternative_segment_list)
            assert latest_parent._ftype == latest_parent_itype

        # pylint: enable=pointless-string-statement
        return latest_parent_itype

    def __len__(self):
        return 1

    def __init__(self, *, itype=None):
        self._sort_key = None
        self._itype = itype

    def __init_subclass__(cls, ftype):
        # print("asd", cls._ftype, ftype, cls.__name__)
        ftype = ftype.replace(".", ":")
        cls._ftype += f".{ftype}"

    @property
    def instructions(self):
        """access instructions"""
        # break recursive loop
        yield self

    # pylint: disable=unused-argument
    def unpack(self, recursive: bool = True):
        """unpack the instruction"""
        # break recursive loop
        yield self

    # pylint: enable=unused-argument

    @property
    def itype(self):
        """access read-only attribute itype"""
        return self._itype

    @property
    def ftype(self):
        """property for class level ftype attribute"""
        return self.__class__._ftype

    @property
    def sort_key(self):
        """access protected sort key attribute"""
        if self._sort_key is None:
            self._sort_key = self._get_sort_key()
        return self._sort_key

    def update_sort_key(self, function=None):
        """update the sort key"""
        self._sort_key = self._get_sort_key(function=function)

    def _get_default_sort_key(self):
        return tuple()

    def _get_sort_key(self, function=None):
        """get a sort key for the instruction, use default function if none is
        given"""
        if function is None:
            return self._get_default_sort_key()
        return function(self)

    def is_subtype(self, itype):
        """check if this instruction is a subtype of a reference.
        Returns true if this instruction's type can be derived from or is equal
        to the reference, i.e. the overlap of the instruction type is exactly
        the reference (which has at most the same length but all segments are
        identical)"""
        if isinstance(itype, Instruction):
            itype = itype.itype
        overlap = segment_overlap(*[self.itype.split("."), itype.split(".")])
        return overlap == itype.split(".")

    def __gt__(self, other):
        return self.itype > other.itype

    def __eq__(self, other):
        return self.itype == other.itype


class GenericInstruction(Instruction, ftype="generic"):
    """Generic instruction"""

    def __init__(self, **params):
        super().__init__(itype=self.ftype)
        self._params = params
        self._protected = True

    def __enter__(self):
        self._protected = False
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self._protected = True

    def __gt__(self, other):
        return self.sort_key > other.sort_key

    def __eq__(self, other):
        return self.sort_key == other.sort_key

    def _get_default_sort_key(self):
        return tuple(self.values())

    def keys(self):
        """dict like call to keys"""
        yield from self._params.keys()

    def items(self):
        """dict like call to items"""
        yield from self._params.items()

    def values(self):
        """dict like call to values"""
        yield from self._params.values()

    def __getitem__(self, key):
        return self.get(key)

    def __setitem__(self, key, value):
        self.set(key, value)

    @property
    def params(self):
        """access values as list"""
        return list(self.values())

    def get(self, *in_args):
        """mimic the get behaviour of dicts"""
        match in_args:
            case (key, default):
                return self._params.get(key, default)
            case (key,):
                return self._params.get(key)
            case _:
                raise RuntimeError("You shouldn't be here!")

    def set(self, key, value):
        """set a value, consider protection"""
        if self._protected:
            raise ValueError(
                f"cannot access protected value of key '{key}' for writing"
            )
        self._params[key] = value

    def to_dict(self, *keys, defaults: dict | None = None):
        """get a dictionary from keys, filled with the values"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        if keys:
            return {
                key: self.get(key, defaults.get(key, None)) for key in keys
            }
        return {
            key: self.get(key, defaults.get(key, None)) for key in self.keys()
        }

    def to_tuple(self, *keys, defaults: dict | None = None):
        """get a data tuple from keys in the order the keys are requested"""
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        if keys:
            return tuple(
                self.get(key, defaults.get(key, None)) for key in keys
            )
        return tuple(
            self.get(key, defaults.get(key, None)) for key in self.keys()
        )


class InstructionGroup(Instruction, ftype="group"):
    """Base class for instruction groups"""

    def __init__(self, instructions, itype=None):
        self._instructions = list(instructions)
        self._len = len(self._instructions)
        super().__init__(itype=itype)

    def __len__(self):
        return sum(len(instr) for instr in self.instructions)

    @property
    def itype(self):
        if self._itype is None:
            self._itype = InstructionGroup._get_itype_common_root(
                self._instructions
            )
        return self._itype

    def _update(self):
        self._len = len(self._instructions)
        self._itype = InstructionGroup._get_itype_common_root(
            self._instructions
        )

    @property
    def instructions(self):
        """access read-only attribute instructions as generator"""
        yield from self._instructions

    def unpack(self, recursive: bool = True):
        """unpack all instructions, including inner groups"""
        for instr in self.instructions:
            if recursive:
                yield from instr.unpack(recursive=True)
            else:
                yield instr

    def flatten(self):
        """flatten instructions, which will unpack all inner groups"""
        return InstructionGroup(list(self.unpack()), itype=self._itype)

    def sorted(self, function=None):
        """return a sorted version. Sort function is optional. Does not
        overwrite sort keys. If no function is given, the default
        sort keys are used"""
        if function is None:
            return InstructionGroup(
                list(sorted(self.instructions)), itype=self._itype
            )
        sorted_instructions = sorted(
            [(function(instr), instr) for instr in self.instructions]
        )
        return InstructionGroup(
            [instr for _, instr in sorted_instructions], itype=self._itype
        )

    def grouped(self, function=None, size=None, number=None):
        """subdivide the current instruction group into smaller groups"""

        match (function, size, number):
            case (function, None, None):
                assert callable(function)
                return self.group_by_key(function)

            case (None, size, None):
                assert isinstance(size, int)
                return self.group_to_size(size)

            case (None, None, number):
                assert isinstance(number, int)
                return self.group_to_batches

            case _:
                raise ValueError(
                    "only one of 'function', 'size' and 'number' can be set"
                )

    def group_by_key(self, function):
        """generate groups by a key generating function"""
        groups = {}
        for instr in self.instructions:
            group_id = function(instr)
            if group_id not in groups:
                groups[group_id] = []
            groups[group_id].append(instr)
        return InstructionGroup(
            [
                InstructionGroup(group, itype=self._itype)
                for group in groups.values()
            ],
            itype=self._itype,
        )

    def group_to_batches(self, num_batches):
        """subdivide the group into a number of batches.
        Does not conserve continuousity of data"""
        groups = [[] for _ in num_batches]
        for num, instr in enumerate(self.instructions):
            groups[num % num_batches].append(instr)
        return InstructionGroup(
            [InstructionGroup(group) for group in groups], itype=self._itype
        )

    def group_to_size(self, max_size):
        """split the instructions into groups of a certain (maximum) size"""
        group = []
        collect = []
        for instr in self.instructions:
            if len(group) >= max_size:
                collect.append(InstructionGroup(group, itype=self._itype))
                group = []
            group.append(instr)
        if group:
            collect.append(InstructionGroup(group, itype=self._itype))
        return InstructionGroup(collect, itype=self._itype)


class PolynomialInstruction(GenericInstruction, ftype="polynomial"):
    """Base class for polynomial instructions"""

    def __init__(self, key_tgt, key_src, *coeffs):
        params = {f"C{num}": val for num, val in enumerate(coeffs)}
        params["deg"] = len(coeffs)
        params["key_tgt"] = key_tgt
        params["key_src"] = key_src
        super().__init__(**params, itype=self.ftype)


class LinearOperationInstruction(PolynomialInstruction, ftype="linear"):
    """Ax + b type instruction"""

    def __init__(self, a, )


if __name__ == "__main__":
    x = GenericInstruction(foo="bar")
    print(x.params)
    print(x.ftype)

    class SpecificInstruction(GenericInstruction, ftype="specific"):
        def __init__(self, *, foo):
            super().__init__(foo=foo)

    class OtherSpecificInstruction(GenericInstruction, ftype="otherspecific"):
        pass

    class MoreSpecificInstruction(SpecificInstruction, ftype="more"):
        def __init__(self):
            super().__init__(foo="default")

    y = SpecificInstruction(foo="foo")
    z = OtherSpecificInstruction(foo="bar")
    k = MoreSpecificInstruction()
    print(y.ftype)

    print(InstructionGroup._get_itype_common_root([z, k]))

    foo = InstructionGroup([y, k])
    print(foo.ftype)
    print(foo._itype)
    print(foo.itype)
    print(foo._itype)

    print(y.is_subtype(x))
    print(y.is_subtype(y))
    # print(foo.is_subtype(y))

    print()
    bar = InstructionGroup(
        [
            foo,
            foo,
        ]
    )
    for instruction in bar.instructions:
        print(instruction)

    print()

    baz = bar.flatten()
    foo = baz.grouped(lambda x: x["foo"])
    print([len(instr) for instr in foo.instructions])
    bar = baz.group_to_size(5)
    print([len(instr) for instr in bar.instructions])

    for instruction in baz.instructions:
        print(instruction)

    try:
        next(baz.instructions)["foo"] = "bazbaz"
    except ValueError as e:
        print(e)

    with next(baz.instructions) as this_instruction:
        print("Here", this_instruction)
        this_instruction["foo"] = "bazbazbaz"

    test = InstructionGroup(list(baz.unpack()) + [z, z])

    print(len(test))
    for ins in test.instructions:
        print(ins)

    print()
    for ins in foo.unpack(recursive=True):
        print(ins, len(ins), ins.to_dict(), ins.to_tuple())
        print(
            "in this test we output 'foo' as {foo} and we like it.".format(
                **ins
            )
        )

    # print(SpecificInstruction.__mro__[::-1])
    # print(MoreSpecificInstruction.__mro__[::-1])
    # print(OtherSpecificInstruction.__mro__[::-1])

    print(test.ftype, test.itype)

    polytest = PolynomialInstruction(0, 1, 2, 3)
    print(polytest.to_dict())
