"""
#autogenerated#header#do#not#modify############################################
#
# File:        lrvariable.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   04/02/2025
# Last Update: 03/03/2025, 17:38
# Version:     0.0.179
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from typing import Set

# import weakref


# class LanguageFeature:
#     """Language feature base class"""

#     def __init__(self, name, size=None, dtype=None):
#         self._name = name
#         self._dtype = dtype
#         self._size = size

#     @property
#     def dtype(self):
#         """access dtype, include preprocessing"""
#         return self._dtype

#     @property
#     def size(self):
#         """access size, include preprocessing"""
#         return self._size

#     @property
#     def name(self):
#         """access name, include preprocessing"""
#         if self.size is None:
#             return self._name
#         return f"{self._dtype}[{self._size}] {self._name}"

#     def name_access(self):
#         """name-like access"""
#         return f"{self._name}[]"

#     def array_access(self, index):
#         """array-like access"""
#         if self.size is None:
#             raise TypeError("Cannot access Scalar as Array type")
#         return f"{self.name}[{index}]"

#     def scalar_access(self):
#         """array-like access"""
#         if self.size is not None:
#             raise TypeError("Cannot access Array as Scalar type")
#         return f"{self.name}"

#     def assign(self, expression):
#         """assign to the constant somewhere in the code"""
#         return f"{self.name} = {expression}"

#     def initialize(self):
#         """initialization line"""


class LibRoutineVariable:
    """Any kind of variable used in the library"""

    _VAR_IDENTIFIER = "GENERIC"

    def __init__(self, name, size):
        self._name = name
        self._size = size

    def __str__(self):
        if self._size is None:
            return f"{self._name}"
        return f"{self._name}[{self._size}]"

    @property
    def name(self):
        """access name attribute"""
        return self._name

    @property
    def size(self):
        """access size attribute"""
        return self._size

    @property
    def vtype(self):
        """access variable type"""
        return self._VAR_IDENTIFIER


class LibRoutineLocalVariable(LibRoutineVariable):
    """Any kind of variable used in the library"""

    _VAR_IDENTIFIER = "LOCAL"

    # if this ever becomes a dict, it must be weak!
    _class_namepool: Set[str] = set()

    @staticmethod
    def autoname(namepool: Set[str], prefix="tmp"):
        """autogenerate a name"""
        num = 0
        while True:
            name = f"{prefix}{num}"
            if name not in namepool:
                break
            num += 1
        namepool.add(name)
        return name

    def __init__(self, size=None, namepool=None, prefix="tmp"):
        if namepool is None:
            namepool = self.__class__._class_namepool
        self._namepool = namepool
        super().__init__(
            name=self.autoname(namepool=namepool, prefix=prefix), size=size
        )

    def discard_name(self):
        """discard the name in the namepool"""
        try:
            self._namepool.remove(self._name)
        except KeyError:
            pass

    def __del__(self):
        self.discard_name()

    def __init_subclass__(cls, namepool=None):
        if namepool is None:
            namepool = set()
        cls._class_namepool = namepool


class LibRoutineCounter(LibRoutineLocalVariable):
    """An integer type variable made for iterating through an array"""

    _VAR_IDENTIFIER = "COUNTER"

    # it can be associated with a range-like source, such as a loop or the grid/block ID on GPUs
    # maybe let it rise like other variables and introduce a "handled" flag that is true once the
    # looping structure has been enabled, which may still require proper initialization.

    # i need to make sure, that there cannot be a situation, where the counter rises from multiple
    # blocks but is handled within only one of them. Maybe keep track of the to be handled counters
    # in the CodeSegments rather than the variables?
    # I could think of a pointer that remembers the last segment where the counter was actually
    # needed and places it one segment above, once the counter is finally initialized even further
    # up.

    def __init__(self, origin=None, size=None, namepool=None, prefix="tmp"):
        super().__init__(size=size, namepool=namepool, prefix=prefix)
        if origin is None:
            raise ValueError("Counter requires origin.")
        self._origin = origin


class LibRoutineInputVariable(LibRoutineVariable):
    """Input Variable. Potentially includes Read-Only behaviour"""

    _VAR_IDENTIFIER = "INPUT"

    # in some languages, input variables are treated differently than output.
    # inputs are assumed constant


class LibRoutineOutputVariable(LibRoutineVariable):
    """Output Variable. Potentially includes Auto Initialization"""

    _VAR_IDENTIFIER = "OUTPUT"

    # in some languages, output variables are treated differently than input.
    # outputs are assumed read-write, or inout and not constant


class LibRoutineConstant(LibRoutineVariable):
    """A constant that can appear somewhere in the libroutine"""

    # the idea of a constant is that this representative class also contains the associated values
    # and the constant is initialized somewhere

    # maybe introduce the is_set flag? -> no, instead set constants right within the same header
    # that they are defined in!
    # Also, some ideas of counters transfer, they have to be both initialized and handled in potentially
    # differnt places.

    _VAR_IDENTIFIER = "CONSTANT"

    def __init__(self, name, *content, size=None):
        super().__init__(name=name, size=size)
        self._content = list(content)

    @property
    def content(self):
        """access content"""
        if self._size is None:
            return self._content[0]
        return list(self._content)

    def append(self, value):
        """append a value"""
        if self._size is None:
            raise ValueError("Cannot append to a scalar")
        self._content.append(value)
        self._size = len(self._content)


# class LibRoutineExternal(LibRoutineConstant):
#     """An external function or library"""

#     _VAR_IDENTIFIER = "EXTERNAL"


if __name__ == "__main__":
    othernamepool: Set[str] = set()
    a = None
    b = None
    c = None
    d = None
    a = LibRoutineLocalVariable(1)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    b = LibRoutineLocalVariable(2)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    c = LibRoutineLocalVariable()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    a = None
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    a = LibRoutineLocalVariable(1)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    d = LibRoutineLocalVariable(1)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    a = None
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    c = None
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    y = LibRoutineLocalVariable(8, namepool=othernamepool)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
    x = LibRoutineLocalVariable(8, namepool=othernamepool)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namepool,
        len(LibRoutineLocalVariable._class_namepool),
        othernamepool,
    )
