"""
#autogenerated#header#do#not#modify############################################
#
# File:        library.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 29/11/2024, 16:58
# Version:     0.0.18
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """
Library module description

I thought about library objects but now I rephrase my thoughts into the idead
of LibraryManagers. Python Libraries can have their own library manager but the
actual libraries are not represented by it, that's why 'Library' would be 
misleading.
"""


class LibraryManager:
    """
    Library manager class description.

    Used to create, manage, adapt and compile libraries.
    """

    def __init__(self):
        self._routines = []

    def append(self, routine):
        """append a routine to the library"""

    def compile(self):
        """compile the library"""


class PythonLibraryManager(LibraryManager):
    """
    The object managing a library that then can be loaded to python.
    This is NOT the library itself!
    """
