"""
#autogenerated#header#do#not#modify############################################
#
# File:        lrvariable.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   04/02/2025
# Last Update: 29/04/2025, 19:43
# Version:     0.0.656
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

import gc

import weakref
from typing import Dict


class Namespace:
    """manages the handling of namespaces"""

    def __init__(self, parent=None):
        # self._content: weakref.WeakValueDictionary[
        #     str, LibRoutineVariable
        # ] = weakref.WeakValueDictionary()
        # if this is weak, the namespace probably cannot remember temp variables that
        # have been set in another branch
        self._content = {}
        self._parent = parent
        self._assigned: Dict[type, Dict[str, LibRoutineVariable]] = {}

    def __contains__(self, element: LibRoutineVariable) -> bool:
        if element in self._content:
            return True
        if self._parent is not None:
            return self._parent.__contains__(element)
        return False

    def assign(self, ivariable_type, key, lvariable):
        """assign an instruction variable class to a libroutine variable"""
        if ivariable_type not in self._assigned:
            self._assigned[ivariable_type] = {}
        self._assigned[ivariable_type][key] = lvariable

    def add(self, variable: LibRoutineVariable):
        """add a variable to the namespace"""
        self._content[variable.name] = variable

    def add_new(self, variable: LibRoutineVariable):
        """add a variable to the namespace. Make sure it is not yet defined"""
        if variable.name in self:
            raise ValueError(f"Variable '{variable.name}' already exists")
        self._content[variable.name] = variable

    def remove(self, variable: LibRoutineVariable):
        """add a variable to the namespace"""
        del self._content[variable.name]

    def get_all_content(self):
        """get all content from self and parents"""
        yield from self._content.values()
        if self._parent is not None:
            yield from self._parent.get_all_content()

    @staticmethod
    def combine_name(name, prefix=None, suffix=None):
        """combine a name from prefix, base and suffix"""
        if prefix is not None:
            name = f"{prefix}_{name}"
        if suffix is not None:
            name = f"{name}_{suffix}"
        return name

    @staticmethod
    def wrap_name_combine(func):
        def wrapper(self, name, *args, prefix=None, suffix=None, **kwargs):
            name = Namespace.combine_name(name, prefix=prefix, suffix=suffix)
            return func(self, name, *args, **kwargs)

        return wrapper

    def autoname(self, name, prefix=None, suffix=None, enum_first=False):
        """automatically generate a name from base, prefix and suffix"""
        cname = self.combine_name(name, prefix=prefix, suffix=suffix)
        num = 0
        if enum_first:
            out = f"{cname}{num}"
        else:
            out = cname
        while out in self._content:
            num += 1
            out = f"{cname}{num}"
        return out

    def find(self, name, exception_existing=True):
        """find a variable in the namespace"""
        if name in self._content:
            return self._content[name]
        if self._parent is not None:
            return self._parent.find(name)
        if exception_existing:
            raise KeyError(f"variable {name} not found")
        return None

    def find_assignment_dict(self, ivariable_type, exception_existing=True):
        """find a variable in the namespace"""
        if ivariable_type in self._assigned:
            return self._assigned[ivariable_type]
        if self._parent is not None:
            return self._parent.find_assignment_dict(ivariable_type)
        if exception_existing:
            raise KeyError(
                f"instruction variable {ivariable_type} not assigned."
            )
        return None

    def find_assignment(self, ivariable_type, key, exception_existing=True):
        """find a variable in the namespace"""
        assignment_dict = self.find_assignment_dict(
            ivariable_type, exception_existing=exception_existing
        )
        if key not in assignment_dict:
            if exception_existing:
                raise KeyError(
                    f"assignment of instruction variable {ivariable_type} does not provide key {key}."
                )
            return None
        return assignment_dict[key]

    def _get_fixed_name(self, name, origin):
        """generate a unique variable name from a standardized recipe"""
        caps = "".join([c for c in type(origin).__name__ if c.isupper()])
        myhash = f"{caps.lower()}"
        return f"{name}_{myhash}"

    def _get_temp_name(self, name, origin):
        """generate a reusable variable name from a standardized recipe"""
        caps = "".join([c for c in type(origin).__name__ if c.isupper()])
        myhash = f"{caps.lower()}"
        return f"{name}_{myhash}L{origin.level}"

    def request_fixed(self, generating, name, origin, **genargs):
        """
        Get a fixed name variable. Look it up or generate.
        """
        name = self._get_fixed_name(name, origin)
        if name in self:
            return self.find(name)
        temp = generating(name=name, namespace=self, **genargs)
        return temp

    def request_temp(self, generating, name, origin, **genargs):
        """
        Get a temporary variable. Look it up or generate.
        Has a fixed name with an additional level specifier.
        """
        name = self._get_temp_name(name, origin)
        if name in self:
            return self.find(name)
        temp = generating(name=name, namespace=self, **genargs)
        return temp

    def request_variable(
        self,
        generating,
        name,
        size,
        dtype="f64",  # in genargs
        **genargs,
    ):
        """
        Request a general variable.
        This is an auxilliary function that fills the namespace and som
        defaults
        """
        variable = generating(
            name,
            namespace=self,
            size=size,
            dtype=dtype,
            # enum_first=enum_first,  # in genargs if required
            **genargs,
        )
        return variable

    def __len__(self) -> int:
        return len(self._content)

    def __str__(self):
        return (
            "{"
            + str(", ".join(var.name for var in self._content.values()))
            + "}"
        )

    def inherit(self):
        """inherit into a new namespace that is contained in self"""
        return type(self)(parent=self)


class LibRoutineVariable:
    """Any kind of variable used in the library"""

    _VAR_IDENTIFIER = "GENERIC"
    _CLASS_BASE = "var"

    # some public globals to handle status
    STATUS_INPUT = 1
    STATUS_OUTPUT = 2
    STATUS_INOUT = STATUS_INPUT | STATUS_OUTPUT

    _class_namespace = Namespace(None)
    # if this ever becomes a dict, it must be weak!

    def __init__(
        self,
        name=None,
        *,
        size=None,
        namespace=None,
        prefix=None,
        suffix=None,
        dtype="f64",
        status=0,
    ):
        if name is None:
            name = type(self)._CLASS_BASE
        if namespace is None:
            self._namespace = type(self)._class_namespace
        else:
            self._namespace = namespace
        aname = self._namespace.autoname(
            name=name,
            prefix=prefix,
            suffix=suffix,
        )
        assert aname not in self._namespace
        assert aname is not None
        self._name = aname
        self._size = size
        self._dtype = dtype
        self._status = status
        self._dependencies = set()
        # do not automatically add if explicit namespace is given!
        if namespace is None:
            self._namespace.add(self)
            # add to namespace if it is not explicitely given, assuming
            # adding to default class namespace.

        self.handle_dependencies()

    def handle_dependencies(self):
        """handle the dependencies of the variable"""
        # overwrite in subclass if required
        pass

    def use_as_input(self):
        """use the variable as an input"""
        self._status |= type(self).STATUS_INPUT  # set the first bit in status

    def use_as_output(self):
        """use the variable as an output"""
        self._status |= type(
            self
        ).STATUS_OUTPUT  # set the second bit in status

    def release(self):
        """release the variable, which means that is can be used somewhere else"""
        self._free_name()

    def _free_name(self):
        """discard the name in the namespace"""
        try:
            self._namespace.remove(self)
        except KeyError:
            pass
            # print("not found in namespace")
        except AttributeError:
            print("this should not have happened.")

    def __str__(self):
        if self.is_scalar:
            return f"{self.name}"
        return f"{self.name}[{self.size}]"

    def __repr__(self):
        return self.name

    def __init_subclass__(cls, prefix=None):
        if prefix is not None:
            cls._CLASS_BASE = prefix

    def __del__(self):
        self.release()

    @staticmethod
    def process_offsets(
        *offsets,
        simplify=True,
        allow_strings=False,
    ):
        offset_str_list = []
        offset_int = 0
        for offset in offsets:
            if isinstance(offset, int):
                if simplify:
                    offset_int += offset
                else:
                    offset_str_list.append(str(offset))
            elif isinstance(offset, LibRoutineVariable):
                if offset.size is not None:
                    raise ValueError(
                        "only scalar offsets are allowed in this context"
                    )
                offset_str_list.append(offset.expr)
            else:
                if allow_strings:
                    offset_str_list.append(str(offset))
                else:
                    raise ValueError(
                        f"offset {offset} is not an integer or LibRoutineVariable"
                    )
        if simplify:
            if offset_int > 0:
                offset_str_list.append(str(offset_int))
        if not offset_str_list:
            offset_str_list = ["0"]
        return offset_str_list

    def get_definition_lines(self) -> str:
        """create the line that defines the variable"""
        status = "??"
        if self.status & type(self).STATUS_INPUT:
            status = "RO"
        if self.status & type(self).STATUS_OUTPUT:
            status = "WO"
        if self.status & type(self).STATUS_INOUT:
            status = "RW"
        if self.size is None:
            yield f":DEFINE {status} {self.datatype} {self.name}"
        else:
            yield f":DEFINE {status} {self.datatype} {self.name}[{self.size}]"

    def as_argument(self):
        """get the variable as an argument for a function"""
        return self.name

    def lookup_dtype(self, dtype):
        """lookup the dtype specifier"""
        return dtype

    @property
    def name(self):
        """access name attribute"""
        return self._name

    @property
    def is_scalar(self):
        """return boolean deciding whether the variable is a scalar"""
        return self._size is None

    @property
    def size(self):
        """access size attribute"""
        return self._size

    @property
    def dtype(self):
        """access datatype attribute"""
        return self._dtype

    @property
    def datatype(self):
        """access datatype attribute"""
        return self.lookup_dtype(self._dtype)

    @property
    def dependencies(self):
        """access dependencies"""
        yield from self._dependencies

    def depends_on(self, other):
        """append a dependency"""
        self._dependencies.add(other)

    @property
    def status(self):
        """access the status binary set as integer"""
        return self._status

    @property
    def vtype(self):
        """access variable type"""
        return self._VAR_IDENTIFIER

    def expr_at(
        self,
        *offsets,
        simplify=True,
        allow_strings=False,
    ):
        """expression at offset"""
        if self.is_scalar:
            raise ValueError("Scalar does not provide index access")

        offset_str_list = self.process_offsets(
            *offsets,
            simplify=simplify,
            allow_strings=allow_strings,
        )

        offset_str = " + ".join(offset_str_list)
        return f"{self.name}[{offset_str}]"

    def expr(self):
        """expression for the whole variable"""
        return f"{self.name}"


class LibRoutineImport(LibRoutineVariable):
    """
    An import. Maybe part of the variable concept in a broader sense.
    When a routine, variable or macro is used that has to be imported,
    it can be provided like that and ultimately requested
    """

    _VAR_IDENTIFIER = "IMPORT"
    _CLASS_BASE = "imp"

    def __init__(self, libroutine, *args, **kwargs):
        super().__init__(
            *args, **kwargs, status=LibRoutineVariable.STATUS_INPUT
        )
        self._libroutine = libroutine


class LibRoutineLocalVariable(LibRoutineVariable):
    """Any kind of variable used in the library"""

    _VAR_IDENTIFIER = "LOCAL"
    _CLASS_BASE = "loc"

    def __init__(self, *args, **kwargs):
        super().__init__(
            *args, **kwargs, status=LibRoutineVariable.STATUS_INOUT
        )


class LibRoutineMultiFrame:
    """
    An integer type variable made for iterating through an array or instructions,
    assuming order does not matter!
    """

    _VAR_IDENTIFIER = "MultiFrame"
    _CLASS_BASE = "mfr"

    # it can be associated with a range-like source, such as a loop or the grid/block ID on GPUs
    # maybe let it rise like other variables and introduce a "handled" flag that is true once the
    # looping structure has been enabled, which may still require proper initialization.
    # this is the counter object, not the lookup object. Each parallel environment will have
    # exactly one of these.

    def __init__(
        self, multiplicity, container=None, namespace=None, prefix=None
    ):
        if container is None:
            raise ValueError("MultiFrame requires Kernelize container.")
        super().__init__(
            size=None,
            namespace=container.context.namespace,
            prefix=prefix,
            status=2,
            dtype="i32",
        )

        # the container that the frame selector is attached to
        self._container = container
        self._multiplicity = multiplicity
        self._value = None
        self._local = None
        # self._default_value = 0

    def expr(self):
        """expression for the whole variable"""
        return f"{self.local.expr}"

    def create_representative(
        self,
        local_variable_class=None,
        context=None,
        prefix=None,
        dtype="i32",
        size=None,
    ):
        """create the frame selector from a class"""
        if local_variable_class is None:
            raise ValueError("No class provided")
        if context is None:
            raise ValueError("No context provided")
        if self._local is None:
            self._local = local_variable_class(
                namespace=context.namespace,
                size=size,
                prefix=prefix,
                dtype=dtype,
            )
            context.container.requires(self.local)
        return self

    @property
    def local(self):
        """access the local representation of the frame selector"""
        return self._local

    def set_value(self, value):
        """
        Set the source of the value of the frame selectors local representation.
        Can be an expression, a constant, a parameter, ...
        """
        self._value = value

    """
    IDEA
    After the kernel's instructions are prepared, all multiframe objects should be known.
    Therefore they can be mapped to inner iterators and outer iterators, i.e.
    threadIdx, ... and loops outside the call.
    The simplest way is to let KernelParameters rise and be captured in the kernelize
    container, where then the call is managed. Even easier would be a get_kernel_params
    routine, that could later involve shared memory and more. No more captures and simple
    integers. I think I prefer that.
    The kernelize container could have a box for loops that cover all kernelparameters
    that are not handled by inner parameters such as threadIdx etc. The proper call can be
    derived from kernel parameters and call parameters, where inner and outer parameters
    could be separated and then remerged. In kernalize, local variables could be introduced
    that are assigned to the loops and automatically put into the right place.
    """


class LibRoutineAssignedVariable(LibRoutineVariable):
    """
    Anything that is IO and therefore considered to appear in a routines
    argument list.

    At this point I was uncertain whether an auxilliary variable can be an
    argument to the routine. So far being an argument to a routine is a
    privilege to IO variables, and as of now these are bound to instruciton
    variables. I prefer that idea, so any routine is always defined based on
    stuff that also exists on the abstract level of instructions.
    A case where such an auxilliary buffer could be required is when
    collecting data from parallel branches to avoid race conditions. If
    something like that occurs, I might implement an IO buffer subclass here.
    As such routines will exclusively be internal auxilliaries, I might
    never need to request the instruction variable or the key from there,
    so these buffer types can go with "None".
    """

    _VAR_IDENTIFIER = "ASSIGNED"
    _CLASS_BASE = "asd"

    def __init__(
        self,
        *args,
        assignment,
        status=LibRoutineVariable.STATUS_INOUT,
        **kwargs,
    ):
        super().__init__(*args, status=status, **kwargs)
        # keep a reference to the thing that the variable is assigned to
        self._assignment = assignment


class LibRoutineInputVariable(LibRoutineAssignedVariable):
    """Input Variable. Potentially includes Read-Only behaviour"""

    _VAR_IDENTIFIER = "INPUT"
    _CLASS_BASE = "inp"

    # in some languages, input variables are treated differently than output.
    # inputs are assumed constant

    def __init__(
        self,
        instruction_variable,
        key,
        *args,
        **kwargs,
    ):
        super().__init__(
            *args,
            assignment=(instruction_variable, key),
            status=LibRoutineVariable.STATUS_INPUT,
            **kwargs,
        )


class LibRoutineOutputVariable(LibRoutineAssignedVariable):
    """Output Variable. Potentially includes Auto Initialization"""

    _VAR_IDENTIFIER = "OUTPUT"
    _CLASS_BASE = "out"

    # in some languages, output variables are treated differently than input.
    # outputs are assumed read-write, or inout and not constant

    def __init__(
        self,
        instruction_variable,
        key,
        *args,
        **kwargs,
    ):
        super().__init__(
            *args,
            assignment=(instruction_variable, key),
            status=LibRoutineVariable.STATUS_OUTPUT,
            **kwargs,
        )


class LibRoutineInOutVariable(LibRoutineAssignedVariable):
    """Output Variable. Potentially includes Auto Initialization"""

    _VAR_IDENTIFIER = "INOUT"
    _CLASS_BASE = "ref"

    # in some languages, in/out variables are treated differently than input.
    # outputs are assumed read-write, or inout and not constant

    def __init__(
        self,
        instruction_variable,
        key,
        *args,
        **kwargs,
    ):
        super().__init__(
            *args,
            assignment=(instruction_variable, key),
            status=LibRoutineVariable.STATUS_INOUT,
            **kwargs,
        )


# class LibRoutineIOBuffer(LibRoutineIOVariable):
#     """
#     A buffer for temp stuff, workspace, reduction container, ...

#     Might refer to an IO or some other meta data container, let's see.
#     """

#     _VAR_IDENTIFIER = "IOBUFFER"
#     _CLASS_BASE = "iob"


class LibRoutineConstant(LibRoutineVariable):
    """A constant that can appear somewhere in the libroutine"""

    # the idea of a constant is that this representative class also contains the associated values
    # and the constant is initialized somewhere

    # maybe introduce the is_set flag? -> no, instead set constants right within the same header
    # that they are defined in!
    # Also, some ideas of counters transfer, they have to be both initialized and handled in potentially
    # differnt places.

    _VAR_IDENTIFIER = "CONSTANT"
    _CLASS_BASE = "cns"

    def __init__(self, name, value, size=None):
        if size is None:
            if hasattr(value, "__iter__"):
                self._value = value
                size = len(value)
            else:
                self._value = value
        else:
            if not hasattr(value, "__iter__"):
                raise ValueError("value must be iterable.")
            if len(value) != size:
                raise ValueError("value size does not match the given size.")
            self._value = value

        super().__init__(
            name=name,
            size=None,
            namespace=None,
            prefix=None,
            suffix=None,
            status=1,
        )

    @property
    def value(self):
        """access value"""
        if self.is_scalar:
            return self._value
        return list(self._value)

    @property
    def values(self):
        """access value"""
        if self.is_scalar:
            raise ValueError(
                "Cannot access multiple values of a scalar variable."
            )
        yield from self._value

    def append(self, value):
        """append a value"""
        if self.is_scalar:
            raise ValueError("Cannot append to a scalar variable.")
        self._value.append(value)
        self._size = len(self._value)


# class LibRoutineExternal(LibRoutineConstant):
#     """An external function or library"""

#     _VAR_IDENTIFIER = "EXTERNAL"


if __name__ == "__main__":
    thisnamespace = Namespace(None)
    othernamespace = Namespace(None)
    a = None
    b = None
    c = None
    d = None
    a = LibRoutineLocalVariable(size=1)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    b = LibRoutineInputVariable(None, None, name="foo", size=42)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    c = LibRoutineLocalVariable()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    gc.collect()
    a._free_name()
    a = None
    print("resetted a")
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    a = LibRoutineLocalVariable(size=4)
    gc.collect()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    d = LibRoutineLocalVariable(size=1)
    gc.collect()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    a = None
    gc.collect()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    c = None
    gc.collect()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    print("check out other namespace now")
    y = LibRoutineLocalVariable(size=8, namespace=othernamespace)
    gc.collect()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    othernamespace.add(y)
    gc.collect()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    x = LibRoutineLocalVariable(size=8, namespace=othernamespace)
    othernamespace.add(x)
    gc.collect()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    x.release()
    del x
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )

    print(
        len(LibRoutineLocalVariable._class_namespace),
    )
