"""
#autogenerated#header#do#not#modify############################################
#
# File:        libroutine.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   03/02/2025
# Last Update: 18/06/2025, 13:47
# Version:     0.0.296
#
#################################################end#of#autoheader#do#not#modify


"""
