"""
#autogenerated#header#do#not#modify############################################
#
# File:        lrvariable.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   04/02/2025
# Last Update: 18/03/2025, 19:16
# Version:     0.0.268
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from typing import Set

# import weakref


class LibRoutineVariable:
    """Any kind of variable used in the library"""

    _VAR_IDENTIFIER = "GENERIC"
    _CLASS_BASE = "var"

    _class_namespace: Set[LibRoutineVariable] = set()
    # if this ever becomes a dict, it must be weak!

    def __init__(
        self,
        size=None,
        name=None,
        namespace=None,
        prefix=None,
        suffix=None,
    ):
        if namespace is None:
            namespace = type(self)._class_namespace
        self._namespace = namespace
        if name is None:
            name = type(self)._CLASS_BASE
        name = type(self).autoname(
            namespace=namespace,
            base=name,
            prefix=prefix,
            suffix=suffix,
        )
        assert name is not None
        assert name not in namespace
        self._name = name
        self._size = size
        self._namespace.add(self)

    def __str__(self):
        if self._size is None:
            return f"{self._name}"
        return f"{self._name}[{self._size}]"

    def __repr__(self):
        return str(self)

    @classmethod
    def autoname(
        cls,
        namespace: Set[LibRoutineVariable] | None,
        base=None,
        prefix=None,
        suffix=None,
    ):
        """autogenerate a name"""
        if base is None:
            base = cls._CLASS_BASE
        name = base
        if prefix is not None:
            name = f"{prefix}_{name}"
        if suffix is not None:
            name = f"{name}_{suffix}"
        if namespace is None:
            namespace = cls._class_namespace
        assert namespace is not None
        num = 0
        out = name
        while True:
            if out not in [var.name for var in namespace]:
                break
            num += 1
            out = f"{name}{num}"
        return out

    def free_name(self):
        """discard the name in the namespace"""
        try:
            self._namespace.remove(self)
        except KeyError:
            pass
        except AttributeError:
            print("fooo")

    @property
    def name(self):
        """access name attribute"""
        return self._name

    @property
    def size(self):
        """access size attribute"""
        return self._size

    @property
    def vtype(self):
        """access variable type"""
        return self._VAR_IDENTIFIER

    def __del__(self):
        self.free_name()

    def __init_subclass__(cls, prefix=None, namespace=None):
        if namespace is None:
            namespace = set()
        if prefix is not None:
            cls._CLASS_BASE = prefix
        cls._class_namespace = namespace

    def expr_at_offset(self, offset):
        """expression at offset"""
        return f"{self._name}[{offset}]"

    def expr(self):
        """expression for the variable"""
        return f"{self._name}"

    def __format__(self, formatstr):
        """here happens the magic"""
        # TODO


class LibRoutineLocalVariable(LibRoutineVariable):
    """Any kind of variable used in the library"""

    _VAR_IDENTIFIER = "LOCAL"
    _CLASS_BASE = "loc"


class LibRoutineFrameSelectVariable(LibRoutineLocalVariable):
    """An integer type variable made for iterating through an array"""

    _VAR_IDENTIFIER = "FRAMESELECT"
    _CLASS_BASE = "frm"

    # it can be associated with a range-like source, such as a loop or the grid/block ID on GPUs
    # maybe let it rise like other variables and introduce a "handled" flag that is true once the
    # looping structure has been enabled, which may still require proper initialization.
    # this is the counter object, not the lookup object. Each parallel environment will have
    # exactly one of these.

    def __init__(self, origin=None, size=None, namespace=None, prefix=None):
        super().__init__(size=size, namespace=namespace, prefix=prefix)
        if origin is None:
            raise ValueError("FrameSelector requires origin.")
        self._origin = origin


class LibRoutineInputVariable(LibRoutineVariable):
    """Input Variable. Potentially includes Read-Only behaviour"""

    _VAR_IDENTIFIER = "INPUT"
    _CLASS_BASE = "inp"

    # in some languages, input variables are treated differently than output.
    # inputs are assumed constant


class LibRoutineOutputVariable(LibRoutineVariable):
    """Output Variable. Potentially includes Auto Initialization"""

    _VAR_IDENTIFIER = "OUTPUT"
    _CLASS_BASE = "out"

    # in some languages, output variables are treated differently than input.
    # outputs are assumed read-write, or inout and not constant


class LibRoutineInpOutVariable(LibRoutineVariable):
    """Output Variable. Potentially includes Auto Initialization"""

    _VAR_IDENTIFIER = "INPOUT"
    _CLASS_BASE = "ref"

    # in some languages, output variables are treated differently than input.
    # outputs are assumed read-write, or inout and not constant


class LibRoutineConstant(LibRoutineVariable):
    """A constant that can appear somewhere in the libroutine"""

    # the idea of a constant is that this representative class also contains the associated values
    # and the constant is initialized somewhere

    # maybe introduce the is_set flag? -> no, instead set constants right within the same header
    # that they are defined in!
    # Also, some ideas of counters transfer, they have to be both initialized and handled in potentially
    # differnt places.

    _VAR_IDENTIFIER = "CONSTANT"
    _CLASS_BASE = "const"

    def __init__(self, name, value, size=None):
        if size is None:
            if hasattr(value, "__iter__"):
                self._value = value
                size = len(value)
            else:
                self._value = [value]
        else:
            if not hasattr(value, "__iter__"):
                raise ValueError("value must be iterable.")
            if len(value) != size:
                raise ValueError("value size does not match the given size.")
            self._value = value

        super().__init__(
            name=name,
            size=None,
            namespace=None,
            prefix=None,
            suffix=None,
        )

    @property
    def value(self):
        """access value"""
        if self._size is None:
            return self._value[0]
        return list(self._value)

    def append(self, value):
        """append a value"""
        self._value.append(value)
        self._size = len(self._value)


# class LibRoutineExternal(LibRoutineConstant):
#     """An external function or library"""

#     _VAR_IDENTIFIER = "EXTERNAL"


if __name__ == "__main__":
    othernamespace: Set[str] = set()
    a = None
    b = None
    c = None
    d = None
    a = LibRoutineLocalVariable(1)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    b = LibRoutineInputVariable(42)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    c = LibRoutineLocalVariable()
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    a = None
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    a = LibRoutineLocalVariable(1)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    d = LibRoutineLocalVariable(1)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    a = None
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    c = None
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    y = LibRoutineLocalVariable(8, namespace=othernamespace)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    x = LibRoutineLocalVariable(8, namespace=othernamespace)
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
    x.free_name()
    del x
    print(
        "\t".join(map(lambda x: f"{str(x):^10s}", [a, b, c, d])),
        "\t:\t",
        LibRoutineLocalVariable._class_namespace,
        len(LibRoutineLocalVariable._class_namespace),
        othernamespace,
    )
