"""
#autogenerated#header#do#not#modify############################################
#
# File:        makefile.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   09/12/2024
# Last Update: 03/06/2025, 16:14
# Version:     0.0.472
#
#################################################end#of#autoheader#do#not#modify


NOTES
=====

In MakeFileManager, the associated Targets are extracted from the LibRoutines
that a library depends on.

A Library is added to known targets when it has been loaded the first time. If it is
required as a target again, no duplicates shall be created.

To stay within the makefile ecosystem, a makefile target can only depend on another 
makefile target. The lookup system is generalized to a key based system and I will start
with names.

Therefore, a makefile can be automatically created.

"""


import warnings


def no_duplicates(listlike):
    """generate a list without duplicates that conserves order"""
    ret = []
    for llike in listlike:
        if llike in ret:
            continue
        ret.append(llike)
    return ret


class MakeFileManager:
    """manages creation, execution and design of makefiles"""

    def __init__(self, name, **_):
        self.name = name
        self._filename = f"Makefile_{name}"
        self._is_created = False
        self._targets = {}
        self._cleanable = []
        self._make_all = []

    def set_filename(self, filename):
        """set the makefile's filename"""
        self._filename = filename
        self._is_created = False

    def create_file(self):
        """create the file"""
        self._is_created = True

    def append(self, target):
        """append, avoid duplicates"""
        if target.target_name() not in self._targets:
            self._targets[target.target_name()] = target

    def get_makefile_lines(self):
        """get the lines that go to the actual makefile"""
        for target in self.all_targets():
            yield from self.filter_double_space(
                target.target_get_makefile_lines()
            )
            yield ""

    def execute_file(self):
        """execute the makefile"""
        if not self._is_created:
            self.create_file()

    def filter_double_space(self, generatorlike):
        """filter out double spaces to make the files look nicer"""
        for tline in generatorlike:
            nline = ""
            while True:
                nline = tline.replace("  ", " ")
                if nline == tline:
                    break
                tline = nline
            yield nline

    def targets_with_dependencies(self):
        """get all targets with potential dependencies"""
        for _, targ in self._targets.items():
            yield from targ.get_dependencies()
            yield targ

    def manage_targets(self, iterable):
        """manage the targets: group them and remove duplicates"""
        groups = {}
        for targ in iterable:
            identifier = targ.get_target_group()
            if identifier not in groups:
                groups[identifier] = []
            groups[identifier].append(targ)
        for identifier, targets in sorted(groups.items()):
            yield from no_duplicates(targets)

    def all_targets(self):
        """get all targets, duplicates only once"""
        yield from self.manage_targets(self.targets_with_dependencies())


class _MFIdentifier:
    """an identifier to help identifying groups"""

    _known_identifiers = {}

    @classmethod
    def get(cls, identifier):
        """get identifier"""
        if identifier in cls._known_identifiers:
            return cls._known_identifiers[identifier]
        raise KeyError("unknown identifier")

    @classmethod
    def create(cls, identifier, order=None):
        """create a new identifier, but make sure its unique"""
        if identifier in cls._known_identifiers:
            raise KeyError("duplicated identifier")
        if order is None:
            order = len(cls._known_identifiers)
        new_ident = _MFIdentifier(identifier, order)
        cls._known_identifiers[identifier] = new_ident
        return new_ident

    def __init__(self, ident, order):
        self.ident = ident
        self.order = order

    def __eq__(self, other):
        return self.ident == other.ident

    def __gt__(self, other):
        return self.order > other.order

    def __hash__(self):
        return hash((self.ident, self.order))

    def __str__(self):
        return f"[{self.order}]:{self.ident}"

    def __repr__(self):
        return str(self)


MFGID_GENERC = _MFIdentifier.create("GENERC", order=999)
MFGID_SOURCE = _MFIdentifier.create("SOURCE", order=3)
MFGID_GLBLIB = _MFIdentifier.create("GLBLIB", order=2)
MFGID_PATTRN = _MFIdentifier.create("PATTRN", order=0)
MFGID_SHDLIB = _MFIdentifier.create("SHDLIB", order=7)
MFGID_STCLIB = _MFIdentifier.create("STCLIB", order=9)
MFGID_OBJECT = _MFIdentifier.create("OBJECT", order=5)
MFGID_GENERL = _MFIdentifier.create("GENERL", order=20)


class MakeFileTarget:
    """manages a target in a makefile"""

    TAB = "\t"
    GROUP_IDENTIFIER = _MFIdentifier.get("GENERC")

    def __init__(self, name, dependencies=None):
        self.name = name
        self.path = "."
        if dependencies is None:
            dependencies = []
        for dep in dependencies:
            if not isinstance(dep, MakeFileTarget):
                raise TypeError("dep must be an instance of MakeFileTarget")
        self.dependencies = dependencies

    @classmethod
    def get_target_group(cls):
        """get a group identifier"""
        return cls.GROUP_IDENTIFIER

    def get_dependencies(self):
        """recursively get all depenendcies"""
        for dep in self.dependencies:
            yield from dep.get_dependencies()
            yield dep

    def __eq__(self, other):
        return self.target_name() == other.target_name()

    def __gt__(self, other):
        return self.target_name() > other.target_name()

    def get_incdirs(self):
        """get the include directory path"""
        yield self.path

    def get_libdirs(self):
        """get the library directory path"""
        yield self.path

    def target_name(self):
        """get the proper target name"""
        return self.name

    def include_as(self):
        """get the proper elements how to include the target"""
        return self.name

    def get_glblibs(self):
        """get global libs"""
        return
        yield

    def get_loclibs(self):
        """get local libs"""
        return
        yield

    def get_scfiles(self):
        """get source"""
        return
        yield

    def get_obfiles(self):
        """get object files"""
        return
        yield

    def target_get_makefile_lines(self):
        """get the lines that have to be appended in the makefile"""
        depnames = " ".join(dep.target_name() for dep in self.dependencies)
        yield f"{self.target_name()}: {depnames}"
        for line in self.generate():
            if line is not None:
                yield f"{self.TAB}" + line

    def generate(self, *flags):
        """get the lines that actually generate the target"""
        flags = list(flags)
        return
        yield

    def resolve_dependencies(self):
        """generate the include dirs, lib dirs and the line for dependencies required"""
        incdirs = []
        libdirs = []
        glblibs = []
        loclibs = []
        scfiles = []
        obfiles = []
        for dep in self.dependencies:
            glblibs.extend(list(dep.get_glblibs()))
            loclibs.extend(list(dep.get_loclibs()))
            scfiles.extend(list(dep.get_scfiles()))
            obfiles.extend(list(dep.get_obfiles()))
            incdirs.extend(list(dep.get_incdirs()))
            libdirs.extend(list(dep.get_libdirs()))
        incdirs = no_duplicates(incdirs)
        libdirs = no_duplicates(libdirs)
        glblibs = no_duplicates(glblibs)
        loclibs = no_duplicates(loclibs)
        scfiles = no_duplicates(scfiles)
        return {
            "incdirs": incdirs,
            "libdirs": libdirs,
            "glblibs": glblibs,
            "loclibs": loclibs,
            "scfiles": scfiles,
            "obfiles": obfiles,
        }


# gen = ["Hello  World", "Hello World", "Hello        WOrld"]

# mfm = MakeFileManager("test")
# for line in mfm.filter_double_space(gen):
#     print(line)

# print()
# print()
# for line in mfm.get_makefile_lines():
#     print(line)
