"""
#autogenerated#header#do#not#modify############################################
#
# File:        makefile.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   09/12/2024
# Last Update: 09/12/2024, 16:00
# Version:     0.0.1
#
#################################################end#of#autoheader#do#not#modify


"""


class MakeFileManager:
    """manages creation, execution and design of makefiles"""

    def __init__(self, name):
        self.name = name
        self._filename = f"Makefile_{name}"
        self._is_created = False
        self._targets = []

    def set_filename(self, filename):
        """set the makefile's filename"""
        self._filename = filename
        self._is_created = False

    def create_file(self):
        """create the file"""
        self._is_created = True

    def execute_file(self):
        """execute the makefile"""
        if not self._is_created:
            self.create_file()


class MakeFileTarget:
    """manages a target in a makefile"""

    def __init__(self, name, dependencies=None):
        self.name = name
        if dependencies is None:
            dependencies = []
        for dep in dependencies:
            if not isinstance(dep, MakeFileTarget):
                raise TypeError("dep must be an instance of MakeFileTarget")
        self.dependencies = dependencies

    def get_makefile_lines(self):
        """get the lines that have to be appended in the makefile"""
        depnames = " ".join(dep.name for dep in self.dependencies)
        yield f"{self.name}: {depnames}"
