"""
#autogenerated#header#do#not#modify############################################
#
# File:        plaintext_builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   10/03/2025
# Last Update: 10/04/2025, 11:42
# Version:     0.0.448
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from typing import Any, Dict

from phoenix.fgen.builder import Builder
from phoenix.fgen.codecontainer import (
    CodeLine,
    CommentLine,
    EmbeddingContainer,
    DefinitionContainer,
    LoopContainer,
    RoutineContainer,
    NamedContainer,
    ConditionalContainer,
)
from phoenix.fgen.libroutinevar import LibRoutineLocalVariable

from phoenix.toolbox.logger import GLOBAL_LOGGER

GLOBAL_LOGGER.set_logfile("plaintextbuilder")
GLOBAL_LOGGER.set_loglevel("INFO")
GLOBAL_LOGGER.add_note(
    """
    This is the plain container build that is supposed to be
    used for either parsing or debugging.
    There is no compilation involved.
    """
)
GLOBAL_LOGGER.add_note(
    "So far I have not implemented a proper library environment either"
)
GLOBAL_LOGGER.log_to_stdout(False)


###############################################################################
#
# .oPYo.                   o            o
# 8    8                   8
# 8       .oPYo.  odYo.   o8P  .oPYo.  o8  odYo.  .oPYo.  oPYo.  .oPYo.
# 8       8    8  8' `8    8   .oooo8   8  8' `8  8oooo8  8  `'  Yb..
# 8    8  8    8  8   8    8   8    8   8  8   8  8.      8        'Yb.
# `YooP'  `YooP'  8   8    8   `YooP8   8  8   8  `Yooo'  8      `YooP'
# :.....: :.....: ..::.. ::..: :.....: :.. ..::.. :.....: ..:::: :.....:
# ::::::: ::::::: :::::: ::::: ::::::: ::: :::::: ::::::: :::::: :::::::
# ::::::: ::::::: :::::: ::::: ::::::: ::: :::::: ::::::: :::::: :::::::
###############################################################################


# aux = {"foobar": LibRoutineLocalVariable("foobar", size=42)}
# ind1 = LibRoutineLocalVariable("index1", dtype="i32")
# ind2 = LibRoutineLocalVariable("index2", dtype="i32")


class TestLineWithVariable(CodeLine):
    def __init__(self, line, *args, **kwargs):
        super().__init__(*args, **kwargs)
        temp1 = self.request_temp(
            "test_temporary1", LibRoutineLocalVariable, size=None, dtype="i64"
        )
        temp2 = self.request_temp(
            "test_temporary2", LibRoutineLocalVariable, size=12, dtype="i64"
        )
        self.requires(temp2)
        var = temp2.expr_at(1, temp1, 3, 4, simplify=False)
        longline = f"{line} yadayada 42 + {var}"
        self.set_line(longline)


class PTCodeLine(CodeLine):
    """Plain Text version of a StatementLine"""


class PTCommentLine(CommentLine):
    """Plain Text version of a CommentLine"""

    COMMENT_PREFIX = "#> "


class PTBracketContainer(NamedContainer, EmbeddingContainer):
    """Plain Text version of a EnvironmentContainer"""

    INDENT_BODY = True

    def generate_head_containers(self, **_):
        yield self.codeline_from_text(f"BEGIN {self.name}")

    def generate_foot_containers(self, **_):
        yield self.codeline_from_text(f"END {self.name}")


class PTLoopContainer(LoopContainer):
    """Plain Text version of a DefinitionContainer"""

    INDENT_BODY = True


# class PTRoutineDefinition(RoutineContainer):
#     """Plain Text version of a RoutineDefinition"""

#     # routine definition
#     # variable initialization
#     # body


# class PTLibraryDefinition(RoutineContainer):
#     """Plain Text version of a RoutineDefinition"""

#     # collect all library routines


###############################################################################
#
#  .oPYo.           o  8       8
#  8   `8              8       8
# o8YooP'  o    o  o8  8  .oPYo8  .oPYo.  oPYo.
#  8   `b  8    8   8  8  8    8  8oooo8  8  `'
#  8    8  8    8   8  8  8    8  8.      8
#  8oooP'  `YooP'   8  8  `YooP'  `Yooo'  8
# :......: :.....: :.. .. :.....: :.....: ..::::
# :::::::: ::::::: ::: :: ::::::: ::::::: ::::::
# :::::::: ::::::: ::: :: ::::::: ::::::: ::::::
###############################################################################


class PlainTextBuilder(Builder, identifier="PLAINTEXT"):
    """PlainTextBuilder"""

    def handle_basic_instruction(self, instruction, context, buildargs):
        yield PTCodeLine(
            f"Unknown instruction {instruction}", context, **buildargs
        )

    def handle_group_instruction(self, instruction, context, buildargs):
        outer = PTBracketContainer(
            name=f"GROUP {instruction.identifier}", context=context, **buildargs
        )
        for inner_instruction in instruction.instructions:
            for inner_container in self.containers_from_instruction(
                inner_instruction,
                context=outer.context,
                **buildargs,
            ):
                outer.append(inner_container)
        yield outer

    def handle_content_instruction(self, instruction, context, buildargs):
        outer = PTBracketContainer(
            name=f"Content Group {instruction.identifier}",
            context=context,
            **buildargs,
        )
        for key, value in instruction.items():
            if key in ["identifier", "content"]:
                continue
            outer.append(
                PTCodeLine(
                    f":{key}={value}", context=outer.context, **buildargs
                )
            )
        for inner_instruction in instruction.content:
            for inner_container in self.containers_from_instruction(
                inner_instruction,
                context=outer.context,
                **buildargs,
            ):
                outer.append(inner_container)
        yield outer

    def handle_generic_instruction(self, instruction, context, buildargs):
        yield PTCodeLine(
            f"generic instruction: {instruction.identifier}",
            context=context,
            **buildargs,
        )
        for key, value in instruction.items():
            if key in ["identifier"]:
                continue
            yield PTCodeLine(f":{key}={value}", context=context, **buildargs)
        yield TestLineWithVariable("fooo", context=context, **buildargs)

    def handle_routine_instruction(self, instruction, context, buildargs):
        yield from super().handle_routine_instruction(
            instruction, context, buildargs
        )

    def handle_mapapply_instruction(self, instruction, context, buildargs):
        yield from super().handle_mapapply_instruction(
            instruction, context, buildargs
        )

    def handle_variation_instruction(self, instruction, context, buildargs):
        yield from super().handle_variation_instruction(
            instruction, context, buildargs
        )

    def handle_environment_instruction(self, instruction, context, buildargs):
        yield from super().handle_environment_instruction(
            instruction, context, buildargs
        )


PlainTextBuilder.set_comment_generator(PTCommentLine)


from phoenix.fgen.builder import Context
import sys
from phoenix.fgen.instruction import GenericInstruction, InstructionGroup


a = PlainTextBuilder()

test = InstructionGroup(
    [
        GenericInstruction(foo="bar1", answer=42.1),
        GenericInstruction(foo="bar2", answer=42.2),
        GenericInstruction(foo="bar3", answer=42.3),
        GenericInstruction(foo="bar4", answer=42.4),
        GenericInstruction(foo="bar5", answer=42.5),
    ]
)
ctxt = Context()

largegroup = InstructionGroup([test, test, test])

outer_defarea = DefinitionContainer(context=ctxt)
outer_defarea.add_capture_trigger(lambda x: True)

container_tree = a.create_routine_container(
    "foo", largegroup, context=outer_defarea.context
)
outer_defarea.append(container_tree)

for indent, line in outer_defarea.reset_all().build_all().get_codelines():
    print(indent * "  " + line)

sys.exit()
