"""
#autogenerated#header#do#not#modify############################################
#
# File:        plaintext_builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   10/03/2025
# Last Update: 10/03/2025, 16:55
# Version:     0.0.25
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from typing import Any, Dict

from phoenix.fgen.builder import Builder
from phoenix.fgen.codecontainer import (
    StatementLine,
    CommentLine,
    GroupContainer,
    DefinitionContainer,
    LoopContainer,
    RoutineContainer,
)


class PTStatementLine(StatementLine):
    """Plain Text version of a StatementLine"""

    _DEFAULTS: Dict[str, Any] = {}

    def __init__(self, signature=None, parent=None, **other):
        super().__init__(signature=signature, parent=parent, **other)


class PTCommentLine(CommentLine):
    """Plain Text version of a CommentLine"""

    _DEFAULTS: Dict[str, Any] = {}


class PTGroupContainer(GroupContainer):
    """Plain Text version of a GroupContainer"""

    _DEFAULTS: Dict[str, Any] = {}


class PTEnvironmentContainer(GroupContainer):
    """Plain Text version of a EnvironmentContainer"""

    # do not resolve environments, verbose them

    _DEFAULTS: Dict[str, Any] = {}


class PTLoopContainer(LoopContainer):
    """Plain Text version of a DefinitionContainer"""

    _DEFAULTS: Dict[str, Any] = {}


class PTDefinitionContainer(DefinitionContainer):
    """Plain Text version of a DefinitionContainer"""

    _DEFAULTS: Dict[str, Any] = {}


class PTRoutineDefinition(RoutineContainer):
    """Plain Text version of a RoutineDefinition"""

    _DEFAULTS: Dict[str, Any] = {}

    def __init__(self, signature=None, parent=None, **other):
        super().__init__(signature=signature, parent=parent, **other)


class PlainTextBuilder(Builder, identifier="PLAINTEXT"):
    """PlainTextBuilder"""
