"""
#autogenerated#header#do#not#modify############################################
#
# File:        routine.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 09/10/2024, 16:34
# Version:     0.0.52
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """
Routine module description
==========================

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisl lectus,
gravida ut risus id, tincidunt pretium arcu. Duis tortor nulla, mattis ac leo
id, pharetra imperdiet odio. Aliquam sit amet nisl sed nulla luctus commodo eget
a est. Quisque iaculis sapien eget metus dignissim congue. Suspendisse cursus
orci ex, a malesuada tellus laoreet in. Nulla eu metus vitae nunc vehicula
consequat a ac erat. Phasellus fringilla tristique magna, sed fermentum enim
malesuada eget. Curabitur mauris diam, vehicula ac odio a, lobortis ultrices
dolor. Vivamus posuere, sem in egestas aliquam, lacus lorem aliquet sapien,
quis tincidunt libero sem ac augue. Mauris eget rhoncus urna. Donec dapibus
nulla lacus, at egestas ligula pulvinar nec. Quisque pellentesque fringilla sem
ac molestie. Suspendisse convallis dolor felis. Vestibulum ante ipsum primis in
faucibus orci luctus et ultrices posuere cubilia curae.

"""

import pickle
from phoenix.fgen.tomography import Tomography

# pylint: disable=too-many-arguments


class Routine:
    """Routine class description"""

    def __init__(
        self,
        identifier: str,
        *,
        itype,
        out_var,
        in_vars,
        instruction_group=None,
    ):
        self._identifier = identifier
        self.instruction_group = instruction_group

        self.in_vars = in_vars
        self.out_var = out_var
        self._itype = itype
        self._ready = False

    def __len__(self):
        return len(self.instruction_group)

    @property
    def itype(self):
        """write-protected access to itype"""
        return self._itype

    @property
    def instructions(self):
        """generator through all instructions.
        Forward the call into the instruction into the top level instruction
        group
        """
        yield from self.instruction_group.instructions

    def checksum(self):
        """a checksum to make sure, that the naming is safe"""
        test_tuple = (
            self._identifier,
            self.itype,
            len(self.in_vars),
            self.out_var.get_size(),
            *[inp_var.get_size() for inp_var in self.in_vars],
        )
        return test_tuple

    def from_file(self):
        """get from file"""
        filename = f"routine_{self._identifier}_data.pckl"
        try:
            with open(filename, "rb") as f:
                checksum, instgrp = pickle.load(f)
                if checksum == self.checksum():
                    self.instruction_group = instgrp
                    self._ready = True
                    return self
                else:
                    return False
        except FileNotFoundError:
            return False

    def to_file(self):
        """write to file"""
        filename = f"routine_{self._identifier}_data.pckl"
        with open(filename, "wb") as f:
            pickle.dump((self.checksum(), self.instruction_group), f)

    @staticmethod
    def from_function(
        function,  # generating function
        itype,  # function type
        out_var,  # output var
        in_vars,  # input vars
        identifier=None,  # identifier
        parallel=True,  # use multiple cores for generation
        verbose=False,
        **kwargs,  # catch other arguments if any
    ):
        """generate instructions from function tomography"""

        if identifier is None:
            identifier = function.__name__
        tomography = Tomography.new(itype, out_var, in_vars, **kwargs)

        # change here: tomography will return an instruction group directly
        instruction_group = tomography.apply(
            function,
            verbose=verbose,
            parallel=parallel,
        )
        return Routine(
            identifier=identifier,
            itype=itype,
            out_var=out_var,
            in_vars=in_vars,
            instruction_group=instruction_group,
        )

    @property
    def identifier(self):
        """make the identifier read-only, to conserve association to
        instructions and filenames
        """
        return self._identifier
