"""
#autogenerated#header#do#not#modify############################################
#
# File:        subroutine.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 24/10/2024, 14:54
# Version:     0.0.6
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """
Subroutine module description



"""


class Subroutine:
    """Subroutine class description"""
