"""
#autogenerated#header#do#not#modify############################################
#
# File:        tomography.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 23/10/2024, 09:38
# Version:     0.0.163
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """
Tomography module description
=============================

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisl lectus,
gravida ut risus id, tincidunt pretium arcu. Duis tortor nulla, mattis ac leo
id, pharetra imperdiet odio. Aliquam sit amet nisl sed nulla luctus commodo eget
a est. Quisque iaculis sapien eget metus dignissim congue. Suspendisse cursus
orci ex, a malesuada tellus laoreet in. Nulla eu metus vitae nunc vehicula
consequat a ac erat. Phasellus fringilla tristique magna, sed fermentum enim
malesuada eget. Curabitur mauris diam, vehicula ac odio a, lobortis ultrices
dolor. Vivamus posuere, sem in egestas aliquam, lacus lorem aliquet sapien,
quis tincidunt libero sem ac augue. Mauris eget rhoncus urna. Donec dapibus
nulla lacus, at egestas ligula pulvinar nec. Quisque pellentesque fringilla sem
ac molestie. Suspendisse convallis dolor felis. Vestibulum ante ipsum primis in
faucibus orci luctus et ultrices posuere cubilia curae.

"""


from phoenix.fgen.instruction3 import InstructionGroup, Instruction
from phoenix.keymap import KeyMap


def neutral_generator(inp):
    yield inp


def outer(*lists, _accum=None):
    """
    An outer product of lists.
    yields any combination of exactly one element from every input list.
    During the process, the lists may be iterated through multiple times,
    so in the first call, it converts potential generators into lists.
    """
    if _accum is None:
        # this is the first call. convert into lists and reset _accum
        yield from outer([list(input_list) for input_list in lists], _accum=[])
    if lists:
        # if there's still levels to work on, do another iteration
        for elem in lists[0]:
            yield from outer(*lists[1:], _accum=_accum + [elem])
    else:
        # break recursion here
        yield tuple(_accum)


class Tomography:
    """
    The Tomography class implements a simple analysis tool that, applied to
    functions, extracts information on how these functions work when they are
    fed any combination of potential input arguments from a discrete set.
    """

    itype = None

    def __init__(self, out_var, in_vars, **kwargs):
        self.out_var = out_var
        self.in_vars = in_vars
        try:
            # extract keymap and lock it
            self.out_keymap = self.out_var.KEYMAP.lock()
            self.in_keymaps = [in_var.KEYMAP.lock() for in_var in self.in_vars]
        except AttributeError as exc:
            raise AttributeError(
                "Error accessing keymap for variables"
            ) from exc
        self.kwargs = kwargs
        self.out_ret2key_conv = neutral_generator
        self.in_key2arg_convs = [neutral_generator for _ in in_vars]

    @classmethod
    def new(cls, itype, out_var, in_vars, **kwargs):
        """create a new Tomography object, distinguish by itype"""
        match itype:
            case _:
                # generic tomography
                return Tomography(out_var, in_vars, **kwargs)

    def get_input_keycombs(self):
        """get all input key combinations as tuples"""
        yield from outer(
            *[in_var.KEYMAP.keys(recursive=True) for in_var in self.in_vars]
        )

    def convert_keys_to_args(self, keycomb: tuple):
        """convert the key kombination into proper input arguments"""
        yield from outer(
            *[
                key2inp(key)
                for key2inp, key in zip(self.in_key2arg_convs, keycomb)
            ]
        )

    def convert_ret_to_key(self, value):
        """convert the output into a key and optionally numbers and more"""
        yield from self.out_ret2key_conv(value)

    def to_instruction(self, out_key, *inp_keys, **kwargs):
        """generate an instruction from the converted output and the inputs"""
        return Instruction(
            output_key=out_key,
            **{
                f"input{num}_key": inp_keys[num]
                for num in range(len(inp_keys))
            },
            **kwargs,
        )

    def apply(self, function, parallel=0, verbose=True):
        """apply automatically"""
        all_instructions = []

        # for all key combinations....
        for input_keycombs in self.get_input_keycombs():
            # translate them into input arguments...
            for converted_inps in self.convert_keys_to_args(input_keycombs):
                # feed into function
                return_value = function(*converted_inps)

                # the return value is most likely not a key yet
                for converted_output in self.convert_ret_to_key(return_value):
                    all_instructions.append(
                        self.to_instruction(converted_output, *input_keycombs)
                    )

        return InstructionGroup(all_instructions, itype=self.itype)
