"""
#autogenerated#header#do#not#modify############################################
#
# File:        libroutine_f90.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   03/12/2024
# Last Update: 30/01/2025, 15:12
# Version:     0.0.70
#
#################################################end#of#autoheader#do#not#modify


"""

from phoenix.fgen.library import LibRoutine, LibRoutineLine
from phoenix.fgen.makefile import MakeFileManager

DEFAULT_OPTIONS = {
    "tab": "  ",
}


SR_1IN1OUT_BASE_HEAD = """
SUBROUTINE {subroutine_name}(tgt1_r, tgt1_i, tgt1_n, src1_r, src1_i, src1_n)
{tab}!
{tab}double precision, dimension(tgt1_n), intent(inout) :: tgt1_r
{tab}double precision, dimension(tgt1_n), intent(inout) :: tgt1_i
{tab}integer,                             intent(in)    :: tgt1_n
{tab}!
{tab}double precision, dimension(src1_n), intent(in)    :: src1_r
{tab}double precision, dimension(src1_n), intent(in)    :: src1_i
{tab}integer,                             intent(in)    :: src1_n
{tab}!
"""

SR_1IN1OUT_BASE_FOOT = """
{tab}!
END SUBROUTINE {subroutine_name}
"""

SR_1IN1OUT_BASE_CALL = """
call {subroutine_name}(tgt1_r, tgt1_i, tgt1_n, src1_r, src1_i, src1_n)"""

###############################################################################

SR_1IN1OUT_OFFS_HEAD = """
SUBROUTINE {subroutine_name}(tgt1_r, tgt1_i, tgt1_n, src1_r, src1_i, src1_n, tgt1_offs, src1_offs)
{tab}!
{tab}double precision, dimension(tgt1_n), intent(inout) :: tgt1_r
{tab}double precision, dimension(tgt1_n), intent(inout) :: tgt1_i
{tab}integer,                             intent(in)    :: tgt1_n
{tab}!
{tab}double precision, dimension(src1_n), intent(in)    :: src1_r
{tab}double precision, dimension(src1_n), intent(in)    :: src1_i
{tab}integer,                             intent(in)    :: src1_n
{tab}!
{tab}integer,                             intent(in)    :: tgt1_offs
{tab}integer,                             intent(in)    :: src1_offs
{tab}!
{tab}integer :: tgt1_shft
{tab}integer :: src1_shft
{tab}!
"""

SR_1IN1OUT_OFFS_FOOT = """

END SUBROUTINE {subroutine_name}
"""

SR_1IN1OUT_OFFS_CALL = """
call {subroutine_name}(tgt1_r, tgt1_i, tgt1_n, src1_r, src1_i, src1_n, tgt1_offs, src1_offs)"""

###############################################################################

SR_1IN1OUT_LIST_HEAD = """
SUBROUTINE {subroutine_name}(tgt1_r, tgt1_i, tgt1_n, src1_r, src1_i, src1_n, tgt1_offs, src1_offs)
{tab}!
{tab}double precision, dimension(tgt1_n), intent(inout) :: tgt1_r
{tab}double precision, dimension(tgt1_n), intent(inout) :: tgt1_i
{tab}integer,                             intent(in)    :: tgt1_n
{tab}!
{tab}double precision, dimension(src1_n), intent(in)    :: src1_r
{tab}double precision, dimension(src1_n), intent(in)    :: src1_i
{tab}integer,                             intent(in)    :: src1_n
{tab}!
{tab}integer,                             intent(in)    :: tgt1_offs
{tab}integer,                             intent(in)    :: src1_offs
{tab}!
{tab}integer :: kk
{tab}integer :: tgt1_shft
{tab}integer :: src1_shft
{tab}!
"""

SR_1IN1OUT_LIST_FOOT = """
{tab}!
END SUBROUTINE {subroutine_name}
"""

SR_1IN1OUT_LIST_CALL = """
call {subroutine_name}(tgt1_r, tgt1_i, tgt1_n, src1_r, src1_i, src1_n, tgt1_offs, src1_offs)"""

###############################################################################


class MakefileManagerF90(MakeFileManager):
    """Fortran implementation of the makefile manager"""


class LibRoutineF90(LibRoutine):
    """
    The f90 style subroutines can be composed from a basic scheme, which is
    introduced and recycled here
    """

    code_head = ""
    code_foot = ""
    code_line = ""
    code_call = ""
    code_prmb = ""
    code_post = ""
    implementation = "generic"

    def get_meta(self):
        """return meta information on the library"""
        meta = super().get_meta()
        # potentially extend the meta by fortran specific stuff
        return meta

    def call_as(self, **kwargs):
        """get a string how the function is called in code"""
        options = dict(DEFAULT_OPTIONS)
        options.update(self.get_meta())
        options.update(kwargs)

        for line in self.code_call.split("\n"):
            yield line.format(**options)

    def create_source_lines(self, **kwargs):
        options = dict(DEFAULT_OPTIONS)
        options.update(self.get_meta())
        options.update(kwargs)

        for line in self.code_head.split("\n"):
            yield line.format(**options)

        for line in self.code_prmb.split("\n"):
            yield line.format(**options)

        for instruction in self.get_instructions():
            for line in self.code_line.split("\n"):
                yield line.format(**(options | instruction.to_dict()))

        for line in self.code_post.split("\n"):
            yield line.format(**options)

        for line in self.code_foot.split("\n"):
            yield line.format(**options)


class LibRoutineLineF90(LibRoutineLine):
    pass
