"""
#autogenerated#header#do#not#modify############################################
#
# File:        libroutine_f90.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   03/12/2024
# Last Update: 04/12/2024, 17:38
# Version:     0.0.33
#
#################################################end#of#autoheader#do#not#modify


"""

from phoenix.fgen.library import LibRoutine, MakefileManager

DEFAULT_OPTIONS = {
    "tab": "  ",
}


class MakefileManagerF90(MakefileManager):
    """Fortran implementation of the makefile manager"""


class LibRoutineF90(LibRoutine):
    """
    The f90 style subroutines can be composed from a basic scheme, which is
    introduced and recycled here
    """

    code_head = ""
    code_foot = ""
    code_line = ""
    implementation = "generic"

    def get_meta(self):
        """return meta information on the library"""
        meta = super().get_meta()
        more_meta = {
            # "subroutine_name": self.name,
            # "num_instructions": len(self.routine.instruction_group),
            # "implementation": self.implementation,
            # "identifier": self.identifier,
            # "library": self.identifier,
        }
        meta.update(more_meta)
        return meta

    def create_source_lines(self, **kwargs):
        options = dict(DEFAULT_OPTIONS)
        options.update(self.get_meta())
        options.update(kwargs)

        for line in self.code_head.split("\n"):
            yield line.format(**options)

        for instruction in self.get_instructions():
            for line in self.code_line.split("\n"):
                yield line.format(**(instruction.to_dict() | options))

        for line in self.code_foot.split("\n"):
            yield line.format(**options)
