"""
#autogenerated#header#do#not#modify############################################
#
# File:        makefile.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   09/12/2024
# Last Update: 11/12/2024, 12:51
# Version:     0.0.330
#
#################################################end#of#autoheader#do#not#modify


"""
import warnings
from phoenix.fgen.makefile import MakeFileTarget


class MFTF2Py(MakeFileTarget):
    """Create a .o file made from Fortran source"""

    COMPILER = "f2py3"
    CFLAGS = ["-O3"]

    CLINE = (
        "{compiler} -c -m {tgtname} "
        + "{incdirs} {libdirs} "
        + "{scfiles} "
        + "{obfiles} {loclibs} {glblibs} "
        + "--f90flags='{cflags}' "
    )

    def target_name(self):
        return f"extf2py_{self.name}"

    def include_as(self):
        raise RuntimeError("this target is not supposed to be included")

    def generate(self, *flags):
        flags = list(flags)
        # TODO: some flags go to f2py, some go to f90comp
        (
            incdirs,
            libdirs,
            glblibs,
            loclibs,
            scfiles,
            obfiles,
        ) = self.resolve_dependencies()
        yield self.CLINE.format(
            compiler="f2py3",
            cflags=" ".join(self.CFLAGS + flags),
            incdirs=" ".join(f"-I{ipath}" for ipath in incdirs),
            libdirs=" ".join(f"-L{lpath}" for lpath in libdirs),
            scfiles=" ".join(scfiles),
            obfiles=" ".join(obfiles),
            loclibs=" ".join(loclibs),
            glblibs=" ".join(glblibs),
            tgtname=self.target_name(),
        )
