"""
#autogenerated#header#do#not#modify############################################
#
# File:        backend_f90_library.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   03/12/2024
# Last Update: 03/12/2024, 16:29
# Version:     0.0.81
#
#################################################end#of#autoheader#do#not#modify


"""

from phoenix.fgen.library import PythonLibraryManager
from phoenix.fgen.backends.backend_f90_linear import (
    LibRoutineF90_Linear_Base,
    LibRoutineF90_Linear_Offs,
)


DEFAULT_OPTIONS = {
    "tab": "  ",
}

LIBRARY_HEAD = """
MODULE {lib_name}

{tab}IMPLICIT NONE

CONTAINS
"""

LIBRARY_FOOT = """
END MODULE {lib_name}
"""


class LibraryManagerF90(PythonLibraryManager):
    """A PythonLibraryManager for f90 type backend routines"""

    def append(self, routine):
        super().append(LibRoutineF90_Linear_Base(routine))
        super().append(LibRoutineF90_Linear_Offs(routine))

    def create_source_lines(self, **kwargs):
        options = dict(DEFAULT_OPTIONS)
        options.update({"lib_name": self.name})
        options.update(kwargs)

        for line in LIBRARY_HEAD.split("\n"):
            yield line.format(**options)

        for routine in self._libroutines:
            for line in routine.create_source_lines(**options):
                if line:
                    yield "{tab}".format_map(options) + line
            yield " "

        for line in LIBRARY_FOOT.split("\n"):
            yield line.format(**options)


if __name__ == "__main__":
    from phoenix.fgen.routine import Routine
    from phoenix.fgen.instruction3 import InstructionGroup, GenericInstruction

    instruction_group = (
        InstructionGroup(
            [
                GenericInstruction(
                    src1_indx=num + 1,
                    targ_indx=10 - num,
                    alph_r=1.0,
                    alph_i=0.0,
                )
                for num in range(10)
            ]
        )
        .sorted(lambda x: x["targ_indx"])
        .flatten()
    )
    my_routine_1 = Routine(
        "myroutine",
        itype=None,
        out_var=None,
        in_vars=[None],
        instruction_group=instruction_group,
    )
    my_routine_2 = Routine(
        "myotherroutine",
        itype=None,
        out_var=None,
        in_vars=[None],
        instruction_group=instruction_group,
    )
    mylib = LibraryManagerF90("mylib")
    mylib.append(my_routine_1)
    mylib.append(my_routine_2)
    for line in mylib.create_source_lines():
        print(line)
