"""
#autogenerated#header#do#not#modify############################################
#
# File:        backend_f90_linear.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   03/12/2024
# Last Update: 03/12/2024, 16:30
# Version:     0.0.175
#
#################################################end#of#autoheader#do#not#modify


"""

from phoenix.fgen.backends.libroutine_f90 import LibRoutineF90


SR_LINEAR_BASE_HEAD = """
SUBROUTINE {sr_name}_base(targ_r, targ_i, targ_n, src1_r, src1_i, src1_n)
{tab}!
{tab}double precision, intent(inout) :: targ_r
{tab}double precision, intent(inout) :: targ_i
{tab}integer, intent(in)             :: targ_n
{tab}!
{tab}double precision, intent(in)    :: src1_r
{tab}double precision, intent(in)    :: src1_i
{tab}integer, intent(in)             :: src1_n    
"""

SR_LINEAR_BASE_FOOT = """
END SUBROUTINE {sr_name}_base
"""

SR_LINEAR_BASE_LINE = """
{tab}targ_r({targ_indx}) = targ_r({targ_indx}) + src1_r({src1_indx}) * {alph_r} - src1_i({src1_indx}) * {alph_i}
{tab}targ_i({targ_indx}) = targ_i({targ_indx}) + src1_r({src1_indx}) * {alph_i} + src1_i({src1_indx}) * {alph_r}"""

SR_LINEAR_OFFS_HEAD = """
SUBROUTINE {sr_name}_offs(targ_r, targ_i, targ_n, src1_r, src1_i, src1_n, targ_off, src1_off)
{tab}!
{tab}double precision, intent(inout) :: targ_r
{tab}double precision, intent(inout) :: targ_i
{tab}integer, intent(in)             :: targ_n
{tab}!
{tab}double precision, intent(in)    :: src1_r
{tab}double precision, intent(in)    :: src1_i
{tab}integer, intent(in)             :: src1_n
{tab}!
{tab}integer, intent(in)             :: targ_off
{tab}integer, intent(in)             :: src1_off
{tab}!
{tab}integer                         : targ_indx_shft
{tab}integer                         : src1_indx_shft
"""

SR_LINEAR_OFFS_FOOT = """
END SUBROUTINE {sr_name}_offs
"""

SR_LINEAR_OFFS_LINE = """
{tab}targ_shft = {targ_indx} + targ_off
{tab}src1_shft = {src1_indx} + src1_off
{tab}targ_r(targ_shft) = targ_r(targ_shft) + src1_r(src1_shft) * {alph_r} - src1_i(src1_shft) * {alph_i}
{tab}targ_i(targ_shft) = targ_i(targ_shft) + src1_r(src1_shft) * {alph_i} + src1_i(src1_shft) * {alph_r}"""


class LibRoutineF90_Linear_Base(LibRoutineF90):
    """Linear version of the F90 routine"""

    code_head = SR_LINEAR_BASE_HEAD
    code_foot = SR_LINEAR_BASE_FOOT
    code_line = SR_LINEAR_BASE_LINE


class LibRoutineF90_Linear_Offs(LibRoutineF90):
    """Linear version of the F90 routine"""

    code_head = SR_LINEAR_OFFS_HEAD
    code_foot = SR_LINEAR_OFFS_FOOT
    code_line = SR_LINEAR_OFFS_LINE


if __name__ == "__main__":
    from phoenix.fgen.routine import Routine
    from phoenix.fgen.instruction3 import InstructionGroup, GenericInstruction

    instruction_group = (
        InstructionGroup(
            [
                GenericInstruction(
                    src1_indx=num + 1,
                    targ_indx=10 - num,
                    alph_r=1.0,
                    alph_i=0.0,
                )
                for num in range(10)
            ]
        )
        # .sorted(lambda x: x["targ_indx"])
        # .flatten()
    )

    for sline in LibRoutineF90_Linear_Base(
        Routine(
            "myroutine",
            itype=None,
            out_var=None,
            in_vars=[None],
            instruction_group=instruction_group,
        )
    ).create_source_lines(tab=""):
        print(sline)
