"""
#autogenerated#header#do#not#modify############################################
#
# File:        logger.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   10/03/2025
# Last Update: 12/03/2025, 17:14
# Version:     0.0.640
#
#################################################end#of#autoheader#do#not#modify


"""

from os.path import join as pathjoin
import traceback as tb

from sys import stdout, stderr

# global log levels
ERROR = 0
WARNING = 1
INFO = 2
DEBUG = 3

_COLORS = {
    "green": "\033[32m",
    "white": "\033[37m",
    "red": "\033[31m",
    "yellow": "\033[33m",
    "blue": "\033[34m",
    "gray": "\033[24m",
    "black": "\033[30m",
    "violet": "\033[35m",
    "lightblue": "\033[36m",
    "default": "\033[0m",
}
_NOCOLOR = _COLORS["default"]


class Logger:
    """A logger class to be used from all other classes"""

    _actioncount = 0
    _LOGREPR = {
        "ERROR": "!ERR",
        "WARNING": "WARN",
        "INFO": "info",
        "CONFIRM": "info",
        "DEBUG": " dbg",
    }

    _LOG_COLORS = {
        "ERROR": "red",
        "WARNING": "yellow",
        "INFO": "white",
        "CONFIRM": "green",
        "DEBUG": "lightblue",
    }
    _DEFAULT_PATH = "./"

    def wrap_call(self, function):
        """a decorator from a logger instance"""

        def wrapper(*args, **kwargs):
            try:
                if __debug__:
                    self.debug(
                        f"CALLED function {function.__name__}",
                        f"args  : {args}",
                        f"kwargs: {kwargs}",
                    )
                if self._loglevel > 2:
                    self._indentlevel += 1
                ret = function(*args, **kwargs)
                if __debug__:
                    self.debug(f"return value: {ret}")
                    self.debug("done")
            except Exception as exc:
                if self._alerted:
                    control_message = "Error! An exception occured"
                else:
                    control_message = "A controlled exception occured"
                lines = [
                    f"{control_message}: {exc}",
                    f"called generator {function.__name__}",
                    f"args  : {args}",
                    f"kwargs: {kwargs}",
                    "traceback:",
                ]
                if self._alerted:
                    for num, segment in enumerate(
                        tb.format_tb(exc.__traceback__, limit=None)
                    ):
                        if num == 0:
                            continue
                        for line in segment.split("\n"):
                            if line.strip():
                                lines.append(f"  {line}")
                    self.error(*lines)
                else:
                    self.warn(*lines)
                exc.add_note(
                    f"Information has been written to the log file '{self._file}'"
                )
                raise exc
            finally:
                if self._loglevel > 2:
                    self._indentlevel -= 1
                self.debug(f"END of function {function.__name__}")
            return ret

        # potential TODO: tidy the stacktrace from the logger parts

        return wrapper

    def wrap_gen(self, function):
        """a decorator from a logger instance"""

        def wrapper(*args, **kwargs):
            try:
                if __debug__:
                    self.debug(
                        f"CALLED generator {function.__name__}",
                        f"args  : {args}",
                        f"kwargs: {kwargs}",
                    )
                if self._loglevel > 2:
                    self._indentlevel += 1
                for ret in function(*args, **kwargs):
                    if __debug__:
                        self.debug(f"yield value: {ret}")
                    yield ret
                if __debug__:
                    self.debug("done")
            except Exception as exc:
                if self._alerted:
                    control_message = "Error! An exception occured"
                else:
                    control_message = "A controlled exception occured"
                lines = [
                    f"{control_message}: {exc}",
                    f"called generator {function.__name__}",
                    f"args  : {args}",
                    f"kwargs: {kwargs}",
                    "traceback:",
                ]
                if self._alerted:
                    for num, segment in enumerate(
                        tb.format_tb(exc.__traceback__, limit=None)
                    ):
                        if num == 0:
                            continue
                        for line in segment.split("\n"):
                            if line.strip():
                                lines.append(f"  {line}")
                    self.error(*lines)
                else:
                    self.warn(*lines)
                exc.add_note(
                    f"Information has been written to the log file '{self._file}'"
                )
                raise exc
            finally:
                if self._loglevel > 2:
                    self._indentlevel -= 1
                self.debug(f"END of generator {function.__name__}")
            return ret

        # potential TODO: tidy the stacktrace from the logger parts

        return wrapper

    def controlled(self, function):
        """a decorator to alert that any exception is fatal within"""

        def wrapper(*args, **kwargs):
            self._alerted = False
            ret = function(*args, **kwargs)
            self._alerted = True
            return ret

        return wrapper

    def __init__(self, filename=None, path=None, loglevel=2, stdout=False):
        """supported kwargs: stdout (False), stderr(True)"""
        self._file = None
        self._alerted = True
        self._file = None
        self._indentlevel = 0
        self._loglevel = min(3, max(0, loglevel))
        self._stdout = stdout

        self.set_logfile(filename, path)
        self.reset()

    def reset(self):
        """reset the file"""
        if self._file:
            with open(self._file, "w") as file:
                file.write("")

    def set_loglevel(self, loglevel):
        """
        Set the loglevel.

        0: include only errors
        1: also include warnings
        2: also include info (default)
        3: also include debug info
        """
        self._loglevel = min(3, max(0, loglevel))

    def set_logfile(self, filename, path=None):
        """
        Set the logfile and path
        """
        if filename is None:
            # reset file?
            self._file = None
        else:
            if not filename.endswith(".log"):
                if not "." in filename:
                    filename = filename + ".log"
            if path is None:
                # default path if not explicitely set
                path = Logger._DEFAULT_PATH
            self._file = pathjoin(path, filename)

    def _write_to_stdout(self, acstr, typestr, mline, msgtype, level):
        indent = level * "  "
        color_in, color_out = _COLORS[Logger._LOG_COLORS[msgtype]], _NOCOLOR
        line = color_in + f"{indent}{mline}" + color_out
        # line = color_in + f"{acstr}{typestr}{indent}{mline}" + color_out
        if msgtype == "ERROR":
            stderr.write(line + "\n")
        else:
            if self._stdout:
                stdout.write(line + "\n")

    def _write_to_file(self, acstr, typestr, mline, msgtype, level):
        indent = level * "  "
        line = f"{acstr}{typestr}{indent}{mline}"
        if self._file:
            with open(self._file, "a") as file:
                file.write(line + "\n")

    def multiline_log(self, message_lines, msgtype="INFO", level=None):
        """log multiple lines"""
        if level is None:
            level = self._indentlevel

        if "".join(message_lines).replace("\n", "").strip():
            acount = Logger._actioncount
            Logger._actioncount += 1

            first = True
            for mline in message_lines:
                acstr = f"{acount:>6}" + ":"
                typestr = f"{type(self)._LOGREPR[msgtype.upper()]: <4}" + ": "
                if not first:
                    acstr = " " * len(acstr)
                    typestr = " " * len(typestr)
                first = False
                self._write_to_stdout(acstr, typestr, mline, msgtype, level)
                if mline.strip():
                    self._write_to_file(acstr, typestr, mline, msgtype, level)
        else:
            self._write_to_stdout("", "", "", msgtype, level)

    def log(self, message, msgtype="INFO", level=None):
        """log a line"""
        self.multiline_log([message], msgtype=msgtype, level=level)

    def _log_debug(self, *messages):
        if self._loglevel > 2:
            self.multiline_log(list(messages), "DEBUG")

    def _log_info(self, *messages):
        if self._loglevel > 1:
            self.multiline_log(list(messages), "INFO")

    def _log_success(self, message):
        if self._loglevel > 1:
            self.multiline_log([message], "CONFIRM")

    def _log_warn(self, *messages):
        if self._loglevel > 0:
            self.multiline_log(list(messages), "WARNING")

    def _log_error(self, *messages):
        self.multiline_log(list(messages), "ERROR")

    def info(self, *messages):
        """make an info log message"""
        return self._log_info(
            *sum((msg.split("\n") for msg in messages), start=[])
        )

    def success(self, message):
        """make a success log message"""
        return self._log_success(message)

    def debug(self, *messages):
        """make a debug log message"""
        return self._log_debug(
            *sum((msg.split("\n") for msg in messages), start=[])
        )

    def warn(self, *messages):
        """make a warning log message"""
        return self._log_warn(
            *sum((msg.split("\n") for msg in messages), start=[])
        )

    def error(self, *messages):
        """make an error log message"""
        return self._log_error(
            *sum((msg.split("\n") for msg in messages), start=[])
        )


# DUMP
# ====
#
#
# def info(self, message, level=None):
#     """plain on-screen info"""
#     if level is None:
#         level = self._indentlevel
#     if self._loglevel > 1:
#         self._write_to_stdout("", "", str(message), "INFO", level)
# def success(self, message="success", level=None):
#     """plain on-screen info"""
#     if level is None:
#         level = self._indentlevel
#     if self._loglevel > 1:
#         self._write_to_stdout("", "", str(message), "CONFIRM", level)
# def debug(self, message, level=None):
#     """plain on-screen info"""
#     if level is None:
#         level = self._indentlevel
#     if self._loglevel > 2:
#         self._write_to_stdout("", "", str(message), "DEBUG", level)
# def warn(self, message, level=None):
#     """plain on-screen info"""
#     if level is None:
#         level = self._indentlevel
#     if self._loglevel > 0:
#         self._write_to_stdout("", "", str(message), "WARNING", level)
# def error(self, message, level=None):
#     """plain on-screen info"""
#     if level is None:
#         level = self._indentlevel
#     self._write_to_stdout("", "", str(message), "ERROR", level)


GLOBAL_LOGGER = Logger(None, loglevel=2, stdout=True)
