"""
#autogenerated#header#do#not#modify############################################
#
# File:        dtype.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 27/01/2025, 14:37
# Version:     0.0.1823
#
#################################################end#of#autoheader#do#not#modify



TODO:
=====

[X]:  from_numpy, to_numpy/as_numpy: these methods shortcut the data transfer
        between host and potential device without using a container object.
        This strategy does not require any host/local data representation in the
        datatype, does not require syncing and is cheap to implement.
[ ]:  auto-implement pure, gpu and cpu data type. Have a lib variable set upon
        initialisation to read the availability of cupy, pycuda, opencl, ...
        and have an automated choice for the data type if "GPU", "CPU" or
        "PURE" is  passed as an initializer. Check how ADAA is best implemented
        to have a choice of hardware
"""

# pylint: disable=too-many-arguments


from __future__ import annotations

__doc__ = """

The ADAA class holds data references to HPC backends and unpacks accordingly
for function calls.

Basic arithemtic operations are implemented via a mapping into a basic
linop(A, b, C) -> A + b * C operation

DContainer combines multiple Layers to a combined datatype and can be extended
to manage inter-layer data conversion, host-device sync and consistency checks.

So far, no arithmetic operation is implemented on this level, intentionally,
as, depending on the interpretation of levels, such an implementation might be
factually wrong.

"""


from typing import Type
import numpy as np

from phoenix.coeffbackend import CoeffBackend
from phoenix.keymap import KeyMap


ZERO_TOL = 1e-14


class ADAA:
    """
    ADAA is an acronym for Aligned Data Access Array.
    This data type is intended for the systematic distribution of data into
    multiple aligned arrays. An example for this distribution are arrays
    holding the real and imaginary parts of numbers that were originally
    stored in a complex array. The distribution does not require more memory
    but might allow optimizations based on the active distinction between
    e.g. real and imaginary parts.

    The base class implements just this case and comes along with basic
    arithmetic operations.
    """

    _IDENTIFIER = "COMPLEX_ARRAY"
    BACKEND: CoeffBackend = None
    KEYMAP: KeyMap = None
    FIXED_SIZE = None

    _type_r = "f64"
    _type_i = "f64"

    def __init__(self, size: int | None = None, init_zeros=True):
        self._data_r = None
        self._data_i = None
        self._size = 0
        if self.FIXED_SIZE is None and self.KEYMAP is None:
            if not size:
                raise ValueError("Size must be given or fixed.")
        if self.FIXED_SIZE:
            if size is None:
                size = self.FIXED_SIZE
            else:
                if size != self.FIXED_SIZE:
                    raise ValueError(f"Size is fixed ({self.FIXED_SIZE})")
        if self.KEYMAP:
            if size is None:
                size = self.KEYMAP.size
            else:
                if size != self.KEYMAP.size:
                    raise ValueError(f"Size is fixed by keymap {self.KEYMAP}")
        assert size is not None
        self.reinit(size)
        if init_zeros:
            self.to_zero()  # should probably be forced anyways.

    def _access_pattern(self, prefix):
        return self.BACKEND.access_pattern(prefix)

    @property
    def real(self):
        """Access protected attribute real."""
        return self._data_r

    @real.setter
    def real(self, arr):
        """Set the data for real part."""
        # self._set_data(real=arr)
        raise ValueError("Real part of the data cannot be set directly.")

    @property
    def imag(self):
        """Access protected attribute imag."""
        return self._data_i

    @imag.setter
    def imag(self, arr):
        """Set the data for imag part."""
        # self._set_data(imag=arr)
        raise ValueError("Imag part of the data cannot be set directly.")

    @property
    def identifier(self) -> str:
        """access write-protected property 'identifier'"""
        return self._IDENTIFIER

    @property
    def size(self) -> int:
        """Access write-protected property 'size'"""
        return self._size

    def to_zero(self):
        """Set the coefficient data to zero."""
        self.BACKEND.coeff_to_zero(
            self._data_r, size=self.size, dtype=self._type_r
        )
        self.BACKEND.coeff_to_zero(
            self._data_i, size=self.size, dtype=self._type_i
        )
        return self

    @classmethod
    def from_numpy(cls, arr: np.ndarray) -> ADAA:
        """Import data from numpy array."""
        size = len(arr)
        obj = cls(size)
        cls.BACKEND.coeff_from_numpy(
            obj.real, arr.real, size=size, dtype=cls._type_r
        )
        cls.BACKEND.coeff_from_numpy(
            obj.imag, arr.imag, size=size, dtype=cls._type_i
        )
        return obj

    def to_numpy(self) -> np.ndarray:
        """Export data as numpy array."""
        real_part = self.BACKEND.coeff_to_numpy(
            self.real, size=self.size, dtype=self._type_r
        )
        imag_part = self.BACKEND.coeff_to_numpy(
            self.imag, size=self.size, dtype=self._type_i
        )
        return real_part + 1j * imag_part

    def unpack(self) -> tuple:
        """Unpack the layer into a tuple to apply it to functions."""
        return (self._data_r, self._data_i, self.size)

    def copy(self) -> ADAA:
        """Creates a real copy of self."""
        copy = self.__class__(self.size)
        self.BACKEND.coeff_copy_data(
            copy.real, self.real, size=self.size, dtype=self._type_r
        )
        self.BACKEND.coeff_copy_data(
            copy.imag, self.imag, size=self.size, dtype=self._type_i
        )
        return copy

    @classmethod
    def allclose(cls, op_a, op_b, rtol: float = 1e-05, atol: float = 1e-8):
        """
        Check if the values are all sufficiently close by checking, if
        |a - b|² <= atol² + rtol² (|a|² + |b|²) / 4
        is fulfilled for all coefficients.
        """
        if op_a.size != op_b.size:
            raise ValueError("Compared operators must have the same size.")
        real_all_close = cls.BACKEND.coeff_allclose(
            op_a.real, op_b.real, rtol, atol, size=op_a.size, dtype=cls._type_r
        )
        imag_all_close = cls.BACKEND.coeff_allclose(
            op_a.imag, op_b.imag, rtol, atol, size=op_a.size, dtype=cls._type_i
        )
        return real_all_close and imag_all_close

    @classmethod
    def basic_linop(cls, op_r, /, op_a=None, sc_b=None, op_c=None, size=None):
        """evaluates operator_r += operator_a + scalar_b * operator_c"""

        assert op_c is not None
        assert op_r is not None

        if size is not None:
            if size != op_r.size:
                raise ValueError("Invalid size parameter.")
        size = op_r.size

        if op_a is None:
            zero = cls(size).to_zero()
            oar, oai = zero.real, zero.imag
        else:
            oar = op_a.real
            oai = op_a.imag

        ocr = op_c.real
        oci = op_c.imag

        if sc_b is None:
            sbr, sbi = (1.0, 0.0)
        else:
            sbr, sbi = (complex(sc_b).real, complex(sc_b).imag)

        aux_r = cls.BACKEND.coeff_new_array(size, dtype=cls._type_r)
        aux_i = cls.BACKEND.coeff_new_array(size, dtype=cls._type_i)

        # sbr * ocr - sbi * oci -> aux_r
        cls.BACKEND.coeff_linop(
            aux_r, sbr, ocr, -1 * sbi, oci, size=size, dtype=cls._type_r
        )
        # sbi * ocr + sbr * oci -> aux_i
        cls.BACKEND.coeff_linop(
            aux_i, sbi, ocr, sbr, oci, size=size, dtype=cls._type_i
        )

        # bracket + oar -> op_r.real
        cls.BACKEND.coeff_add(
            op_r.real, aux_r, oar, size=size, dtype=cls._type_r
        )
        # bracket + oai -> op_r.imag
        cls.BACKEND.coeff_add(
            op_r.imag, aux_i, oai, size=size, dtype=cls._type_i
        )

    def free_memory(self):
        """free the occupied memory"""
        self._data_r = self.BACKEND.coeff_free(
            self._data_r, size=self.size, dtype=self._type_r
        )
        self._data_i = self.BACKEND.coeff_free(
            self._data_i, size=self.size, dtype=self._type_i
        )

    def _reinit(self, size=None):
        """Reinitialize the data for a certain size"""
        if size is None:
            size = self.size
        else:
            if size == self.size:
                return
        self.reinit(size)

    def reinit(self, size):
        """Actual reinitialization. Forced."""
        self.free_memory()
        self._data_r = self.BACKEND.coeff_new_array(size, dtype=self._type_r)
        self._data_i = self.BACKEND.coeff_new_array(size, dtype=self._type_i)
        self._size = size

    def __init_subclass__(
        cls, backend=None, identifier=None, keymap=None, size=None
    ):
        """
        When a new subclass is derived, introduce the class
        variable _IDENTIFIER.
        """
        if backend is None:
            if cls.BACKEND is None:
                raise ValueError("No backend specified.")
        else:
            cls.BACKEND = backend
        if identifier is None:
            identifier = cls.__name__  # get default
        cls._IDENTIFIER = identifier
        if size is not None and keymap is not None:
            raise ValueError("Size and keymap cannot be set simultaneously.")
        if keymap is not None:
            cls.KEYMAP = keymap  # get default
        if size is not None:
            if size >= 0:
                cls.FIXED_SIZE = size
            else:
                raise ValueError("Size must be a non-negative integer.")

    @classmethod
    def set_keymap(cls, keymap: KeyMap) -> Type[ADAA]:
        """derive a type with given keymap"""
        if cls.FIXED_SIZE:
            raise ValueError("Cannot set keymap when fixed size is given.")
        if cls.KEYMAP is not None:
            raise ValueError(f"KeyMap {cls.KEYMAP} already set.")
        return type(cls._IDENTIFIER + f"<{keymap}>", (cls,), {}, keymap=keymap)

    @classmethod
    def fix_size(cls, size: int) -> Type[ADAA]:
        """derive a fixed size type"""
        if cls.KEYMAP:
            raise ValueError("Cannot derive fixed size when keymap is given.")
        if cls.FIXED_SIZE:
            raise ValueError(f"Fixed size {cls.FIXED_SIZE} already set.")

        return type(cls._IDENTIFIER + f"[{size}]", (cls,), {}, size=size)

    @classmethod
    def ones(cls, size=None):
        """return an ADAA made from ones"""
        if size is None:
            size = cls.FIXED_SIZE
        return cls.from_numpy(np.ones(size))

    @classmethod
    def mul(cls, first, other, target=None, **_kwargs):
        """multiplication slot routine"""
        if isinstance(other, ADAA):
            raise ValueError(
                "Multiplication by other operator is not supported"
            )
        if target is None:
            target = cls(first.size)
        cls.basic_linop(target, op_a=None, sc_b=other, op_c=first)
        return target

    @classmethod
    def div(cls, first, other, target=None, **_kwargs):
        """division slot routine"""
        if isinstance(other, ADAA):
            raise ValueError("Division by other operator is not supported")
        if target is None:
            target = cls(first.size)
        cls.basic_linop(target, op_a=None, sc_b=1.0 / other, op_c=first)
        return target

    @classmethod
    def add(cls, first, other, target=None, **_kwargs):
        """addition slot routine"""
        if isinstance(other, ADAA):
            assert first.size == other.size
            assert first.identifier == other.identifier
        else:
            raise ValueError("Addition only supports ADAAs")
        if target is None:
            target = cls(first.size)
        cls.basic_linop(target, op_a=first, sc_b=1, op_c=other)
        return target

    @classmethod
    def sub(cls, first, other, target=None, **_kwargs):
        """subtraction slot routine"""
        if isinstance(other, ADAA):
            assert first.size == other.size
            assert first.identifier == other.identifier
        else:
            raise ValueError("Subtraction only supports ADAAs")
        if target is None:
            target = cls(first.size)
        cls.basic_linop(target, op_a=first, sc_b=-1, op_c=other)
        return target

    @classmethod
    def neg(cls, first, target=None, **kwargs):
        """negation slot routine"""
        return cls.mul(first, -1, target=target, **kwargs)

    ###########################################################################
    #
    # MAGIC
    # =====

    def __add__(self, other):
        return self.__class__.add(self, other)

    def __radd__(self, other):
        return self.__class__.add(other, self)

    def __sub__(self, other):
        return self.__class__.sub(self, other)

    def __rsub__(self, other):
        return self.__class__.sub(other, self)

    def __mul__(self, other):
        return self.__class__.mul(self, other)

    def __rmul__(self, other):
        return self.__class__.mul(other, self)

    def __truediv__(self, other):
        return self.__class__.div(self, other)

    def __rtruediv__(self, other):
        return self.__class__.div(other, self)

    def __div__(self, other):
        return self.__class__.div(self, other)

    def __rdiv__(self, other):
        return self.__class__.div(other, self)

    def __neg__(self):
        return self.__class__.neg(self)

    def __len__(self):
        return self.size

    def __bool__(self):
        return self.size > 0

    def __eq__(self, other):
        return self.__class__.allclose(self, other)  # , rtol=1e-08, atol=1e-12)

    def __del__(self):
        self.free_memory()


###############################################################################


#


# class TestADAA(PurePyADAA, identifier="test"):
#     pass


# print(
#     test[0],
# )

# FixedSizeTest = TestADAA.fix_size(42)

# foo_object = FixedSizeTest()

# print(foo_object.identifier)
# print(len(foo_object))
