"""
#autogenerated#header#do#not#modify############################################
#
# File:        dtype.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 02/10/2024, 18:19
# Version:     0.0.751
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """
DType module description
========================

DLayer
------

The DLayer class holds data references to HPC backends and unpacks accordingly
for function calls.

Basic arithemtic operations are implemented via a mapping into a basic
linop(A, b, C) -> A + b * C operation

DContainer
----------

DContainer combines multiple Layers to a combined datatype and can be extended
to manage inter-layer data conversion, host-device sync and consistency checks.

So far, no arithmetic operation is implemented on this level, intentionally,
as, depending on the interpretation of levels, such an implementation might be
factually wrong.

"""

# pylint: disable=too-many-arguments

# from typing import Any

import numpy as np
import cupy as cp
import pyopencl as cl


ZERO_TOL = 1e-14


class ADAA:
    """Aligned Data Access Array class description"""

    _IDENTIFIER = "_GENERIC_"

    def __init__(self, size: int):
        self._meta = {"ndata": size}
        self._data_r = None
        self._data_i = None
        self._reinit(size)

    @classmethod
    def _empty(cls, size):
        return None, None

    def _reinit(self, size):
        self._data_r, self._data_i = self.__class__._empty(size)
        self._meta["ndata"] = size

    def __init_subclass__(cls, ident=None):
        if ident is None:
            # ident = cls._IDENTIFIER
            ident = cls.__name__
        cls._IDENTIFIER = ident

    def _set_data_ref(self, real=None, imag=None):
        """set data"""
        if real is not None:
            self._data_r = real
        if imag is not None:
            self._data_i = imag
        return self

    @property
    def real(self):
        """access read-only attribute real"""
        return self._data_r

    @property
    def imag(self):
        """access read-only attribute imag"""
        return self._data_i

    @classmethod
    def _from_scalar(cls, scalar_real, scalar_imag):
        return scalar_real, scalar_imag

    @classmethod
    def _maxval(cls, array):
        return max(array.real), max(array.imag)

    @classmethod
    def _minval(cls, array):
        return min(array.real), min(array.imag)

    @classmethod
    def _coeff_conjugate(cls, array):
        return cls(array.size)._set_data_ref(array.real, -array.imag)

    @classmethod
    def _coeff_norm2(cls, array):
        return array * cls._coeff_conjugate(array)

    @classmethod
    def _all_coeff_positive(cls, array, real=True, imag=False):
        """checks if all real parts of the array are non-negative"""
        if real:
            if cls._minval(array.real) < -ZERO_TOL:
                return False
        if imag:
            if cls._minval(array.imag) < -ZERO_TOL:
                return False
        return True

    @classmethod
    def allclose(cls, array_a, array_b, rtol=1e-05, atol=1e-8):
        """check if the values are all close

        checks for each component, if
        |a - b|² <= atol² + rtol² (|a|² + |b|²) / 4
        """
        dif_squared = cls._coeff_norm2(array_a - array_b)
        ref_squared = cls._from_scalar(atol**2, 0) + cls._from_scalar(
            rtol**2 / 4, 0
        ) * (cls._coeff_norm2(array_a) + cls._coeff_norm2(array_b))
        return cls._all_coeff_positive(
            ref_squared - dif_squared, real=True, imag=False
        )

    @classmethod
    def _basic_linop(cls, op_a=None, sc_b=None, op_c=None):
        """returns operator_a + scalar_b * operator_c"""

        if op_a is None:
            oar, oai = cls._from_scalar(0, 0)
        else:
            oar = op_a.real
            oai = op_a.imag

        if op_c is None:
            ocr, oci = cls._from_scalar(1, 0)
        else:
            ocr = op_c.real
            oci = op_c.imag

        if sc_b is None:
            sbr, sbi = cls._from_scalar(1, 0)
        else:
            sbr, sbi = cls._from_scalar(complex(sc_b).real, complex(sc_b).imag)

        real_part = oar + (sbr * ocr - sbi * oci)
        imag_part = oai + (sbi * ocr + sbr * oci)

        return (real_part, imag_part)

    def __add__(self, other):
        if isinstance(other, self.__class__):
            assert self.size == other.size
            assert self.ident == other.ident
            (real_part, imag_part) = self._basic_linop(
                op_a=self, sc_b=1, op_c=other
            )
        else:
            (real_part, imag_part) = self._basic_linop(
                op_a=self, sc_b=other, op_c=None
            )
        return self.__class__(size=self.size)._set_data_ref(
            real=real_part,
            imag=imag_part,
        )

    def __sub__(self, other):
        if isinstance(other, self.__class__):
            assert self.size == other.size
            assert self.ident == other.ident
            (real_part, imag_part) = self._basic_linop(
                op_a=self, sc_b=-1, op_c=other
            )
        else:
            (real_part, imag_part) = self._basic_linop(
                op_a=self, sc_b=-other, op_c=None
            )
        return self.__class__(size=self.size)._set_data_ref(
            real=real_part,
            imag=imag_part,
        )

    def __mul__(self, other):
        if isinstance(other, ADAA):
            raise ValueError("Dividing through operator is not supported")
        (real_part, imag_part) = self._basic_linop(
            op_a=None, sc_b=other, op_c=self
        )
        return self.__class__(size=self.size)._set_data_ref(
            real=real_part,
            imag=imag_part,
        )

    def __truediv__(self, other):
        if isinstance(other, ADAA):
            raise ValueError("Dividing through operator is not supported")
        inv_other = 1.0 / other
        (real_part, imag_part) = self._basic_linop(
            op_a=None, sc_b=inv_other, op_c=self
        )
        return self.__class__(size=self.size)._set_data_ref(
            real=real_part,
            imag=imag_part,
        )

    def __rmul__(self, other):
        # assume commutative, because if the other operator is an ADAA as well,
        # why should rmul be called anyways?
        return self.__mul__(other)

    def __radd__(self, other):
        # assume commutative, because addition is.
        return self.__add__(other)

    def __neg__(self):
        (real_part, imag_part) = self._basic_linop(
            op_a=None, sc_b=-1, op_c=self
        )
        return self.__class__(size=self.size)._set_data_ref(
            real=real_part,
            imag=imag_part,
        )

    def __rsub__(self, other):
        if isinstance(other, ADAA):
            raise ValueError("This should not have happened")
        (real_part, imag_part) = self._basic_linop(
            op_a=-self, sc_b=other, op_c=None
        )
        return self.__class__(size=self.size)._set_data_ref(
            real=real_part,
            imag=imag_part,
        )

    def __pow__(self, exponent):
        if not isinstance(exponent, int):
            raise ValueError("Exponent must be an integer")
        if exponent < 0:
            raise ValueError("Exponent must be non-negative")
        accum = self.__class__._from_scalar(1, 0)  # identity operator
        for _ in range(exponent):
            accum *= self
        return accum

    def __len__(self):
        return self.size

    def __bool__(self):
        return self.size > 0

    def __eq__(self, other):
        return self.__class__.allclose(
            self, other
        )  # , rtol=1e-08, atol=1e-12)

    @property
    def ident(self) -> str:
        """access write-protected property ident"""
        return self._IDENTIFIER

    @property
    def size(self) -> int:
        """access write-protected property ndata"""
        return self._meta["ndata"]

    def unpack(self) -> tuple:
        """unpack the layer"""
        return (self._data_r, self._data_i, self.size)


class DContainer:
    """DContainer class description"""

    _LAYERS: dict[str, ADAA] = {}

    def __init__(self, *sizes):
        self._layers = {
            key: layer(size)
            for (key, layer), size in zip(self._LAYERS.items(), sizes)
        }

    def __init_subclass__(cls, **layers):
        cls._LAYERS = layers
        return cls

    def __getitem__(self, key):
        assert key in self._layers
        return self._layers[key]

    # # I need to think about granting write access to that.
    # def __setitem__(self, key, value):
    #     assert key in self._layers
    #     self._layers[key] = value

    def unpack(self, key, **kwargs):
        """unpack the requested layer"""
        assert key in self._layers
        return self._layers[key].unpack(**kwargs)

    def unpack_multi(self, keys, **kwargs):
        """unpack the requested layer"""
        for key in keys:
            assert key in self._layers
        return [self._layers[key].unpack(**kwargs) for key in keys]


class DLC(DContainer):
    """Dual Layer Container class"""


class SDLC(DLC):
    """Synced Dual Layer Container class"""


###############################################################################


class PurePyADAA(ADAA):
    """Pure Python data layer"""

    _IDENTIFIER = "PUREPYTHON"

    @classmethod
    def _empty(cls, size):
        real = [0.0 for _ in range(size)]
        imag = [0.0 for _ in range(size)]
        return real, imag


class NumpyADAA(ADAA):
    """Numpy based data layer"""

    _IDENTIFIER = "NUMPY"

    @classmethod
    def _empty(cls, size):
        real = np.zeros(size)
        imag = np.zeros(size)
        return real, imag


class FortranADAA(ADAA):
    """FORTRAN based data layer (implemented via NumPy)"""

    _IDENTIFIER = "FORTRAN"

    @classmethod
    def _empty(cls, size):
        real = np.zeros(size)
        imag = np.zeros(size)
        return real, imag


class CupyADAA(ADAA):
    """Cupy based data layer"""

    _IDENTIFIER = "CUPY"

    @classmethod
    def _empty(cls, size):
        real = cp.zeros(size)
        imag = cp.zeros(size)
        return real, imag


class OpenClADAA(ADAA):
    """Cupy based data layer"""

    _IDENTIFIER = "OPENCL"

    _CL_CTX = cl.create_some_context()
    _CL_QUEUE = cl.CommandQueue(_CL_CTX)

    _CL_MF = cl.mem_flags

    @classmethod
    def _empty(cls, size):
        real = cl.Buffer(
            cls._CL_CTX,
            cls._CL_MF.READ_ONLY | cls._CL_MF.COPY_HOST_PTR,
            hostbuf=np.zeros(size),
        )
        imag = cl.Buffer(
            cls._CL_CTX,
            cls._CL_MF.READ_ONLY | cls._CL_MF.COPY_HOST_PTR,
            hostbuf=np.zeros(size),
        )
        return real, imag


class Foo(
    DContainer,
    layer1=PurePyADAA,
    layer2=NumpyADAA,
    layer3=OpenClADAA,
    layer4=CupyADAA,
):
    pass


print(Foo._LAYERS)

test = Foo(10, 12, 14, 16)

print(
    test["layer1"].unpack(),
    "\n",
    type(test["layer1"].unpack()[0]),
    type(test["layer1"].unpack()[0][0]),
    "\n",
)

print(
    test["layer2"].unpack(),
    "\n",
    type(test["layer2"].unpack()[0]),
    type(test["layer2"].unpack()[0][0]),
    "\n",
)

print(
    test["layer3"].unpack(),
    "\n",
    type(test["layer3"].unpack()[0]),
    "\n",
)

print(
    test["layer4"].unpack(),
    "\n",
    type(test["layer4"].unpack()[0]),
    type(test["layer4"].unpack()[0][0]),
    "\n",
)


class MyLayerPurePy(PurePyADAA, ident="PurePy2"):
    pass


print(MyLayerPurePy._IDENTIFIER)
