"""
#autogenerated#header#do#not#modify############################################
#
# File:        libroutine_txt.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   11/02/2025
# Last Update: 10/03/2025, 10:20
# Version:     0.0.107
#
#################################################end#of#autoheader#do#not#modify


"""

from typing import Set, Dict

from phoenix.fgen.codecontainer import CodeContainer, StatementLine
from phoenix.fgen.instruction import (
    InstructionGroup,
    GenericInstruction,
    EnvironmentInstruction,
    MapInstruction,
)
from phoenix.fgen.instructionvar import InstructionVariable


class TextCodeContainer(CodeContainer):
    """a text base code container for debugging purposes"""
