"""
#autogenerated#header#do#not#modify############################################
#
# File:        makefile.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   09/12/2024
# Last Update: 17/07/2025, 18:56
# Version:     0.0.525
#
#################################################end#of#autoheader#do#not#modify


NOTES
=====

In MakeFileManager, the associated Targets are extracted from the LibRoutines
that a library depends on.

A Library is added to known targets when it has been loaded the first time. If it is
required as a target again, no duplicates shall be created.

To stay within the makefile ecosystem, a makefile target can only depend on another 
makefile target. The lookup system is generalized to a key based system and I will start
with names.

Therefore, a makefile can be automatically created.

"""


import warnings


class _MFIdentifier:
    """an identifier to help identifying groups"""

    _known_identifiers = {}

    @classmethod
    def get(cls, identifier):
        """get identifier"""
        if identifier in cls._known_identifiers:
            return cls._known_identifiers[identifier]
        raise KeyError("unknown identifier")

    @classmethod
    def create(cls, identifier, order=None, silent=False):
        """create a new identifier, but make sure its unique"""
        if identifier in cls._known_identifiers:
            raise KeyError("duplicated identifier")
        if order is None:
            order = len(cls._known_identifiers)
        new_ident = _MFIdentifier(identifier, order, silent=silent)
        cls._known_identifiers[identifier] = new_ident
        return new_ident

    @property
    def default_silent_state(self):
        """access silent target state"""
        return self.default_silent

    def __init__(self, ident, order, silent=False):
        self.default_silent = silent
        self.ident = ident
        self.order = order

    def __eq__(self, other):
        return self.ident == other.ident

    def __gt__(self, other):
        return self.order > other.order

    def __hash__(self):
        return hash((self.ident, self.order))

    def __str__(self):
        return f"[{self.order}]:{self.ident}"

    def __repr__(self):
        return str(self)


MFGID_PATTERN = _MFIdentifier.create("PATTERN", order=0)
MFGID_HEADER = _MFIdentifier.create("HEADER", order=2, silent=True)
MFGID_PREPROC = _MFIdentifier.create("PREPROC", order=3)
MFGID_SOURCE = _MFIdentifier.create("SOURCE", order=4, silent=True)
MFGID_OBJECT = _MFIdentifier.create("OBJECT", order=5)
MFGID_SHAREDLIB = _MFIdentifier.create("SHAREDLIB", order=7)
MFGID_STATICLIB = _MFIdentifier.create("STATICLIB", order=9)
MFGID_SPECIAL = _MFIdentifier.create("SPECIAL", order=20)
MFGID_EXTERNLIB = _MFIdentifier.create("EXTERNLIB", order=998, silent=True)
MFGID_GENERIC = _MFIdentifier.create("GENERIC", order=999)
MFGID_GENERAL = _MFIdentifier.create("GENERAL", order=20)


def no_duplicates(listlike):
    """generate a list without duplicates that conserves order"""
    ret = []
    for llike in listlike:
        if llike in ret:
            continue
        ret.append(llike)
    return ret


class MakeFileManager:
    """manages creation, execution and design of makefiles"""

    def __init__(self, name, **_):
        self.name = name
        self._filename = f"Makefile_{name}"
        self._is_created = False
        self._targets = {}
        self._cleanable = []
        self._make_all = []

    def set_filename(self, filename):
        """set the makefile's filename"""
        self._filename = filename
        self._is_created = False

    def create_file(self):
        """create the file"""
        self._is_created = True

    def append(self, target, exception_existing=True):
        """append, avoid duplicates"""
        if target.target_name() not in self._targets:
            self._targets[target.target_name()] = target
            return True
        if exception_existing:
            raise ValueError(f"target {target.target_name()} already exists")
        return False

    def get_makefile_lines(self):
        """get the lines that go to the actual makefile"""
        for target in self.all_targets():
            yield from self.filter_double_space(
                target.target_get_makefile_lines()
            )
            yield ""

    def execute_file(self):
        """execute the makefile"""
        if not self._is_created:
            self.create_file()

    def filter_double_space(self, generatorlike):
        """filter out double spaces to make the files look nicer"""
        for tline in generatorlike:
            nline = ""
            while True:
                nline = tline.replace("  ", " ")
                if nline == tline:
                    break
                tline = nline
            yield nline

    def targets_with_dependencies(self):
        """get all targets with potential dependencies"""
        for _, targ in self._targets.items():
            yield from targ.get_dependencies(recursive=True)
            yield targ

    def manage_targets(self, iterable):
        """manage the targets: group them and remove duplicates"""
        groups = {}
        for targ in iterable:
            identifier = targ.get_target_group()
            if identifier not in groups:
                groups[identifier] = []
            groups[identifier].append(targ)
        for identifier, targets in sorted(groups.items()):
            yield from no_duplicates(targets)

    def all_targets(self):
        """get all targets, duplicates only once"""
        yield from self.manage_targets(self.targets_with_dependencies())


class MakeFileTarget:
    """manages a target in a makefile"""

    TAB = "\t"
    GROUP_IDENTIFIER = _MFIdentifier.get("GENERIC")

    def __init__(self, name, dependencies=None, silent=None):
        self.name = name
        self.path = "."
        if dependencies is None:
            dependencies = []
        for dep in dependencies:
            if not isinstance(dep, MakeFileTarget):
                raise TypeError("dep must be an instance of MakeFileTarget")
        self.dependencies = dependencies
        if silent is None:
            print("choose default silent state for target", self.name)
            self._silent = type(self).GROUP_IDENTIFIER.default_silent_state
            print(self._silent)

    @property
    def is_silent(self):
        """access silent state of the target"""
        return self._silent

    @classmethod
    def get_target_group(cls):
        """get a group identifier"""
        return cls.GROUP_IDENTIFIER

    def get_dependencies(self, recursive=True):
        """recursively get all depenendcies"""
        for dep in self.dependencies:
            if recursive:
                yield from dep.get_dependencies(recursive=True)
            yield dep

    def __eq__(self, other):
        return self.target_name() == other.target_name()

    def __gt__(self, other):
        return self.target_name() > other.target_name()

    def target_name(self):
        """get the proper target name"""
        return self.name

    def include_as(self):
        """get the proper elements how to include the target"""
        return self.name

    def get_incdir_contributions(self):
        """get the include directory path"""
        return
        yield

    def get_libdir_contributions(self):
        """get the library directory path"""
        return
        yield

    def get_loclib_contributions(self):
        """get local libs"""
        return
        yield

    def get_extlib_contributions(self):
        """get external libs"""
        return
        yield

    def get_scfile_contributions(self):
        """get source"""
        return
        yield

    def get_obfile_contributions(self):
        """get object files"""
        return
        yield

    def get_hdfile_contributions(self):
        """get header files"""
        return
        yield

    def target_get_makefile_lines(self):
        """get the lines that have to be appended in the makefile"""
        if self.is_silent:
            return
        depnames = " ".join(dep.target_name() for dep in self.dependencies)
        yield f"{self.target_name()}: {depnames}"
        for line in self.generate():
            if line is not None:
                yield f"{self.TAB}" + line

    def generate(self, *flags):
        """get the lines that actually generate the target"""
        flags = list(flags)
        return
        yield

    def summarize_contributions(self):
        """generate the include dirs, lib dirs and the line for dependencies required"""
        loclibs = []
        extlibs = []
        scfiles = []
        obfiles = []
        hdfiles = []
        incdirs = []
        libdirs = []
        for dep in self.dependencies:
            loclibs.extend(list(dep.get_loclib_contributions()))
            extlibs.extend(list(dep.get_extlib_contributions()))
            scfiles.extend(list(dep.get_scfile_contributions()))
            obfiles.extend(list(dep.get_obfile_contributions()))
            hdfiles.extend(list(dep.get_hdfile_contributions()))
            incdirs.extend(list(dep.get_incdir_contributions()))
            libdirs.extend(list(dep.get_libdir_contributions()))
        loclibs = no_duplicates(loclibs)
        extlibs = no_duplicates(extlibs)
        scfiles = no_duplicates(scfiles)
        obfiles = no_duplicates(obfiles)
        hdfiles = no_duplicates(hdfiles)
        incdirs = no_duplicates(incdirs)
        libdirs = no_duplicates(libdirs)
        return {
            "loclibs": loclibs,
            "extlibs": extlibs,
            "scfiles": scfiles,
            "obfiles": obfiles,
            "hdfiles": hdfiles,
            "incdirs": incdirs,
            "libdirs": libdirs,
        }


# gen = ["Hello  World", "Hello World", "Hello        WOrld"]

# mfm = MakeFileManager("test")
# for line in mfm.filter_double_space(gen):
#     print(line)

# print()
# print()
# for line in mfm.get_makefile_lines():
#     print(line)


print(MFGID_SOURCE.default_silent_state)
